### PR TITLE
build: update ip - test-osuosl-ubuntu14-ppc64_be-2

### PR DESCRIPTION
**Pull request by mhdawson**
As per issue https://github.com/nodejs/build/issues/420
updated ip for test-osuosl-ubuntu14-ppc64_be-2

### CODE REVIEW

**Comment by jbergstroem** [comment]
LGTM. Perhaps keep this open and add the other floating ip's which is likely to cause issues shortly?

**Comment by mhdawson** [comment]
@jbergstroem  believe we have not lost/fixed all that will happen.

Updated PR to include all that needed updates as well as renaming of machines for le to use the standard naming convention.  

Should be good to land now.

**Comment by jbergstroem** [comment]
Lets get it in!

**Comment by mhdawson** [comment]
Landed as 96ba7214cb996a9396b06c1e6eae5484551f2d3f

**Pull request closed without merging**
