### PR TITLE
WWW changes for ChakraCore nightlies and releases

### PR DESCRIPTION
**Pull request by joaocgreis**
~DO NOT LAND!~

This PR includes the changes made live in the server, to make them public and accept feedback. This was not tested with Ansible.

Ref: https://github.com/nodejs/build/issues/527

### CODE REVIEW

**Comment by rvagg** [comment]
lgtm, nightly building crontab job lives in tasks/tools.yaml if you want to add that too, might need to adjust https://github.com/nodejs/nodejs-nightly-builder too I suppose

**Comment by joaocgreis** [comment]
Rebased and added changes to start the nightly build with `nodejs-nightly-builder`.

**Comment by joaocgreis** [comment]
This has been live on the server for some months now, I believe we should land even if only to make Ansible consistent with what's in the server. This is likely to be improved in the future, but is stable as is.

@nodejs/build if there are no objections I'll land this tomorrow.

**Comment by gibfahn** [comment]
+1 on landing.

**Comment by joaocgreis** [comment]
Thanks! Landed in https://github.com/nodejs/build/compare/9774dae...e5d81e9

**Pull request closed without merging**
