### PR TITLE
[WIP] aix ansible setup scripts

### PR DESCRIPTION
**Pull request by BethGriggs**
Work in progress - looking at reducing the steps in [manualBootstrap.md](https://github.com/nodejs/build/blob/master/setup/aix61/manualBootstrap.md)

### CODE REVIEW

**Comment by jbergstroem** [comment]
@BethGriggs hey, thanks for this! Seeing how we're moving away from the "old" ansible scripts (that lives in setup) it would be great if you could adapt this to the new structure that lives in "ansible".

**Comment by gibfahn** [comment]
@jbergstroem yeah, I asked @BethGriggs to put this up as is so that people could look at it. The plan is to put it into `ansible/`.

**Comment by jbergstroem** [comment]
seems to be an opportunity for reusing what we've done in other setups too, like ccache. I suspect the bootstrap will be the most different path for AIX.

**Comment by gibfahn** [comment]
>seems to be an opportunity for reusing what we've done in other setups too, like ccache. I suspect bootstrap will be the most different path for AIX.

Yeah definitely. TBH it was easiest for testing to just put a single file together, reusing what we already have is the next step 😁 .

**Comment by gdams** [comment]
We need to add the ramdisk setup to the ansible playbook too, shouldn't be too hard to add

**Comment by maclover7** [comment]
ping @BethGriggs @gibfahn

**Comment by BethGriggs** [comment]
I have not had time to progress this for quite a while, I think I'll close this PR. 

//cc @gibfahn or @nodejs/platform-aix who might want to pick up from where I got to

**Comment by mhdawson** [comment]
I believe that @gibfahn was going to be looking at AIX ansible this week, but if so reasonable to open new PR.

**Pull request closed without merging**
