### PR TITLE
ansible: use non-deprecated way to connect Jenkins agents

### PR DESCRIPTION
**Pull request by targos**
- **ansible,jenkins: use "agent" naming**
- **ansible: use non-deprecated way to connect Jenkins agents**

### CODE REVIEW

**Comment by targos** [comment]
I'll try to deploy on some nodes if it looks good to the team.

**Review by MoLow — APPROVED** [review]
RSLGTM. if it works

**Review by richardlau — APPROVED** [review]

**Comment by targos** [comment]
Deployed on:
- https://ci.nodejs.org/computer/test%2Ddigitalocean%2Dfedora32%2Dx64%2D1/
- https://ci.nodejs.org/computer/test%2Ddigitalocean%2Ddebian11%2Dx64%2D1/
- https://ci.nodejs.org/computer/test%2Ddigitalocean%2Drhel8%2Dx64%2D1/
- https://ci.nodejs.org/computer/test%2Ddigitalocean%2Dubuntu2204%2Dx64%2D1/

Note that I had to manually ssh to the machines and run `systemctl daemon-reload; systemctl restart jenkins` before it took effect.

**Comment by richardlau** [comment]
I'm setting up a [replacement machine](https://ci.nodejs.org/computer/test-ibm-ubuntu2204-x64-1/) which appears to need these changes to connect successfully. Without these changes the agent hits a StringIndexOutOfBoundsException and fails to start:
```
Mar 18 18:04:26 test-ibm-ubuntu2204-x64-1 systemd[1]: Started Jenkins agent.
Mar 18 18:04:26 test-ibm-ubuntu2204-x64-1 java[14398]: WARNING: The "-jnlpUrl" argument is deprecated. Use "-url" and "-name" instead, potentially also passing in "-webSocket", "-tunnel", and/or work director>
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: Mar 18, 2024 6:04:27 PM hudson.remoting.Launcher createEngine
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: INFO: Setting up agent: test-ibm-ubuntu2204-x64-1
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: Mar 18, 2024 6:04:27 PM hudson.remoting.Engine startEngine
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: INFO: Using Remoting version: 3206.vb_15dcf73f6a_9
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: Mar 18, 2024 6:04:27 PM hudson.remoting.Engine startEngine
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: WARNING: No Working Directory. Using the legacy JAR Cache location: /home/iojs/.jenkins/cache/jars
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: Mar 18, 2024 6:04:27 PM hudson.remoting.Launcher$CuiListener status
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: INFO: Locating server among [https://ci.nodejs.org/]
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: Mar 18, 2024 6:04:27 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: Mar 18, 2024 6:04:27 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: INFO: Remoting TCP connection tunneling is enabled. Skipping the TCP Agent Listener Port availability check
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: Mar 18, 2024 6:04:27 PM hudson.remoting.Launcher$CuiListener error
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: SEVERE: String index out of range: 0
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]:         at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]:         at java.base/java.lang.String.charAt(String.java:1517)
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]:         at org.jenkinsci.remoting.engine.HostPort.splitHostPort(HostPort.java:21)
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]:         at org.jenkinsci.remoting.engine.HostPort.<init>(HostPort.java:16)
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]:         at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:326)
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]:         at hudson.remoting.Engine.innerRun(Engine.java:809)
Mar 18 18:04:27 test-ibm-ubuntu2204-x64-1 java[14398]:         at hudson.remoting.Engine.run(Engine.java:563)
Mar 18 18:04:28 test-ibm-ubuntu2204-x64-1 systemd[1]: jenkins.service: Main process exited, code=exited, status=255/EXCEPTION
Mar 18 18:04:28 test-ibm-ubuntu2204-x64-1 systemd[1]: jenkins.service: Failed with result 'exit-code'.
Mar 18 18:04:28 test-ibm-ubuntu2204-x64-1 systemd[1]: jenkins.service: Consumed 1.851s CPU time.
```

**Pull request merged**
