### PR TITLE
ansible: add test-digitalocean-rhel9-x64-1

### PR DESCRIPTION
**Pull request by richardlau**
Refs: https://github.com/nodejs/build/pull/3663

---

Created with custom image `rhel-9.3-x86_64-kvm.qcow2` uploaded to DigitalOcean from https://access.redhat.com/downloads/content/rhel.

### CODE REVIEW

**Comment by richardlau** [comment]
Test build: https://ci.nodejs.org/job/richardlau-node-test-commit-linux/15/nodes=rhel9-x64/console

**Review by targos — APPROVED** [review]

**Comment by richardlau** [comment]
Two builds for `main` have failed on the new VM. I'm running a test build on the IBM hosted rhel9-x64 machine to check if that builds `main` (V8 12.2 landed on main since I last ran a test build). Given that we seemed to need swap in addition to the 4GB RAM to build on rhel8-x64 we might need to add swap for rhel9-x64 as well. (FWIW unlike the rhel8 VMs on IBM Cloud it looks like the rhel9 VM on IBM Cloud was created without swap which is consistent with this droplet.)

**Comment by richardlau** [comment]
Added 2GB of swap to both rhel9-x64 VMs.
Test builds:
- [test-digitalocean-rhel9-x64-1](https://ci.nodejs.org/computer/test-digitalocean-rhel9-x64-1): https://ci.nodejs.org/job/richardlau-node-test-commit-linux/18/nodes=rhel9-x64/console
- [test-ibm-rhel9-x64-1](https://ci.nodejs.org/computer/test-ibm-rhel9-x64-1): https://ci.nodejs.org/job/richardlau-node-test-commit-linux/19/nodes=rhel9-x64/console

**Review by MoLow — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
