### PR TITLE
ansible: python3 for freebsd (for linting)

### PR DESCRIPTION
**Pull request by rvagg**
/R= @cclauss

### CODE REVIEW

**Comment by cclauss** [comment]
Related to #1639

**Comment by rvagg** [comment]
```
$ python3 --version
Python 3.6.7
```

there is a `python37` package but it looks like `python3` has given us `python36`, and I can't find a pip for 37

**Comment by cclauss** [comment]
✅ Let's stick with Python 3.6.7.

**Comment by cclauss** [comment]
✅ This change should enable us to add the command __make lint-py PYTHON=python3__

**Comment by cclauss** [comment]
Do we need more approvals on this one?

**Comment by thefourtheye** [comment]
cc @nodejs/build

**Comment by thefourtheye** [comment]
I believe this is ready to be merged. Can anybody from @nodejs/build take a look at this and merge?

**Comment by refack** [comment]
I'll run the playbook, update the job and if everything goes smoothly I'll merge.

**Comment by refack** [comment]
So the workers are setup, and the a cloned-edited job works as expected. That is fails with:
```
PYTHONPATH=tools/pip python3 -m flake8 . \
	--count --show-source --statistics --select=E901,E999,F821,F822,F823 \
	--exclude=.git,deps,lib,src,tools/*_macros.py,tools/gyp,tools/inspector_protocol,tools/jinja2,tools/markupsafe,tools/pip
./test/fixtures/wpt/encoding/resources/single-byte-raw.py:3:52: F821 undefined name 'xrange'
  response.content = "".join(chr(byte) for byte in xrange(255))
                                                   ^
1     F821 undefined name 'xrange'
1
gmake: *** [Makefile:1295: lint-py] Error 1
```

A PR was opened in upstream WPT repo - https://github.com/web-platform-tests/wpt/pull/14973
and in node core - https://github.com/nodejs/node/pull/25614

**Comment by refack** [comment]
Has been run on worker.

**Pull request merged**
