### PR TITLE
doc: add minutes for build WG meeting 2016-12-20

### PR DESCRIPTION
**Pull request by gibfahn**
doc: add minutes for build WG meeting 2016-12-20

### CODE REVIEW

**Comment by piccoloaiutante** [comment]
Just finished to listen the recorded version. I will come back for sure @jbergstroem and thanks for the right pronunciation of my name :-).

@joaocgreis in issue https://github.com/nodejs/build/issues/495 the other thing good for first contribution that you mentioned were:

- Generating  .rdp and/or .remmina files (I have a rough script for Remmina that can serve as a starting point).
- Handle Windows secrets better - passwords are used only for Windows and currently the file we have is not parsable, so we can decide for something better that Ansible can pick from the secrets (currently I have a custom script to generate host_vars).
- vcbuild.bat support for #387 , porting what is currently in the Makefile (introduced initially in nodejs/node#4704 ).

What do you think is the best to go on?

**Comment by joaocgreis** [comment]
@piccoloaiutante It's up to you, which one do you prefer? Since now you have some experience with ansible, there is a more complex task that you might also consider: adapt the current Windows ansible scripts to the new ansible scripts at https://github.com/jbergstroem/build/tree/feature/refactor-the-world/ansible . It would be great to find a way to include Windows there without using a `if(windows)` everywhere and while keeping it clean. We can discuss this more if you want to take it! Actually it would be better to do the first two points you mentioned (remmina/rdp and secrets) after this. However the last point (v8 tests) is independent of this and would also be nice to have.

**Comment by piccoloaiutante** [comment]
@joaocgreis perfect i'll go on with the first point "Generating .rdp and/or .remmina files (I have a rough script for Remmina that can serve as a starting point)."

**Comment by piccoloaiutante** [comment]
@joaocgreis can you share with me your script for generating .remmina file?

**Comment by joaocgreis** [comment]
@piccoloaiutante Sorry for the delay, I was out the last few weeks. Here it is: https://gist.github.com/joaocgreis/208e87942cba416467490947d7385efa This is just a prototype that I made to get me through, feel free to improve! Developing this in Johan's branch would be great, even if you do not port our current Windows setup scripts. There is already ssh config file generation there, this would be the equivalent for Windows. Thanks a lot!

**Comment by piccoloaiutante** [comment]
Excellent @joaocgreis, thanks

**Comment by piccoloaiutante** [comment]
@joaocgreis I've started looking at your script and my ideal goal would be to arrive to write it as a plugin for Ansible like the one @jbergstroem has written for ssh (https://github.com/jbergstroem/build/blob/feature/refactor-the-world/ansible/plugins/library/ssh_config.py) and used here (https://github.com/jbergstroem/build/blob/feature/refactor-the-world/ansible/playbooks/write-ssh-config.yml). How does it sounds to you?

**Comment by joaocgreis** [comment]
@piccoloaiutante sounds great! Some ideas/issues come to my head:

- The authentication method for all servers currently in [inventory](https://github.com/jbergstroem/build/blob/feature/refactor-the-world/ansible/inventory.yml) is SSH keys. We have the key in secrets and who wants to use Johan's generator will only have to drop the key in secrets. But for Windows it'll have to be passwords, so you'll have to adapt this a little. In that gist above there is an example with the exact same format that we have in secrets now, but I don't think it's optimal, and we can change it. Perhaps use a yaml format instead (like the inventory) that Ansible can parse. Or save the full `host_vars` for Windows in secrets, but that will have a lot of redundant information. Ideally, usernames/passwords and ports (just to be extra safe) should be stored in secrets and everything else in the inventory.
- Azure hosts are the only ones that use DNS, everything else uses IP addresses. The IP address will change if we have to turn off the server for some reason, so use DNS wherever possible (is it possible to replace IP by DNS in the inventory?).

**Comment by piccoloaiutante** [comment]
@joaocgreis that's what i'm currently working on: 
https://gist.github.com/piccoloaiutante/575d5e9d17729ebbca3a1d64f1956e8f
it's still based on you old schema. Next step will be to move it to the yams format that Ansible can parse.

**Comment by piccoloaiutante** [comment]
@joaocgreis i've updated the gist with a working version of the plugin, with yaml file. It works and produces one remmina file per server. The only thing that I need before raising a PR is an example of encrypted server_list with certificate so I can be sure that the gpg decryption works smoothly. Here is an example of server list in yaml:
```yaml
test-example-win10-x64-1:
  ip: node-win10.example.org
  port: 55443
  username: Administrator
  password: password1111

test-example-win10-x64-2:
  ip: node-win10-2.example.org
  port: 55443
  username: Administrator
  password: password1111
```

**Comment by joaocgreis** [comment]
@piccoloaiutante that's fantastic! You can use dotgpg to encrypt the file I sent you. Here are some instructions:

* Install with `sudo gem install dotgpg`
* Edit a file with `dotgpg edit <filename>` if you have access
* Show the contents of a file without editing with `dotgpg cat <filename>` if you have access (same as `gpg --decrypt <filename>`)
* New GPG keys can be added by users who already have access by using `dotgpg add` and pasting in a new key (exported using `gpg --armor --export <email>` or `dotgpg key`)
* See the [dotgpg](https://github.com/ConradIrwin/dotgpg) page or `dotgpg --help` for more information

Let me know if this is not enough or if you have trouble setting it up. Feel free to take this to IRC or email if you prefer.

**Comment by piccoloaiutante** [comment]
@joaocgreis I've tested it and it worked with a dotgpg created file. I've opened a pr against @jbergstroem `refactor-the-world` build branch (https://github.com/jbergstroem/build/pull/2/).

As next task I have:
```
vcbuild.bat support for https://github.com/nodejs/build/issues/387, porting what is currently in the Makefile (introduced initially in nodejs/node#4704 ).
```

Is it still the next priority? We can discuss about in next WG meeting.

**Comment by joaocgreis** [comment]
@piccoloaiutante thanks for your PR, I'll take a look! The work to support v8 tests in Windows is still relevant, please go ahead if you'd like to take that one.

**Comment by kunalspathak** [comment]
I have started looking into `v8 tests in Windows `.

**Comment by kunalspathak** [comment]
Update: On my local machine, i see 7 failures. Do we ignore it? Who is the right contact to check this about? I am on [5.8-lkgr](https://chromium.googlesource.com/v8/v8.git/+/2f06375912a79b55603cc75306738101921ce80a).

```cmd
[06:35|% 100|+ 27873|-   7]: Done
```

**Comment by joaocgreis** [comment]
cc @ofrobots , if it's better to open an issue let us know where. Thanks!

**Comment by ofrobots** [comment]
@kunalspathak can you paste which tests failed?

/cc @nodejs/v8

**Comment by fhinkel** [comment]
@joaocgreis Do you mind opening an issue on the [V8 tracker](https://bugs.chromium.org/p/v8/issues/entry)? I don't have a Windows machine and it's easier for us to track progress if we have an issue. Thanks! 🙇

**Comment by kunalspathak** [comment]
@ofrobots - I did a reset to my environment. I will share that failures with you as soon as I run into it again.

**Comment by kunalspathak** [comment]
@ofrobots  - Here are the details of test failures.

Command ran
```
python tools\run-tests.py --arch=x64 --mode=release --quickcheck --no-presubmit --shell-dir=out/x64.release --junitout ./v8-tap.xml
```
Test failures:

<details><code><pre>
D:\git\node-chakracore\deps\v8>python tools\run-tests.py --arch=x64 --mode=release --quickcheck --no-presubmit --shell-dir=out/x64.release --junitout ./v8-tap.xml
>>> Running tests for x64.release
Traceback (most recent call last):
  File "tools\run-tests.py", line 932, in <module>
    sys.exit(Main())
  File "tools\run-tests.py", line 720, in Main
    code = Execute(arch, mode, args, options, suites)
  File "tools\run-tests.py", line 748, in Execute
    raise Exception('Could not find shell_dir: "%s"' % shell_dir)
Exception: Could not find shell_dir: "out/x64.release"

D:\git\node-chakracore\deps\v8>start.

D:\git\node-chakracore\deps\v8>python tools\run-tests.py --arch=x64 --mode=release --quickcheck --no-presubmit --shell-dir=out.gn/x64.release --junitout ./v8-tap.xml
>>> Running tests for x64.release
=== debugger/debug/debug-sourceinfo ===
============ Stress 1/5 ============
D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253: Failure: expected <1608> found <1635>

Stack: Error
    at new MjsUnitAssertionError (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:31:16)
    at failWithMessage (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253:11)
    at fail (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:270:12)
    at assertEquals (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:341:7)
    at D:\git\node-chakracore\deps\v8\test\debugger\debug/debug-sourceinfo.js:85:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:31:16)
    at failWithMessage (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253:11)
    at fail (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:270:12)
    at assertEquals (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:341:7)
    at D:\git\node-chakracore\deps\v8\test\debugger\debug/debug-sourceinfo.js:85:1
Command: D:\git\node-chakracore\deps\v8\out.gn\x64.release\d8.exe --test --random-seed=-1567808436 --stress-opt --always-opt --enable-inspector --allow-natives-syntax --nohard-abort --nodead-code-elimination --nofold-constants D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js D:\git\node-chakracore\deps\v8\test\debugger\test-api.js D:\git\node-chakracore\deps\v8\test\debugger\debug/debug-sourceinfo.js
=== debugger/debug/debug-sourceinfo ===
D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253: Failure: expected <1608> found <1635>

Stack: Error
    at new MjsUnitAssertionError (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:31:16)
    at failWithMessage (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253:11)
    at fail (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:270:12)
    at assertEquals (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:341:7)
    at D:\git\node-chakracore\deps\v8\test\debugger\debug/debug-sourceinfo.js:85:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:31:16)
    at failWithMessage (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253:11)
    at fail (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:270:12)
    at assertEquals (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:341:7)
    at D:\git\node-chakracore\deps\v8\test\debugger\debug/debug-sourceinfo.js:85:1
Command: D:\git\node-chakracore\deps\v8\out.gn\x64.release\d8.exe --test --random-seed=-1567808436 --enable-inspector --allow-natives-syntax --nohard-abort --nodead-code-elimination --nofold-constants D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js D:\git\node-chakracore\deps\v8\test\debugger\test-api.js D:\git\node-chakracore\deps\v8\test\debugger\debug/debug-sourceinfo.js
=== mjsunit/type-profile/collect-type-profile ===
{}
{"519":["Object","number","string","number"],"526":["undefined","boolean","undefined","undefined"],"723":["Object","number","string","number"]}
D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253: Failure (function testFunction(param, flag) {
  // We want to test 2 different return positions in one function.
  if (flag) {
    var first_var = param;
    return first_var;
  }
  var second_var = param;
  return second_var;
} failed):
expected:
"{\"503\":[\"Object\",\"number\",\"string\",\"number\"],\"510\":[\"undefined\",\"boolean\",\"undefined\",\"undefined\"],\"699\":[\"Object\",\"number\",\"string\",\"number\"]}"
found:
"{\"519\":[\"Object\",\"number\",\"string\",\"number\"],\"526\":[\"undefined\",\"boolean\",\"undefined\",\"undefined\"],\"723\":[\"Object\",\"number\",\"string\",\"number\"]}"

Stack: Error
    at new MjsUnitAssertionError (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:31:16)
    at failWithMessage (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253:11)
    at fail (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:270:12)
    at assertEquals (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:341:7)
    at check_collect_types (D:\git\node-chakracore\deps\v8\test\mjsunit\type-profile/collect-type-profile.js:12:5)
    at D:\git\node-chakracore\deps\v8\test\mjsunit\type-profile/collect-type-profile.js:40:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:31:16)
    at failWithMessage (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253:11)
    at fail (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:270:12)
    at assertEquals (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:341:7)
    at check_collect_types (D:\git\node-chakracore\deps\v8\test\mjsunit\type-profile/collect-type-profile.js:12:5)
    at D:\git\node-chakracore\deps\v8\test\mjsunit\type-profile/collect-type-profile.js:40:1
Command: D:\git\node-chakracore\deps\v8\out.gn\x64.release\d8.exe --test --random-seed=-1567808436 --nohard-abort --nodead-code-elimination --nofold-constants --type-profile --turbo --allow-natives-syntax D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js D:\git\node-chakracore\deps\v8\test\mjsunit\type-profile/collect-type-profile.js
=== mjsunit/type-profile/collect-type-profile ===
============ Stress 1/5 ============
{}
{"519":["Object","number","string","number"],"526":["undefined","boolean","undefined","undefined"],"723":["Object","number","string","number"]}
D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253: Failure (function testFunction(param, flag) {
  // We want to test 2 different return positions in one function.
  if (flag) {
    var first_var = param;
    return first_var;
  }
  var second_var = param;
  return second_var;
} failed):
expected:
"{\"503\":[\"Object\",\"number\",\"string\",\"number\"],\"510\":[\"undefined\",\"boolean\",\"undefined\",\"undefined\"],\"699\":[\"Object\",\"number\",\"string\",\"number\"]}"
found:
"{\"519\":[\"Object\",\"number\",\"string\",\"number\"],\"526\":[\"undefined\",\"boolean\",\"undefined\",\"undefined\"],\"723\":[\"Object\",\"number\",\"string\",\"number\"]}"

Stack: Error
    at new MjsUnitAssertionError (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:31:16)
    at failWithMessage (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253:11)
    at fail (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:270:12)
    at assertEquals (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:341:7)
    at check_collect_types (D:\git\node-chakracore\deps\v8\test\mjsunit\type-profile/collect-type-profile.js:12:5)
    at D:\git\node-chakracore\deps\v8\test\mjsunit\type-profile/collect-type-profile.js:40:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:31:16)
    at failWithMessage (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253:11)
    at fail (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:270:12)
    at assertEquals (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:341:7)
    at check_collect_types (D:\git\node-chakracore\deps\v8\test\mjsunit\type-profile/collect-type-profile.js:12:5)
    at D:\git\node-chakracore\deps\v8\test\mjsunit\type-profile/collect-type-profile.js:40:1
Command: D:\git\node-chakracore\deps\v8\out.gn\x64.release\d8.exe --test --random-seed=-1567808436 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --type-profile --turbo --allow-natives-syntax D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js D:\git\node-chakracore\deps\v8\test\mjsunit\type-profile/collect-type-profile.js
=== mjsunit/tools/tickprocessor ===
=== testProcessing-Default ===
===== actual output: =====
Statistical profiling result from v8.log, (13 ticks, 4 unaccounted, 0 excluded).

 [Shared libraries]:
   ticks  total  nonlib   name
      3   23.1%          /lib32/libm-2.7.so
      1    7.7%          ffffe000-fffff000

 [JavaScript]:
   ticks  total  nonlib   name

 [C++]:
   ticks  total  nonlib   name
      2   15.4%   22.2%  v8::internal::Runtime_Math_exp(v8::internal::Arguments)
      1    7.7%   11.1%  v8::internal::JSObject::LookupOwnRealNamedProperty(v8::internal::String*, v8::internal::LookupResult*)
      1    7.7%   11.1%  v8::internal::HashTable<v8::internal::StringDictionaryShape, v8::internal::String*>::FindEntry(v8::internal::String*)
      1    7.7%   11.1%  exp

 [Summary]:
   ticks  total  nonlib   name
      0    0.0%    0.0%  JavaScript
      5   38.5%   55.6%  C++
      0    0.0%    0.0%  GC
      4   30.8%          Shared libraries
      4   30.8%          Unaccounted

 [C++ entry points]:
   ticks    cpp   total   name
      2   40.0%   15.4%  v8::internal::Runtime_Math_exp(v8::internal::Arguments)
      1   20.0%    7.7%  v8::internal::JSObject::LookupOwnRealNamedProperty(v8::internal::String*, v8::internal::LookupResult*)
      1   20.0%    7.7%  v8::internal::HashTable<v8::internal::StringDictionaryShape, v8::internal::String*>::FindEntry(v8::internal::String*)
      1   20.0%    7.7%  exp

 [Bottom up (heavy) profile]:
  Note: percentage shows a share of a particular caller in the total
  amount of its parent calls.
  Callers occupying less than 1.0% are not shown.

   ticks parent  name
      4   30.8%  UNKNOWN

      3   23.1%  /lib32/libm-2.7.so

      2   15.4%  v8::internal::Runtime_Math_exp(v8::internal::Arguments)

      1    7.7%  v8::internal::JSObject::LookupOwnRealNamedProperty(v8::internal::String*, v8::internal::LookupResult*)

      1    7.7%  v8::internal::HashTable<v8::internal::StringDictionaryShape, v8::internal::String*>::FindEntry(v8::internal::String*)

      1    7.7%  ffffe000-fffff000

      1    7.7%  exp

===== expected output: =====
===== File: D:\git\node-chakracore\deps\v8\test\mjsunit\tools/tickprocessor-test.default =====
Statistical profiling result from v8.log, (13 ticks, 2 unaccounted, 0 excluded).

 [Shared libraries]:
   ticks  total  nonlib   name
      3   23.1%          /lib32/libm-2.7.so
      1    7.7%          ffffe000-fffff000

 [JavaScript]:
   ticks  total  nonlib   name

 [C++]:
   ticks  total  nonlib   name
      2   15.4%   22.2%  v8::internal::Runtime_Math_exp(v8::internal::Arguments)
      1    7.7%   11.1%  v8::internal::JSObject::LookupOwnRealNamedProperty(v8::internal::String*, v8::internal::LookupResult*)
      1    7.7%   11.1%  v8::internal::HashTable<v8::internal::StringDictionaryShape, v8::internal::String*>::FindEntry(v8::internal::String*)
      1    7.7%   11.1%  exp

 [Summary]:
   ticks  total  nonlib   name
      0    0.0%    0.0%  JavaScript
      5   38.5%   55.6%  C++
      0    0.0%    0.0%  GC
      4   30.8%          Shared libraries
      2   15.4%          Unaccounted

 [C++ entry points]:
   ticks    cpp   total   name
      2   40.0%   15.4%  v8::internal::Runtime_Math_exp(v8::internal::Arguments)
      1   20.0%    7.7%  v8::internal::JSObject::LookupOwnRealNamedProperty(v8::internal::String*, v8::internal::LookupResult*)
      1   20.0%    7.7%  v8::internal::HashTable<v8::internal::StringDictionaryShape, v8::internal::String*>::FindEntry(v8::internal::String*)
      1   20.0%    7.7%  exp

 [Bottom up (heavy) profile]:
  Note: percentage shows a share of a particular caller in the total
  amount of its parent calls.
  Callers occupying less than 1.0% are not shown.

   ticks parent  name
      3   23.1%  /lib32/libm-2.7.so
      3  100.0%    LazyCompile: exp native math.js:41
      3  100.0%      Script: exp.js

      2   15.4%  v8::internal::Runtime_Math_exp(v8::internal::Arguments)
      2  100.0%    LazyCompile: exp native math.js:41
      2  100.0%      Script: exp.js

      2   15.4%  UNKNOWN
      1   50.0%    LazyCompile: exp native math.js:41
      1  100.0%      Script: exp.js

      1    7.7%  v8::internal::JSObject::LookupOwnRealNamedProperty(v8::internal::String*, v8::internal::LookupResult*)
      1  100.0%    Script: exp.js

      1    7.7%  v8::internal::HashTable<v8::internal::StringDictionaryShape, v8::internal::String*>::FindEntry(v8::internal::String*)
      1  100.0%    Script: exp.js

      1    7.7%  ffffe000-fffff000

      1    7.7%  exp
      1  100.0%    LazyCompile: exp native math.js:41
      1  100.0%      Script: exp.js


D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253: Failure:
expected:
[]
found:
["line 0: expected <Statistical profiling result from v8.log, (13 ticks, 2 unaccounted, 0 excluded).\r> found <Statistical profiling result from v8.log, (13 ticks, 4 unaccounted, 0 excluded).>\n","line 1: expected <\r> found <>\n","line 2: expected < [Shared libraries]:\r> found < [Shared libraries]:>\n","line 3: expected <   ticks  total  nonlib   name\r> found <   ticks  total  nonlib   name>\n","line 4: expected <      3   23.1%          /lib32/libm-2.7.so\r> found <      3   23.1%          /lib32/libm-2.7.so>\n","line 5: expected <      1    7.7%          ffffe000-fffff000\r> found <      1    7.7%          ffffe000-fffff000>\n","line 6: expected <\r> found <>\n","line 7: expected < [JavaScript]:\r> found < [JavaScript]:>\n","line 8: expected <   ticks  total  nonlib   name\r> found <   ticks  total  nonlib   name>\n","line 9: expected <\r> found <>\n","line 10: expected < [C++]:\r> found < [C++]:>\n","line 11: expected <   ticks  total  nonlib   name\r> found <   ticks  total  nonlib   name>\n","line 12: expected <      2   15.4%   22.2%  v8::internal::Runtime_Math_exp(v8::internal::Arguments)\r> found <      2   15.4%   22.2%  v8::internal::Runtime_Math_exp(v8::internal::Arguments)>\n","line 13: expected <      1    7.7%   11.1%  v8::internal::JSObject::LookupOwnRealNamedProperty(v8::internal::String*, v8::internal::LookupResult*)\r> found <      1    7.7%   11.1%  v8::internal::JSObject::LookupOwnRealNamedProperty(v8::internal::String*, v8::internal::LookupResult*)>\n","line 14: expected <      1    7.7%   11.1%  v8::internal::HashTable<v8::internal::StringDictionaryShape, v8::internal::String*>::FindEntry(v8::internal::String*)\r> found <      1    7.7%   11.1%  v8::internal::HashTable<v8::internal::StringDictionaryShape, v8::internal::String*>::FindEntry(v8::internal::String*)>\n","line 15: expected <      1    7.7%   11.1%  exp\r> found <      1    7.7%   11.1%  exp>\n","line 16: expected <\r> found <>\n","line 17: expected < [Summary]:\r> found < [Summary]:>\n","line 18: expected <   ticks  total  nonlib   name\r> found <   ticks  total  nonlib   name>\n","line 19: expected <      0    0.0%    0.0%  JavaScript\r> found <      0    0.0%    0.0%  JavaScript>\n","line 20: expected <      5   38.5%   55.6%  C++\r> found <      5   38.5%   55.6%  C++>\n","line 21: expected <      0    0.0%    0.0%  GC\r> found <      0    0.0%    0.0%  GC>\n","line 22: expected <      4   30.8%          Shared libraries\r> found <      4   30.8%          Shared libraries>\n","line 23: expected <      2   15.4%          Unaccounted\r> found <      4   30.8%          Unaccounted>\n","line 24: expected <\r> found <>\n","line 25: expected < [C++ entry points]:\r> found < [C++ entry points]:>\n","line 26: expected <   ticks    cpp   total   name\r> found <   ticks    cpp   total   name>\n","line 27: expected <      2   40.0%   15.4%  v8::internal::Runtime_Math_exp(v8::internal::Arguments)\r> found <      2   40.0%   15.4%  v8::internal::Runtime_Math_exp(v8::internal::Arguments)>\n","line 28: expected <      1   20.0%    7.7%  v8::internal::JSObject::LookupOwnRealNamedProperty(v8::internal::String*, v8::internal::LookupResult*)\r> found <      1   20.0%    7.7%  v8::internal::JSObject::LookupOwnRealNamedProperty(v8::internal::String*, v8::internal::LookupResult*)>\n","line 29: expected <      1   20.0%    7.7%  v8::internal::HashTable<v8::internal::StringDictionaryShape, v8::internal::String*>::FindEntry(v8::internal::String*)\r> found <      1   20.0%    7.7%  v8::internal::HashTable<v8::internal::StringDictionaryShape, v8::internal::String*>::FindEntry(v8::internal::String*)>\n","line 30: expected <      1   20.0%    7.7%  exp\r> found <      1   20.0%    7.7%  exp>\n","line 31: expected <\r> found <>\n","line 32: expected < [Bottom up (heavy) profile]:\r> found < [Bottom up (heavy) profile]:>\n","line 33: expected <  Note: percentage shows a share of a particular caller in the total\r> found <  Note: percentage shows a share of a particular caller in the total>\n","line 34: expected <  amount of its parent calls.\r> found <  amount of its parent calls.>\n","line 35: expected <  Callers occupying less than 1.0% are not shown.\r> found <  Callers occupying less than 1.0% are not shown.>\n","line 36: expected <\r> found <>\n","line 37: expected <   ticks parent  name\r> found <   ticks parent  name>\n","line 38: expected <      3   23.1%  /lib32/libm-2.7.so\r> found <      4   30.8%  UNKNOWN>\n","line 39: expected <      3  100.0%    LazyCompile: exp native math.js:41\r> found <>\n","line 40: expected <      3  100.0%      Script: exp.js\r> found <      3   23.1%  /lib32/libm-2.7.so>\n","line 41: expected <\r> found <>\n","line 42: expected <      2   15.4%  v8::internal::Runtime_Math_exp(v8::internal::Arguments)\r> found <      2   15.4%  v8::internal::Runtime_Math_exp(v8::internal::Arguments)>\n","line 43: expected <      2  100.0%    LazyCompile: exp native math.js:41\r> found <>\n","line 44: expected <      2  100.0%      Script: exp.js\r> found <      1    7.7%  v8::internal::JSObject::LookupOwnRealNamedProperty(v8::internal::String*, v8::internal::LookupResult*)>\n","line 45: expected <\r> found <>\n","line 46: expected <      2   15.4%  UNKNOWN\r> found <      1    7.7%  v8::internal::HashTable<v8::internal::StringDictionaryShape, v8::internal::String*>::FindEntry(v8::internal::String*)>\n","line 47: expected <      1   50.0%    LazyCompile: exp native math.js:41\r> found <>\n","line 48: expected <      1  100.0%      Script: exp.js\r> found <      1    7.7%  ffffe000-fffff000>\n","line 49: expected <\r> found <>\n","line 50: expected <      1    7.7%  v8::internal::JSObject::LookupOwnRealNamedProperty(v8::internal::String*, v8::internal::LookupResult*)\r> found <      1    7.7%  exp>\n","line 51: expected <      1  100.0%    Script: exp.js\r> found <>\n"]

Stack: Error
    at new MjsUnitAssertionError (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:31:16)
    at failWithMessage (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253:11)
    at fail (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:270:12)
    at assertEquals (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:341:7)
    at PrintMonitor.finish (D:\git\node-chakracore\deps\v8\test\mjsunit\tools/tickprocessor.js:378:5)
    at driveTickProcessorTest (D:\git\node-chakracore\deps\v8\test\mjsunit\tools/tickprocessor.js:412:6)
    at testProcessing (D:\git\node-chakracore\deps\v8\test\mjsunit\tools/tickprocessor.js:440:28)
    at D:\git\node-chakracore\deps\v8\test\mjsunit\tools/tickprocessor.js:442:3
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:31:16)
    at failWithMessage (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:253:11)
    at fail (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:270:12)
    at assertEquals (D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js:341:7)
    at PrintMonitor.finish (D:\git\node-chakracore\deps\v8\test\mjsunit\tools/tickprocessor.js:378:5)
    at driveTickProcessorTest (D:\git\node-chakracore\deps\v8\test\mjsunit\tools/tickprocessor.js:412:6)
    at testProcessing (D:\git\node-chakracore\deps\v8\test\mjsunit\tools/tickprocessor.js:440:28)
    at D:\git\node-chakracore\deps\v8\test\mjsunit\tools/tickprocessor.js:442:3
line 5: unknown code state: undefined
line 6: unknown code state: undefined
line 7: unknown code state: undefined
line 8: unknown code state: undefined
line 10: unknown code state: undefined
line 11: unknown code state: undefined
Command: D:\git\node-chakracore\deps\v8\out.gn\x64.release\d8.exe --test --random-seed=-1567808436 --nohard-abort --nodead-code-elimination --nofold-constants -e TEST_FILE_NAME="D:\\git\\node-chakracore\\deps\\v8\\test\\mjsunit\\tools/tickprocessor.js" D:\git\node-chakracore\deps\v8\tools\splaytree.js D:\git\node-chakracore\deps\v8\tools\codemap.js D:\git\node-chakracore\deps\v8\tools\csvparser.js D:\git\node-chakracore\deps\v8\tools\consarray.js D:\git\node-chakracore\deps\v8\tools\profile.js D:\git\node-chakracore\deps\v8\tools\profile_view.js D:\git\node-chakracore\deps\v8\tools\logreader.js D:\git\node-chakracore\deps\v8\tools\tickprocessor.js D:\git\node-chakracore\deps\v8\test\mjsunit\mjsunit.js D:\git\node-chakracore\deps\v8\test\mjsunit\tools/tickprocessor.js
=== inspector/debugger/script-parsed-hash ===
Hash received: 1C6D2E82E4E4F1BA4CB5762843D429DC872EBA18
Hash received: EBF1ECD351E7A3294CB5762843D429DC872EBA18
[FAIL]: unknown hash 2E8017514061BC94478B46106FC9B5336DCD6908
Command: D:\git\node-chakracore\deps\v8\out.gn\x64.release\inspector-test.exe --random-seed=-1567808436 --nohard-abort --nodead-code-elimination --nofold-constants D:\git\node-chakracore\deps\v8\test\inspector\protocol-test.js D:\git\node-chakracore\deps\v8\test\inspector\debugger/script-parsed-hash.js
=== inspector/debugger/script-parsed-hash ===
Hash received: 1C6D2E82E4E4F1BA4CB5762843D429DC872EBA18
Hash received: EBF1ECD351E7A3294CB5762843D429DC872EBA18
[FAIL]: unknown hash 2E8017514061BC94478B46106FC9B5336DCD6908
Command: D:\git\node-chakracore\deps\v8\out.gn\x64.release\inspector-test.exe --random-seed=-1567808436 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants D:\git\node-chakracore\deps\v8\test\inspector\protocol-test.js D:\git\node-chakracore\deps\v8\test\inspector\debugger/script-parsed-hash.js
[06:11|% 100|+ 20443|-   7]: Done
</pre></code></details>

**Pull request merged**
