### PR TITLE
build: update jenkins agent to 256m

### PR DESCRIPTION
**Pull request by mhdawson**
We seemed to be having out of memory issues on some machines.
For example:  https://github.com/nodejs/build/issues/548#issuecomment-269974066.
Bumping up to 256m seems to have resolved so modifying the
ansible config to reflect that.

Fixes: https://github.com/nodejs/build/issues/548

### CODE REVIEW

**Comment by jbergstroem** [comment]
The problem is that some vm's are running on 2G; meaning the more memory we have available for compilation and testing, the better. An idea I've been playing around with in my refactor is passing memory as a variable to the template and overriding it - if needed - for specific providers, operating systems or architectures (all of those are available to test against in Ansible).

**Comment by mhdawson** [comment]
Should I just close this given that we are moving to the refactor ?

**Comment by gibfahn** [comment]
>Should I just close this given that we are moving to the refactor ?

Maybe we should change the default `server_ram` from 128M to 256M in the refactor?

```bash
➜  ansible git:(master) ❯ rg server_ram                                                                                                                                             ~/wrk/com/build/ansible
host_vars/README.md
20:- `server_ram`: how much memory the slave should assign to java-base

roles/jenkins-worker/templates/centos.initd.j2
20:JENKINS_SLAVE_ARGS="-Xmx{{ server_ram|default('128m') }} -jnlpUrl {{ jenkins_url }}/computer/{{ inventory_hostname }}/slave-agent.jnlp -secret {{ secret }}"

roles/jenkins-worker/templates/freebsd.initd.j2
36:jenkins_args="-Xmx{{ server_ram|default('128m') }} -jar ${jenkins_jar} \

roles/jenkins-worker/templates/jenkins_manifest.xml.j2
31:                   exec='{{ java_path[os] }} -Dsun.security.pkcs11.enable-solaris=false -Xmx{{ server_ram|default('128m') }} -jar /home/{{ server_user }}/slave.jar -jnlpUrl {{ jenkins_url }}/computer/{{ inventory_hostname }}/slave-agent.jnlp -secret {{ secret }}'

roles/jenkins-worker/templates/openrc.initd.j2
7:command_args="-Xmx{{ server_ram|default('128m') }} \

roles/jenkins-worker/templates/systemd.service.j2
25:ExecStart=/usr/bin/java -Xmx{{ server_ram|default('128m') }} \

roles/jenkins-worker/templates/upstart.j2
26:  exec java -Xmx{{ server_ram|default('128m') }} \
```

**Comment by jbergstroem** [comment]
server_ram can be overridden from the host vars. The idea was to the specific hosts that needs it allow override.

**Comment by gibfahn** [comment]
Sure, my point was that if we think they'll mostly need 256M rather than 128M then we should consider updating the default. If it's just the odd one then I agree we don't want to.

**Comment by jbergstroem** [comment]
My experience is that they - at least so far - doesn't need more than 128m.

**Comment by gibfahn** [comment]
Might as well close then.

**Comment by jbergstroem** [comment]
I think the issue mutated after the branch landed -- it's much easier to override per host or even per group via config.

**Pull request closed without merging**
