### PR TITLE
ansible: remove smartos test machines

### PR DESCRIPTION
**Pull request by sam-github**
See: https://github.com/nodejs/build/pull/2014

### CODE REVIEW

**Comment by sam-github** [comment]
After this merges I'll remove the machines from https://ci.nodejs.org/computer/

**Comment by sam-github** [comment]
@cclauss :headscratching:  I didn't touch any python, is the flake8 test invalid?

**Comment by richardlau** [comment]
> 
> 
> @cclauss :headscratching: I didn't touch any python, is the flake8 test invalid?

Looks like it was broken by https://github.com/nodejs/build/pull/2024.

**Comment by cclauss** [comment]
https://realpython.com/the-most-diabolical-python-antipattern/

**Comment by sam-github** [comment]
I removed the machines from jenkins.

**Pull request merged**
