### PR TITLE
Update generate-index-html.py

### PR DESCRIPTION
**Pull request by XhmikosR**
nodejs.org backports and fixes

~~So, if the index.html is autogenerated, does this mean that https://github.com/nodejs/benchmarking/pull/289 and https://github.com/nodejs/benchmarking/pull/290 are moot?~~

/CC @Trott @richardlau

### CODE REVIEW

**Comment by XhmikosR** [comment]
https://github.com/nodejs/build/pull/1936/files?w=1

Live preview: <https://stoic-agnesi-bfb346.netlify.com/>

Should be ready now. Feel free to squash when merging

**Comment by richardlau** [comment]
> 
> 
> nodejs.org backports and fixes
> 
> So, if the index.html is autogenerated, does this mean that [nodejs/benchmarking#289](https://github.com/nodejs/benchmarking/pull/289) and [nodejs/benchmarking#290](https://github.com/nodejs/benchmarking/pull/290) are moot?
> 

AFAIK benchmarking.nodejs.org and coverage.nodejs.org are separate sites.

**Comment by XhmikosR** [comment]
You are right, I confused it with coverage. Sorry, I jumped to this as fast as I could and I needed more coffee.

But I think everything should be fine now. I've submitted a couple of PRs to the other 2 projects.

**Comment by XhmikosR** [comment]
@Trott here it is.

This PR includes #1933, so better get that merged first.

**Comment by nschonni** [comment]
@XhmikosR would there be a lot of CSS changes to use an HTML table? Just saw you fix some of the semantics in here, but I can also just raise an issue on the coverage repo if that makes more sense

**Comment by XhmikosR** [comment]
If I did change the semantics that would be a bug :)

I just normalized stuff and fixed the HTML validation errors for the time being. See the non-whitespace diff https://github.com/nodejs/build/pull/1936/files?w=1

That being said, I think that first we need to come up with a solution for the CSS. I don't think it's a good practice to load the nodejs.org CSS because it can break at any time like it already has (I wasn't even aware this was a thing and people did this :P)

After that, we can switch to a table for sure. The amount of CSS depends on how flexible we can be with styling, but from a quick look, I don't think it needs a lot.

I could try doing this in the next days assuming I find a way to develop locally. Just make an issue and CC me and we'll pick it up there.

**Comment by nschonni** [comment]
> If I did change the semantics that would be a bug :)

I just meant fixing the `<main>` :)
I'll open up an issue on this repo

**Comment by mhdawson** [comment]
Don't think this is controversial so landing so we get fixup sooner than later.

**Comment by mhdawson** [comment]
Somehow the UI  landed before I could paste the meta data, sorry.

**Pull request merged**
