### PR TITLE
Add Apple silicon macs

### PR DESCRIPTION
**Pull request by AshCripps**
This pr will add the DTKs kindly donated to us by macstadium and any edits needed to playbooks.

refs: https://github.com/nodejs/TSC/issues/886

@nodejs/build-infra can the ips be added to the test jenkins firewall please.

### CODE REVIEW

**Comment by AshCripps** [comment]
Manual intervention needed so far:

Brew needs a workround patch untill upstream is patched: https://github.com/Homebrew/brew/issues/7857

**Comment by AshCripps** [comment]
Failures:

installing tap2junit: 
```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_pip_payload_FZYqiv/ansible_pip_payload.zip/ansible/module_utils/basic.py", line 2561, in run_command
    cmd = subprocess.Popen(args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception

fatal: [test-macstadium-macos11.0-arm64-2]: FAILED! => {
    "changed": false,
    "cmd": "/usr/local/bin/pip3 install tap2junit",
    "invocation": {
        "module_args": {
            "chdir": null,
            "editable": false,
            "executable": "/usr/local/bin/pip3",
            "extra_args": null,
            "name": [
                "tap2junit"
            ],
            "requirements": null,
            "state": "present",
            "umask": null,
            "use_mirrors": true,
            "version": null,
            "virtualenv": null,
            "virtualenv_command": "virtualenv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    },
    "msg": "[Errno 2] No such file or directory",
    "rc": 2
}
```

**Comment by richardlau** [comment]
Looks like for some reason `pip3` is being used with `python` 2.

**Comment by AshCripps** [comment]
oo good spot, for some reason these brand new macs released this year still come with python 2 as the system python

@richardlau is there a way to set which python ansible uses on the target machine?

**Comment by richardlau** [comment]
> 
> 
> oo good spot, for some reason these brand new macs released this year still come with python 2 as the system python
> 
> @richardlau is there a way to set which python ansible uses on the target machine?

Yes, see e.g. https://github.com/nodejs/build/blob/022ee2187d510e6cb4eb45e9823c436c555b726b/ansible/ansible.cfg#L42

**Comment by AshCripps** [comment]
from updating the python used Its now pointing out that this is the wrong link:
https://github.com/nodejs/build/blob/022ee2187d510e6cb4eb45e9823c436c555b726b/ansible/roles/jenkins-worker/tasks/partials/tap2junit/macos.yml#L7-L11

On the DTK pip is under `/usr/bin/pip3` but I think they will break the playbooks for new macs so might need to make a seperate mac arm file.

in other news I get a clean run through of the playbooks now

**Comment by AshCripps** [comment]
so `test-macstadium-macos11.0-arm64-2` is all setup and I got a build of https://github.com/nodejs/node/pull/34238 complete. saw some V8 failures and a fair few test failures which I think are mentioned in the PR

**Comment by AshCripps** [comment]
Second machine setup, have discovered the `./configure` script isnt working on these machines - it only detects python2 not python3. 
https://github.com/nodejs/node/blob/3b130327fa96cda42fed581df7c763acbf706a13/configure#L8-L12

`command -v python3.8` returns nothing wheres `command -v python2.7` returns the path for system python.
`command  -v python3` does return the correct path however

**Comment by mhdawson** [comment]
Sorry, missed the request to add IP's looking at it now.

**Comment by mhdawson** [comment]
Should be active now

**Comment by AshCripps** [comment]
first run through of new job https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/1/console

**Comment by mhdawson** [comment]
@AshCripps seems like the changes will affect all the Macs not just the new ones, can you confirm you've already validated they will all work ok on the old machines as well?

**Comment by AshCripps** [comment]
@mhdawson haven't tested yet will do that now. I tried to spawn a fresh instance in orka to save affecting one of the test machines but do to my current internet issues I can't load the VPN so will have to use one of the test machines.

**Comment by AshCripps** [comment]
Rebased and pushed to fix merge conflicts

**Pull request merged**
