### PR TITLE
Orka: packer macos11 intel test

### PR DESCRIPTION
**Pull request by UlisesGascon**
### Main Changes

- Add support for SSH Connection using the default credentials.
- Use a custom base image developed by us.
- Add steps for installing Homebrew and basic dependencies.

### Related

- https://github.com/nodejs/build/issues/3686#issuecomment-2278119351

### CODE REVIEW

**Comment by targos** [comment]
Didn't we agree on not migrating macOS to 11 but skipping directly to 13 instead?

**Comment by UlisesGascon** [comment]
> Didn't we agree on not migrating macOS to 11 but skipping directly to 13 instead?

We will skip MacOS 12 for sure, but we need to migrate the current Orka workload (MacOS 10.15 and MacOS 11) to the new cluster, so all the infra in Orka will be ephemeral instances controlled directly by Jenkins.

You have a recap in our last meeting ([minute 33:19](https://www.youtube.com/live/eJSzKTzSMU0?si=zESZ4Iy_wtZycCDR&t=1999))

**Comment by targos** [comment]
Ok, I won't object if you want to maintain 10.15 and 11, but I would be in favor of dropping them entirely. The build policy allows to do it for EoL platforms.

**Comment by UlisesGascon** [comment]
> Ok, I won't object if you want to maintain 10.15 and 11, but I would be in favor of dropping them entirely. The build policy allows to do it for EoL platforms.

Oh! I love the idea a lot. I was purely thinking about the migration. I didn't realize that we are "open" to dropping support. Let me create an issue for better visibility, and let's see if the team agrees on dropping support. 👍

**Comment by UlisesGascon** [comment]
As discussed in https://github.com/nodejs/build/issues/3876. I will close this PR now.

**Pull request closed without merging**
