### PR TITLE
ansible: add test-digitalocean-fedora41-x64-[12]

### PR DESCRIPTION
**Pull request by targos**
Note that I had to manually install an Ansible dependency before running the playbook because of https://github.com/ansible/ansible/issues/84206:

```
dnf install python3-libdnf5
```

### CODE REVIEW

**Comment by targos** [comment]
Test job: https://ci.nodejs.org/view/All/job/node-test-commit-linux-targos/1/nodes=fedora-next-x64/

**Comment by targos** [comment]
Build and tests passed.

**Review by richardlau — APPROVED** [review]

**Comment by richardlau** [comment]
> Note that I had to manually install an Ansible dependency before running the playbook because of [ansible/ansible#84206](https://github.com/ansible/ansible/issues/84206):
> 
> ```
> dnf install python3-libdnf5
> ```

Maybe that could be in `bootstrap`, like the selinux stuff in https://github.com/nodejs/build/blob/main/ansible/roles/bootstrap/tasks/partials/fedora.yml (you'd have to use raw commands instead of the dnf/package module)?

**Comment by targos** [comment]
> Maybe that could be in bootstrap, like the selinux stuff in [main/ansible/roles/bootstrap/tasks/partials/fedora.yml](https://github.com/nodejs/build/blob/main/ansible/roles/bootstrap/tasks/partials/fedora.yml?rgh-link-date=2024-11-19T20%3A31%3A58Z) (you'd have to use raw commands instead of the dnf/package module)?

Done. I setup https://ci.nodejs.org/computer/test-digitalocean-fedora41-x64-2/ with it.

**Comment by targos** [comment]
Test run: https://ci.nodejs.org/view/All/job/node-test-commit-linux-targos/2/nodes=fedora-next-x64/

**Review by richardlau — APPROVED** [review]

**Comment by richardlau** [comment]
FWIW today's [node-daily-v18.x-staging](https://ci.nodejs.org/job/node-daily-v18.x-staging/384/) run failed on Fedora 41:
https://ci.nodejs.org/job/node-test-commit-linux/61746/nodes=fedora-latest-x64/console
```console
10:00:40 python3 ./configure --verbose 
10:00:40 Please use python3.12 or python3.11 or python3.10 or python3.9 or python3.8 or python3.7 or python3.6.
10:00:40 Node.js configure: Found Python 3.13.0...
10:00:40 make: *** [Makefile:569: build-ci] Error 1
```

I've cherry-picked https://github.com/nodejs/node/commit/54035ac0ca8764fc6a5ebe37b7e1a8fcf3f231ce onto `v18.x-staging` and kicked off a build (which I expect to pass -- it did when I tried in a local Fedora 41 container with the cherry-pick applied): https://ci.nodejs.org/job/node-test-commit-linux/61748/nodes=fedora-latest-x64/

**Pull request merged**
