### PR TITLE
meta: add Stefan Stojanovic to test

### PR DESCRIPTION
**Pull request by joaocgreis**
I would like to add Stefan Stojanović (@StefanStojanovic) to the Build WG, giving him test level access. I can handle any task that requires higher access for now.

Stefan has been working with me on Node.js, focusing on Windows, and he has more bandwidth than I've had recently. I will help him ramp up and would we're aiming to have him increasingly help more.

He'll start by creating a small guide on how to provision a Windows machine for testing, to unblock https://github.com/nodejs/build/issues/3137 and allow other people to do it as well.

### CODE REVIEW

**Review by richardlau — APPROVED** [review]

**Comment by joaocgreis** [comment]
I remember we used to wait for 48h before moving forward with PRs, not sure if that rule is still in place, should we wait longer here?

Any objections to moving forward? @nodejs/build

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
I added him to the two teams I think that should give him access to the secrets repo.

**Comment by StefanStojanovic** [comment]
Thanks @mhdawson I have access to the secrets repo now.

**Pull request merged**
