### PR TITLE
www: redirect for calendar

### PR DESCRIPTION
**Pull request by rvagg**
@mikeal @williamkapke pls review, is this what we're after for calendar access?

### CODE REVIEW

**Comment by mikeal** [comment]
Yup.

Also, how do I get the .ics url for this?

**Comment by gibfahn** [comment]
If you follow [the link](https://calendar.google.com/calendar/embed?src=nodejs.org_nr77ama8p7d7f9ajrpnu506c98%40group.calendar.google.com) there's a `+google calendar` button.

image

If you click on the `ICS` button in the calendar settings after adding it, you get this:

https://calendar.google.com/calendar/ical/nodejs.org_nr77ama8p7d7f9ajrpnu506c98%40group.calendar.google.com/public/basic.ics

I feel like there's probably an easier way...

**Comment by rvagg** [comment]
added `$` to the regex and also added one for https://nodejs.org/calendar.ics to take you to the .ics file, is that going to be helpful?

**Comment by rvagg** [comment]
deployed, we now have those two URLs active

**Pull request merged**
