### PR TITLE
doc: improve readme with awesome image

### PR DESCRIPTION
**Pull request by jbergstroem**
I liked this image so much I wanted everybody to have a look!
Also refactored the readme because we all use w80 in our dec vt100 terminals.

Todo: perhaps get a smaller resolution image? (2mb..)

Edit: also, ask for permission/license from rod/ns (mention somewhere?)

### CODE REVIEW

**Comment by Starefossen** [comment]
Great work @jbergstroem 👏🏼 Should we try to find vector versions of the remaining logos as well?

**Comment by williamkapke** [comment]
Maybe the donation list should be brought current too

**Comment by jbergstroem** [comment]
@williamkapke I believe Rod is doing that in another PR; didn't want too put too much stuff in here.

**Comment by jbergstroem** [comment]
(ping @rvagg re licensing/image)

**Comment by phillipj** [comment]
Without a doubt very nice 👍

**Comment by jbergstroem** [comment]
> @Starefossen said:
> Great work @jbergstroem 👏🏼 Should we try to find vector versions of the remaining logos as well?

Feel free!

**Comment by jasnell** [comment]
Please make sure you add a small attribution note to the picture along with the licensing.
(@rvagg, if I may suggest, [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/)?)

**Comment by jbergstroem** [comment]
@jasnell yeah, waiting for feedback.

**Comment by Starefossen** [comment]
**ARM (SVG)**

ARM

**Joyent (SVG black)**

Joyent

**Microsoft (SVG)**

Microsoft

**Scaleway (SVG logo only)**

[https://cloud.scaleway.com/images/c16347e9.logo.svg](https://cloud.scaleway.com/images/c16347e9.logo.svg) 

**Voxer (EPS)**

http://voxer.com/images/voxer_walkie_variants.eps

**Comment by jbergstroem** [comment]
@Starefossen perhaps open a PR once you have them that replaces the current?

**Comment by Starefossen** [comment]
Yeah, sure thing, Johan 😄

**Comment by rvagg** [comment]
sure, let's go with attribution using by-sa/au https://creativecommons.org/licenses/by-sa/3.0/au/deed.en

lgtm but hopefully people won't get the impression that _is_ our cluster!

**Pull request merged**
