### PR TITLE
ansible: add loongson-clfs-loongarch64-1

### PR DESCRIPTION
**Pull request by shipujin**
ansible: add loongson-clfs-loongarch64-1

Refs: https://github.com/nodejs/build/issues/3540

### CODE REVIEW

**Comment by shipujin** [comment]
Submit the LoongArch machine CI node patch. If need to add LoongArch content to other files, please tell me and I will resubmit the patch. Thank you very much.

Best regards

**Comment by mhdawson** [comment]
It's going to need more than that. The PR in the current form simply adds the machine to the inventory, I believe if you then tried to run the script on the machine it would fail since it does not know what the Operating system is.

**Comment by shipujin** [comment]
> It's going to need more than that. The PR in the current form simply adds the machine to the inventory, I believe if you then tried to run the script on the machine it would fail since it does not know what the Operating system is.

Yes, thank you for your help.
I submitted a pr for the "clfs.yml" file and I will run the script on the machine to test it

Best regards

**Comment by shipujin** [comment]
Because the network IP has changed, the patch is no longer applicable.

Best regards

**Pull request closed without merging**
