### PR TITLE
ansible: fix problem with resolving localhost on zos

### PR DESCRIPTION
**Pull request by miladfarca**

### CODE REVIEW

**Comment by sam-github** [comment]
@miladfarca Do you need these changes made to any hosts, or did you make and test the changes already?

**Comment by miladfarca** [comment]
@sam-github these have been manually added to our zos boxes some time ago, just adding to ansible for the future. We also need to have this export on Jenkins when running the job, its' already added on Jenkins:
```
export RESOLVER_CONFIG=/u/iojs/resolver
```

**Comment by sam-github** [comment]
OK, we'll give it a couple days in case anyone has a comment, then I'll merge. Thanks. ps. Remind me if I forget about it :-)

**Comment by sam-github** [comment]
@miladfarca Can you land or do you need me to?

**Comment by miladfarca** [comment]
@sam-github  I don't have write access on this repository, could you merge for me

**Comment by sam-github** [comment]
Landed in 395cd28e41716739efc0c3db5b55f6a3c8250ed7

**Pull request merged**
