### PR TITLE
github-bot: redirect stdout to file

### PR DESCRIPTION
**Pull request by phillipj**
Fixes an issue we have currently, where all current logs are deleted whenever the bot is redeployed because of two things:

1. We have the github-bot repo cloned and write logs to a sub-directory of repo root (`logs`)
2. Upon deploy `git clean -fdx` deletes any untracked files in the repo

Simply writing out bunyan logs to stdout would also simplify our current log related code in the bot.

Is `logrotate` the way to go for rotating this?

### CODE REVIEW

**Comment by phillipj** [comment]
Refs https://github.com/nodejs/github-bot/issues/88#issuecomment-262628736

**Comment by jbergstroem** [comment]
Wouldn't stdout be collected by systemd (when deployed on debian8, ubuntu, etc) which is already managed by logctl?

**Comment by phillipj** [comment]
I'm all ears to better / simpler ways. I'd say it's important to be able to
expose this log over HTTP like we currently have. Using bunyan to filter
and trace logs as been really valuable so far.

**Comment by jbergstroem** [comment]
I'm personally not a "log over http" guy (grep, awk, tail, ..) but if has been a big part of the teams debugging lets opt for that then.

If you're going that route, look at systemd's `StandardOutput=` directive and pass that to file. Another alternative could be using console+syslog and use the system logger (with an identifier) to control output. That way, the system logger could probably handle rotating as well.

**Comment by jbergstroem** [comment]
By the way, does stdout follow the same format bunyan expects?

**Comment by phillipj** [comment]
> By the way, does stdout follow the same format bunyan expects?

Yepp. Everything we log is through bunyan, which writes both to stdout and a log file ATM. When running locally via `npm start` the stdout output gets prettified for easier reading tho. That's not the case on the server, as the systemd service executes the server script directly.

**Comment by phillipj** [comment]
On second thought, doing this seemed more complex than simply writing logs outside the directory where the github-bot repo is cloned into.

Refs https://github.com/nodejs/build/pull/602

**Comment by phillipj** [comment]
Closing this in favor of #602

**Pull request closed without merging**
