### PR TITLE
node-test-commit matrix document

### PR DESCRIPTION
**Pull request by rvagg**
I was writing up some basic notes on our standard CI matrix and figured it might make a good doc for our repo even though it's not likely to stay updated (hence the caveats at the top).

It's highlighted a couple of things already:

1. node-test-commit-custom-suites-freestyle is really far too complex for what it contributes to node-test-commit and could be easily refactored out into the containered jobs (from what I can tell) https://github.com/nodejs/build/issues/1864
2. The debian9-docker-armv7 label was missing from node-test-commit-linux-arm, it should have been there since Node 12 but I guess this was my oversight. I've added it and am testing it out https://ci.nodejs.org/job/node-test-commit-arm/25379/nodes=debian9-docker-armv7/console
3. The containered jobs config could be refactored into a script in this repo. As the list of them as grown, the copypasta has increased, there's a standard set of things that need to be executed for each of them and they could be put into a single script, or at least a collection of scripts which would make it easier to diagnose problems like the recent one that was highlighted where debug builds aren't running the full compliment of tests.

@joaocgreis the Windows matrix doesn't seem to be using VersionSelectorScript.groovy, I've tried my best to reproduce what I think the rules are but a sanity check from you would be appreciated.

### CODE REVIEW

**Comment by rvagg** [comment]
Need some Windows sanity check before I can merge this I think.

**Comment by joaocgreis** [comment]
@rvagg pushed a fixup with some adjustments, feel free to adjust as you see fit.

Windows doesn't use the VersionSelectorScript because of two issues (at least):
- Would have to separate what can build and what should be used to build the official releases. For example, for Node 8, we want to use both VS2015 and VS2017 to build in CI and we have those two versions as well in the release Jenkins ([where VS2015 should be used](https://github.com/nodejs/build/blob/master/doc/windows-visualstudio-supported-versions.md#official-releases)).
- We support running (including building addons) in more versions than we support compiling core, and we want to test those in CI.

Separating the test jobs in CI as we have now for Node >= 11 is not a bad way of organizing it. So, even though VersionSelectorScript would probably be a better way I don't think adapting it is urgent at the moment.

**Comment by rvagg** [comment]
thanks @joaocgreis, just having the windows matrix outlined like this is helpful

**Comment by rvagg** [comment]
merged

**Pull request closed without merging**
