### PR TITLE
ansible: move `roles` and `plugins` under `playbooks`

### PR DESCRIPTION
**Pull request by AshCripps**
Wanted to float this here, basically if we want to expand AWX to be able to use our regular playbooks we need to move `role` to `playbooks`. This is because AWX runs from the root directory therefore doesnt pick up our `ansible.cfg` and cant find the roles, by moving roles under playbooks this allows for AWX to run the playbooks (currently need to find a solution for secrets) without impacting our usual workflow of running from within the `ansible` directory. So this should **not** make any difference to us running the playbooks manually.

thoughts?

### CODE REVIEW

**Comment by rvagg** [comment]
no major objection from me .. are we anticipating wanting to use AWX? does it value-add for us? I haven't been following news about it

**Comment by AshCripps** [comment]
ATM im currently focusing on getting it working for the `build-helper` stuff but I think there is so value add from getting the regular playbooks working  with a big plus being able to have the playbooks run regularly so we can check for any faults and help prevent so much technical debt accumulating. (it seems that everytime we update machines we have to fix something different in the playbook).

This is all pipeline stuff - still have to get secrets working on the machine anyway but I wanted to open this to see if people were strongly opposed before I got too far into it.

**Comment by mhdawson** [comment]
No objections from me. @jbergstroem any concerns from you since you set up the current structure?

**Review by jbergstroem — APPROVED** [review]
All good from my side

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by richardlau — APPROVED** [review]
LGTM. @AshCripps have you run the playbooks from the refactored layout against any of the CI hosts?

**Comment by AshCripps** [comment]
> LGTM. @AshCripps have you run the playbooks from the refactored layout against any of the CI hosts?

I did with `check` mode on but cant remember if I completed a run through let me do that now

**Comment by AshCripps** [comment]
ive updated this pr to fixup conflicts and to move `plugins` under `playbooks` to fix AWX in `restart-agent.yml`

**Review by mhdawson — APPROVED** [review]
Still LGTM

**Comment by AshCripps** [comment]
closing in favour https://github.com/nodejs/build/pull/2767

**Pull request closed without merging**
