### PR TITLE
doc: add minutes for build WG meeting 2016-06-28

### PR DESCRIPTION
**Pull request by mhdawson**

### CODE REVIEW

**Comment by mhdawson** [comment]
@nodejs/build

**Comment by TheAlphaNerd** [comment]
LGTM

**Comment by joaocgreis** [comment]
Some problem with my name in the 3 places it is used (encoding?)

Everything else LGTM

**Comment by mhdawson** [comment]
Ok cut/paste Joao's name from previous minutes and landing

**Comment by mhdawson** [comment]
Landed as aaead264814230900e443f6ac11fd3d95e9bbac3

**Pull request closed without merging**
