### PR TITLE
www: enable fallback for French, Catalan, and Galitian locales

### PR DESCRIPTION
**Pull request by lpinca**
This enables English fallback for files not translated to French, Catalan, and Galitian.

Refs: https://github.com/nodejs/nodejs.org/issues/1318

### CODE REVIEW

**Comment by jevtovich** [comment]
ca, gl need to be added as well

**Comment by lpinca** [comment]
Nice catch, will update shortly.

**Comment by gibfahn** [comment]
This seems fine, but it'd be great to update the new [`ansible/`](https://github.com/nodejs/build/tree/master/ansible) scripts too, IDK if an equivalent for this exists there yet (cc/ @jbergstroem ).

**Comment by rvagg** [comment]
:+1: deployed, please test and confirm

**Comment by jevtovich** [comment]
Tested, everything working fine.

**Pull request merged**
