### PR TITLE
ansible: upgrade test-digitalocean-fedora32-x64-1

### PR DESCRIPTION
**Pull request by targos**
Replaced with test-digitalocean-fedora39-x64-1

Refs: https://github.com/nodejs/build/issues/3350

### CODE REVIEW

**Comment by targos** [comment]
Note that after recreating the droplet, DNS resolution was broken. I had to do the following to fix it and be able to run the playbook:

```
`vi /etc/systemd/resolved.conf` with:

DNS=1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com 2606:4700:4700::1111#cloudflare-dns.com 2606:4700:4700::1001#cloudflare-dns.com

`systemctl restart systemd-resolved`
```

**Comment by targos** [comment]
First host with this Fedora version, so let's do a test run before adding it to regular CI: https://ci.nodejs.org/view/All/job/node-test-commit-linux-targos-fedora39/1/

**Comment by richardlau** [comment]
> Note that after recreating the droplet, DNS resolution was broken. I had to do the following to fix it and be able to run the playbook:
> 
> `vi /etc/systemd/resolved.conf` with:
> 
> DNS=1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com 2606:4700:4700::1111#cloudflare-dns.com 2606:4700:4700::1001#cloudflare-dns.com
> 
> `systemctl restart systemd-resolved`

We've hit that before with DO droplets: https://github.com/nodejs/build/pull/2745#issuecomment-911842863

**Review by richardlau — APPROVED** [review]
LGTM (subject to the CI run not uncovering any further issues)

**Comment by targos** [comment]
CI passed.

**Comment by richardlau** [comment]
@targos FYI https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/56783/console just failed on the machine (Node.js 18):
```console
17:55:46 python3 ./configure --verbose 
17:55:46 Please use python3.11 or python3.10 or python3.9 or python3.8 or python3.7 or python3.6.
17:55:46 Node.js configure: Found Python 3.12.2...
17:55:46 make: *** [Makefile:569: build-ci] Error 1
17:55:46 Build step 'Execute shell' marked build as failure
```
We haven't backported the Python 3.12 compatibility patches to Node.js 18 -- I did look at those earlier this week but considered them risky for inclusion in 18.20.0.

**Comment by richardlau** [comment]
I'm running a test to see if we can just cherry-pick https://github.com/nodejs/node/pull/50209 to Node.js 18 for now without the gyp-next changes from https://github.com/nodejs/node/pull/50380. It looks like Python 3.12 on `test-digitalocean-fedora39-x64-1` does still include/support `distutils.version`.

https://ci.nodejs.org/job/node-test-commit-linux/56785/nodes=fedora-latest-x64/

**Comment by targos** [comment]
Run looks good!

**Pull request merged**
