### PR TITLE
Update CentOS6 support, add support for release nodes

### PR DESCRIPTION
**Pull request by rvagg**
ref https://github.com/nodejs/build/issues/718

Also added these 2 release machines to ci-release and gave them a label `post-8-release` and added the following to the iojs+release scripting:

```bash
if [[ \
  $OSTYPE =~ linux && \
  $ARCH =~ x86_64|x64|i386|x86|ia32 && \
  ( \
    ( ${NODE_VERSION:0:1} -gt "7" && ! $NODE_LABELS =~ post-8-release ) || \
    ( ${NODE_VERSION:0:1} -lt "7" && $NODE_LABELS =~ post-8-release ) \
  ) \
]]; then
  echo "Not building Node.js ${NODE_VERSION:0:1} on $NODE_NAME"
  exit 0
fi
```

### CODE REVIEW

**Comment by rvagg** [comment]
sorry @mhdawson, didn't know we were onto a local `ansible` branch, can you point me to discussion or PR or something about that? I was still tracking jbergstroem/feature/refactor-the-world which is a bit out of date so I haven't used it.

**Comment by rvagg** [comment]
oh, it's not a branch, it's a whole directory! ok .. will look into that

**Comment by mhdawson** [comment]
@rvagg its still a work in progress.  We agreed at the vm summit in Berlin (with @jbergstroem via remote) to land the refactor and the move platform by platform over to it as we had time to validate.

**Comment by rvagg** [comment]
OK, that's great! I might ammend this PR to include the new work, that should give me a chance to have some proper hands-on experience with it.

**Pull request merged**
