### PR TITLE
doc: add gireeshpunathil to members

### PR DESCRIPTION
**Pull request by gireeshpunathil**
often, I work to debug test failures in CI. And in many cases the issues are reproducible only in CI systems in which case I would request for temporary access.

Having part of the team will help
 - not waiting for long time before access is granted
 - stabilizing CI on a timely basis.

Thanks in advance.

### CODE REVIEW

**Comment by rvagg** [comment]
Anyone know what our process is these days? Can we just merge this, add to the GitHub team and add a GPG key (which you'll need to provide @gireeshpunathil btw) to secrets/build/test?

**Comment by joaocgreis** [comment]
We usually do a onboarding session where we go over https://github.com/nodejs/build/blob/master/ONBOARDING.md, focusing on the responsibility that membership implies and discussing with more detail the areas that the new member knows less or is more interested in.

I can do the onboarding, or if @mhdawson or @gdams want to have a more direct chat (IIUC you work for IBM, don't know how close) that would work as well.

We usually add the keys during the onboarding, but I don't see any issue with adding @gireeshpunathil sooner since he already has experience connecting to machines.

**Comment by mhdawson** [comment]
@joaocgreis  either of myself or @gdams could do the onboarding, but you might give better coverage of the windows side.  Just let us know which you would prefer.

**Comment by joaocgreis** [comment]
I will onboard Gireesh on Wednesday.

**Comment by gibfahn** [comment]
@joaocgreis my ability to do that is based on Admin permissions from being a member of the moderation team (I think), so probably best for me not to do it...

**Comment by joaocgreis** [comment]
We had to change plans, the onboarding will happen this Friday.

Adding to https://github.com/orgs/nodejs-private/teams/build/members is part of the onboarding preparation procedure from https://github.com/nodejs/build/blob/master/ONBOARDING.md. It would be good if a team maintainer could add @gireeshpunathil before the onboarding session, so that we could set up and test secrets access.

**Comment by mhdawson** [comment]
I've invited @gireeshpunathil to  https://github.com/orgs/nodejs-private/teams/build/members as requested.

**Comment by joaocgreis** [comment]
We just did the onboarding, welcome @gireeshpunathil! Feel free to land this PR now, you should have all the necessary access, let me know if there is any issue.

**Pull request merged**
