### PR TITLE
ansible: add cmake to macos

### PR DESCRIPTION
**Pull request by AshCripps**
refs: https://github.com/nodejs/build/issues/2175

So far ive only added it to 10.15 as older macs can build libuv on gyp whereas 10.15 can't at this time.

Tested on test-nearform-macos10.15-x64-3 and its working

```
administrator@test-nearform-macos10 ~ % cmake -version
cmake version 3.16.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).
administrator@test-nearform-macos10 ~ %
```

### CODE REVIEW

**Comment by richardlau** [comment]
Test libuv build: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-osx-cmake/nodes=osx1015/

**Comment by richardlau** [comment]
The other issue requesting cmake was for CITGM (https://github.com/nodejs/build/issues/2097) but I can't remember if we're running CITGM on macOS 10.15,

**Comment by AshCripps** [comment]
@richardlau im sure I added it too CITGM let me check

**Comment by richardlau** [comment]
I think the npm that used cmake was zeromq. It might be skipped in CITGM's lookup.json but we should be able to run CITGM and change the default CITGM command parameter from `citgm-all` to `citgm zeromq`.

**Comment by AshCripps** [comment]
the only issue is, is it safe to reansible the old macs to add cmake onto them? They are quite old and I have no idea when they were last ansibled.

**Comment by richardlau** [comment]
> 
> 
> the only issue is, is it safe to reansible the old macs to add cmake onto them? They are quite old and I have no idea when they were last ansibled.

¯\\_(ツ)\_/¯

**Comment by sam-github** [comment]
I don't know, either.

Maybe just brew install cmake?

**Comment by AshCripps** [comment]
Ive updated to add cmake to all mac lines and if there are no objections, when I merge this and run the ansible playbooks ill manually install cmake on the older macs.

Do the release machines need cmake or is it just test at this point?

**Comment by richardlau** [comment]
> 
> 
> Ive updated to add cmake to all mac lines and if there are no objections, when I merge this and run the ansible playbooks ill manually install cmake on the older macs.
> 
> Do the release machines need cmake or is it just test at this point?

At this point just test AFAIK.

**Comment by richardlau** [comment]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/742/nodes=osx1015/console

```
12:08:08 warn: zeromq npm-install: | /Users/iojs/tmp/citgm_tmp/eead1d20-4f5f-4b11-930d-0cfb27981a6b/zeromq/build/Release/../../script/build.sh: line 60: cmake: command not found
12:08:08 warn: zeromq npm-install: | make: *** [libzmq/lib] Error 127
```

**Comment by AshCripps** [comment]
@richardlau that'll be because ive only installed it on `-3` and that citgm ran on `-1`

**Comment by AshCripps** [comment]
installed on all 10.15 machines https://ci.nodejs.org/job/citgm-smoker-nobuild/743/nodes=osx1015/console looks like it found cmake.

**Comment by AshCripps** [comment]
Ive manually installed cmake on all old macstadium test machines

**Pull request merged**
