### PR TITLE
ansible: update Node.js from 12.x -> 14.x

### PR DESCRIPTION
**Pull request by aduh95**
Fixes: https://github.com/nodejs/build/issues/2504

/cc @richardlau

### CODE REVIEW

**Review by AshCripps — APPROVED** [review]

**Comment by richardlau** [comment]
I've run this against `test-packetnet-ubuntu1804-x64-1` but unfortunately while it has added the Node.js 14 repo from Node Source it hasn't actually updated the installed Node.js to 14.x. It did update to 12.20.1 so I'm presuming it's because different repositories are involved.

**Comment by richardlau** [comment]
Pushed a commit to do the equivalent of `apt-get update` before installing the `nodejs` package.

The `jenkins-workspace` role is currently given to the following hosts that will need updating:
    - [x] test-packetnet-ubuntu1804-x64-1
    - [ ] test-packetnet-ubuntu1804-x64-2
    - [ ] test-ibm-ubuntu1804-x64-1

**Comment by richardlau** [comment]
Test build https://ci.nodejs.org/job/node-test-linter/38634/ (rebuild of https://ci.nodejs.org/job/node-test-linter/38339) appears to have passed.

**Review by richardlau — APPROVED** [review]

**Comment by rvagg** [comment]
did it remove the 12.x repo whle it was there? my guess is that just changing that line is going to _add_ the new one but not do anything with the old. I'm not sure there's a good way of handling that without doing it manually or adding the 14.x as a new task and setting the 12.x one as `absent`.

**Comment by richardlau** [comment]
No it did not. I'll add another task to manually remove the 12.x one.

**Pull request merged**
