### PR TITLE
update armv7-wheezy config

### PR DESCRIPTION
**Pull request by rvagg**

### CODE REVIEW

**Comment by rvagg** [comment]
2 new machines

https://ci.nodejs.org/computer/nodejs-scaleway-armv7-wheezy-1/
https://ci.nodejs.org/computer/nodejs-scaleway-armv7-wheezy-2/

taking offline

https://ci.nodejs.org/computer/iojs-online_net-armv7-wheezy-1/
https://ci.nodejs.org/computer/iojs-online_net-armv7-wheezy-2/

**Comment by joaocgreis** [comment]
Thanks for adding monit! I'm doing the ansible for the cross compiling machine, already included it. I changed it to be a little more generic by using the server_user variable, you can include it if you want. The file `resources/monit-jenkins.conf` became:
```
check process jenkins
  matching slave.jar
  start program = "/bin/su {{server_user}} -c 'cd /home/{{server_user}} && /home/{{server_user}}/start.sh'"
  stop program = "/bin/su {{server_user}} -c 'pkill jenkins'"
```
And added this after the `Copy monit config` in the playbook:
```
    - name: Monit | Copy server user name to monit config
      replace: dest=/etc/monit/conf.d/jenkins regexp="\{\{server_user\}\}" replace="{{ server_user }}"
      tags: monit
```

I did not test run your changes here, but the text LGTM.

**Comment by rvagg** [comment]
@joaocgreis we should put that into ansible-tasks/monit.yaml cause it's used in a few places now, do you want to do that?

**Comment by joaocgreis** [comment]
@rvagg Sounds good, I'll do it.

**Comment by jbergstroem** [comment]
Config probably needs to live elsewhere though since some machines are into init scripts. Also, newer upstarts and systemd afaik handles restarting/keepalive for you.

**Pull request closed without merging**
