### PR TITLE
switch ppcle to use newer java8 version

### PR DESCRIPTION
**Pull request by gdams**
This fixes one of the issues that @maclover7 mentioned on the build WG call.

### CODE REVIEW

**Comment by maclover7** [comment]
@gdams Can you run the playbook on all of the PPC machines, after that will land

**Comment by maclover7** [comment]
@gdams Can you add the following diff to this PR? With both changes, this gets the PPC machines running on the newer version, and then this can land.

```diff
diff --git a/ansible/roles/jenkins-worker/templates/upstart.j2 b/ansible/roles/jenkins-worker/templates/upstart.j2
index ebb9d91..2415852 100644
--- a/ansible/roles/jenkins-worker/templates/upstart.j2
+++ b/ansible/roles/jenkins-worker/templates/upstart.j2
@@ -25,7 +25,7 @@ setuid iojs
 script
 
   if [ $(uname -i) = "ppc64le" ]; then
-    export PATH=/home/iojs/jdk8u144-b01/bin:$PATH;
+    export PATH=/home/iojs/jdk8u172-b11/bin:$PATH;
   fi
 
   exec java -Xmx{{ server_ram|default('128m') }} \
```

**Comment by mhdawson** [comment]
@maclover7 good catch, original would potentially have broken the machines.  One reason why I always want good testing/rollout to minimize chances of breaking our infra.

**Comment by maclover7** [comment]
ping @gdams, would like for this to land soon if possible to unblock other work

**Comment by gdams** [comment]
@maclover7 applied the diff

**Comment by maclover7** [comment]
Landed in 3bd1032

**Pull request merged**
