### PR TITLE
build: on push GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
Use GitHub Actions to lint Python code with flake8 on both Python 2 and Python 3.

### CODE REVIEW

**Comment by sam-github** [comment]
gh actions are the new hotness, it seems, but I don't know that yet a third ci system added to jenkins and travis is really supportable, but we can leave that decision for a bit. I'm sure it will come up.

In the meantime, RSLGTM too .

**Comment by rvagg** [comment]
👍 from me, we're not using travis here so we're not doubling up. The more we exercise GitHub Actions to understand its limitation the better.

**Comment by rvagg** [comment]
this is failing https://github.com/nodejs/build/commit/303e626f9d550c70606d95e3cae6ba8287d93793/checks
But I see now that the commit has an additional comment that it's blocked by #1929 (this didn't show up in the PR btw @cclauss, just in the commit summary). If this is the case I suppose we can just wait for to land, presumably soon?

**Comment by rvagg** [comment]
nope, #1929 already landed, so the failure is unexpected then. failed on pip upgrade pip:

```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by cclauss** [comment]
Runtime issues resolved in #1934

**Pull request merged**
