### PR TITLE
[WIP] win: add a "VS2017 Build Tools" playbook

### PR DESCRIPTION
**Pull request by refack**
A new playbook to set-up "VS2017 Build Tools".

### CODE REVIEW

**Comment by refack** [comment]
I'm still playing with the command line parameter so it'll wait for the install to finish

**Comment by joaocgreis** [comment]
> I'm still playing with the command line parameter so it'll wait for the install to finish

@refack thanks for this! Let us know when it's time to review.

**Comment by piccoloaiutante** [comment]
@refack looking forward to test it locally on my machine :)

**Comment by BridgeAR** [comment]
This should likely be closed. There was no progress for one year now.

**Comment by joaocgreis** [comment]
Superseded by https://github.com/nodejs/build/pull/1383. @refack I hope you don't mind me closing this, thanks for your work!

**Pull request closed without merging**
