### PR TITLE
ansible: add new AIX 7.2 machines from IBM

### PR DESCRIPTION
**Pull request by richardlau**
Adding some new AIX 7.2 VMs hosted in IBM Cloud.

https://ci.nodejs.org/computer/test-ibm-aix72-ppc64_be-1/ has been set up with these changes.
WIP while adding the remaining hosts and testing.

### CODE REVIEW

**Comment by richardlau** [comment]
Test build: https://ci.nodejs.org/job/node-test-commit-aix/45070/ on [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/computer/test-ibm-aix72-ppc64_be-1/).

**Comment by richardlau** [comment]
> Test build: https://ci.nodejs.org/job/node-test-commit-aix/45070/ on [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/computer/test-ibm-aix72-ppc64_be-1/).

I've opened https://github.com/nodejs/node/issues/46792 for the test failure -- it's a follow on to an older issue with the same test (https://github.com/nodejs/node/issues/39143) that was fixed but the test now fails in a different manner. It's masked on the other AIX machines in the CI as we had disabled the IPv6 network interfaces for the older issue.

Also noticed that the test build ran with gcc 10 instead of 8 (despite select-compiler.sh claiming otherwise). It looks like the `gcc-c++` package now installs gcc 10. I'll update the selecect-compiler.sh script and the Ansible playbook accordingly, also taking into account https://community.ibm.com/community/user/power/blogs/sangamesh-mallayya1/2020/12/17/aix-gcc-multi-version-support-improvements.

**Comment by richardlau** [comment]
Pulled out the GitHub known_hosts keys into https://github.com/nodejs/build/pull/3212 as that is not AIX-specific and this PR needs more work.

**Comment by richardlau** [comment]
This is now ready for review. I will need to coordinate landing with running the playbook against the AIX VMs -- running the playbook will be necessary to get gcc 8 and 10 onto the AIX 7.2 VMs and landing will be required to update select-compiler.sh so the correct compiler is selected for the Node.js version being built.

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
