### PR TITLE
[to be unfozen on 2019-40-18] remove linux ppc64be support

### PR DESCRIPTION
**Pull request by refack**
as per nodejs/node#12309

Please tell me if I'm missing something

### CODE REVIEW

**Comment by gibfahn** [comment]
@refack I don't think we'd want to land this until Node 6 goes out of support, but quick work!

**Comment by refack** [comment]
> but quick work!

Did it mostly as an exercise

**Comment by jbergstroem** [comment]
@refack out of curiosity; did you test the ansible playbook somehow? It's currently pretty tricky; having virtualization/vagrant handy might make it easier.

**Comment by refack** [comment]
> @refack out of curiosity; did you test the ansible playbook somehow? It's currently pretty tricky; having virtualization/vagrant handy might make it easier.

WIP

**Comment by mhdawson** [comment]
Yes we can't remove the BE machines for quite a while yet.

**Comment by jbergstroem** [comment]
Seeing how we're three years away, how about we just close it?

**Comment by gibfahn** [comment]
Closing, we can always reopen when it's time 😃

**Pull request closed without merging**
