### PR TITLE
ansible: rebuild fedora37-x64-1 with Fedora 40

### PR DESCRIPTION
**Pull request by targos**
Fedora 37 is EoL.

https://ci.nodejs.org/computer/test%2Ddigitalocean%2Dfedora40%2Dx64%2D1/

### CODE REVIEW

**Comment by targos** [comment]
Similar to https://github.com/nodejs/build/pull/3660, DNS resolution didn't work by default so I did the following:
``
mkdir /etc/systemd/resolved.conf.d
vi /etc/systemd/resolved.conf.d/cloudflare.conf
```

With 
```
[Resolve]
DNS=1.1.1.1#1dot1dot1dot1.cloudflare-dns.com 1.0.0.1#1dot1dot1dot1.cloudflare-dns.com 2606:4700:4700::1111#1dot1dot1dot1.cloudflare-dns.com 2606:4700:4700::1001#1dot1dot1dot1.cloudflare-dns.com
DNSSEC=yes
DNSOverTLS=yes
```

**Comment by targos** [comment]
It's still not really working, even after a reboot.

`dnf upgrade` is able to get metadata but then it fails to download the packages:

```
# dnf upgrade
Fedora 40 - x86_64 - Updates                                                                                          222 kB/s |  29 kB     00:00
Fedora 40 - x86_64 - Updates                                                                                          6.9 MB/s | 5.4 MB     00:00
Last metadata expiration check: 0:00:03 ago on Sun 14 Jul 2024 09:42:45 AM UTC.
Dependencies resolved.
======================================================================================================================================================
 Package                                         Architecture            Version                                       Repository                Size
======================================================================================================================================================
Installing:
 kernel-core                                     x86_64                  6.9.8-200.fc40                                updates                   17 M
...
many more lines
...
Transaction Summary
======================================================================================================================================================
Install    3 Packages
Upgrade  170 Packages

Total download size: 144 M
Is this ok [y/N]: y
Downloading Packages:
[MIRROR] dhcpcd-10.0.6-4.fc40.x86_64.rpm: Curl error (6): Couldn't resolve host name for http://mirror.siena.edu/fedora/linux/releases/40/Everything/x86_64/os/Packages/d/dhcpcd-10.0.6-4.fc40.x86_64.rpm [Could not resolve host: mirror.siena.edu]
[MIRROR] dhcpcd-10.0.6-4.fc40.x86_64.rpm: Curl error (6): Couldn't resolve host name for https://nnenix.mm.fcix.net/fedora/linux/releases/40/Everything/x86_64/os/Packages/d/dhcpcd-10.0.6-4.fc40.x86_64.rpm [Could not resolve host: nnenix.mm.fcix.net]
...
many more lines
...
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  kernel-core-6.9.8-200.fc40.x86_64: Cannot download, all mirrors were already tried without success
```

**Comment by targos** [comment]
Feel free to take over. I'll be mostly unavailable next week.

**Comment by targos** [comment]
Well I tried again and this time, while it still printed many "Couldn't resolve host name" errors, it ended up working.

**Comment by targos** [comment]
Test run: https://ci.nodejs.org/job/node-test-commit-linux-targos/nodes=fedora-latest-x64-test/3/console

```
12:22:25 + curl -sLO https://raw.githubusercontent.com/targos/nodejs-build/gcc-11-debian-12/jenkins/scripts/select-compiler.sh
12:22:25 + . ./select-compiler.sh
12:22:25 ++ 404: Not Found
12:22:25 ./select-compiler.sh: line 1: 404:: command not found
12:22:26 Build step 'Execute shell' marked build as failure
```

**Comment by targos** [comment]
Test run: https://ci.nodejs.org/view/All/job/node-test-commit-linux-targos/4/nodes=fedora-latest-x64-test/console

**Comment by targos** [comment]
It's green!

**Review by richardlau — APPROVED** [review]

**Pull request merged**
