### PR TITLE
ci: Skip centOS6 for node >= 12

### PR DESCRIPTION
**Pull request by refack**
Refs: https://github.com/nodejs/build/issues/1583

### CODE REVIEW

**Comment by refack** [comment]
Since the plan is to build node12 on CentOS7, skip CentOS6 testing at all for node >= 12, essentially downgrading support level to "experimental".
EOL will be Nov 2020, but meanwhile it's just a slow test (~30m).

**Comment by refack** [comment]
Oops. Jumped the gun there.
Reverted.

**Comment by refack** [comment]
Pending https://github.com/nodejs/node/pull/26714

**Comment by refack** [comment]
Relanded in 67bee155f578f3fda0efb2566e560a7689a671d6
CentOS6 has EOL Python2.6 and is incompatible with code changes for node 12.

**Comment by rvagg** [comment]
we forgot that this impacts ci-release as well and broke nightlies #1764

**Comment by refack** [comment]
Ack.

**Pull request merged**
