### PR TITLE
chore: Update nodejs.org webhook branch

### PR DESCRIPTION
**Pull request by nschonni**
To support rename of default branch from master -> main

### CODE REVIEW

**Comment by nschonni** [comment]
Just flipped this to draft till the actual branch rename happens in the other repo

**Comment by richardlau** [comment]
@nschonni Would you mind updating the reference to nodejs.org's `origin/master` at https://github.com/nodejs/build/blob/61b074e950a04fc6587cacb614e2fbf032bdf204/ansible/www-standalone/resources/scripts/build-site.sh#L35 as part of this PR as well?

I believe that and the reference you've already updated here are the places we need to update to keep the website build pipeline working after the default branch rename. We'd need to manually deploy the change and restart the webhook but I can take care of that.

**Comment by nschonni** [comment]
@richardlau done!

**Review by richardlau — APPROVED** [review]

**Review by AshCripps — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
@richardlau deployed to website and I've rename the branch

**Pull request merged**
