### PR TITLE
ansible: add Debian 10

### PR DESCRIPTION
**Pull request by richardlau**
Replace `test-softlayer-debian8-x86-1` with a Debian 10 based image.
`openjdk-8-jre-headless` is no longer available from the Debian 10
repositories, so replace with `openjdk-11-jre-headless`.

Refs: https://lists.debian.org/debian-java/2019/04/msg00036.html
Refs: https://github.com/nodejs/build/issues/2600

### CODE REVIEW

**Comment by richardlau** [comment]
Changes have been run against [test-softlayer-debian10-x64-1](https://ci.nodejs.org/computer/test-softlayer-debian10-x64-1/) (which is the old `test-softlayer-debian8-x86-1` but reimaged ("Load selected image") with "Debian GNU/Linux 10.x Buster/Stable - Minimal Install (64 bit)" through the IBM Cloud interface).

Test build in progress: https://ci.nodejs.org/job/node-test-commit-linux-richardlau/4/nodes=debian10-x64/
(am not intending to update the main `node-test-commit-linux` job until we have a second debian 10 host.)

**Comment by richardlau** [comment]
We are mostly running Java 8 elsewhere... if desired I can try getting Java 8 from the adoptopenjdk project instead of pulling from Debian repositories.

**Comment by richardlau** [comment]
Test build and second test build (https://ci.nodejs.org/job/node-test-commit-linux-richardlau/5/) failed lots of tests with "key too small" errors. I think this is related to https://github.com/nodejs/node/issues/27862.

**Comment by richardlau** [comment]
Added a commit to drop the OpenSSL security level back to the OpenSSL default of `1` (Debian increased it to `2` but that breaks over a hundred Node.js tests). Longer term we should look to resolve https://github.com/nodejs/node/issues/27862 but this will get us going.

Test build: https://ci.nodejs.org/job/node-test-commit-linux-richardlau/7/nodes=debian10-x64/
is now down to a single failure, `parallel/test-zlib-unused-weak`, which is failing on other platforms and may be fixed by https://github.com/nodejs/node/pull/38149.

**Comment by richardlau** [comment]
A test build of https://github.com/nodejs/node/pull/38149 passed (🎉): https://ci.nodejs.org/job/node-test-commit-linux-richardlau/8/nodes=debian10-x64/

**Comment by richardlau** [comment]
I've reimaged `test-rackspace-debian8-x64-2` as [test-rackspace-debian10-x64-1](https://ci.nodejs.org/computer/test-rackspace-debian10-x64-1/) and run the scripts in this PR against it.
Test build: https://ci.nodejs.org/job/node-test-commit-linux-richardlau/9/nodes=debian10-x64/

**Comment by richardlau** [comment]
Added VersionSelectorScript changes. This is ready for review.

**Review by AshCripps — APPROVED** [review]

**Pull request merged**
