### PR TITLE
doc: add richardlau to members

### PR DESCRIPTION
**Pull request by richardlau**
People tend to [assume](https://github.com/nodejs/build/issues/2005#issuecomment-546570070) I'm already a member of this WG so let's make it official 😄.

For the record, I work for IBM and have been working on Node.js ever since we started porting to ppcbe Linux back in 2013. To set expectations, I have more experience in the Jenkins job configuration side of things compared to machine setup/maintenance.

### CODE REVIEW

**Comment by richardlau** [comment]
Reading https://github.com/nodejs/build/blob/master/ONBOARDING.md I'll have to generate a GPG key... reading https://help.github.com/en/github/authenticating-to-github/generating-a-new-gpg-key there's a note about key algorithms... are there any restrictions/requirements around key algorithms for the purposes of this WG?

**Comment by Trott** [comment]
Wait, what, you're not a member? Yes, let's fix that.

**Comment by rvagg** [comment]
@richardlau no mandated restrictions, just make it good. We only use this for the secrets repo and the `dotgpg` program we use to encode and decode secrets. The repo is private and the files are encrypted with gpg keys so we have a double-layer of security. That's all.

**Comment by rvagg** [comment]
goodo! @richardlau give us a gpg pubkey, either in here or keybase or some other trusted mechanism (posted here from your GitHub account is "trusted" inasmuch as we need), and we'll get you added to secrets.

**Comment by richardlau** [comment]
@rvagg My public gpg key:

<details>

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBF222c0BEAC/wIiI7EYmA7yprNa/0en2leF+CrF09BlCItTHH5IgjSLGq2tI
Bi3hIhf7TitDlu6GphHlFjvhj6UDgdEmr0itcoOLRhtER6WlmMaXtS+im5fPSLWW
skZSAh1YC3iqOQCErkAnVFUWY5nUbWfxgv0pKrc5GTT2RkiD6ngor5YIAkRaYQ+n
niHsekUYOuLln0p4n/K0/iRw5NMok9Q2FwlEj7H0kCfDPuqsgfEoDXoVv8QSVIpB
1gdOQ7e2MeMAB6U5o0OjqzMxPUrIkDmgGIBvCgcCN33lMNO4DWlhr3vF90EhKvWP
Ly4kTa4Gctt9f5kICzb7AYZJG7+F8hrVHpbF0fXzTgZsO/BBf4ERTMKGfj7ZXq7e
GARTfDgzR9yxWfxfo47jUd8amVk/qj9O94lIPobEUeP7SKPy2jIRTx04HcdMDPAF
okzJf1cwCghc19mN+ro31rcnud0Za0EM7Yxq89GHvHiUEzxj2XWny3n583V4Lh6c
2bAm0tcqmJlLholeFo3qW/nBSCde0BjwfamKd4KB80tsF8Qu6OdahFT8ybaCA2ls
dcks9uAXXqwyTmXhwe22CHk/919Ubk0DFPozgj0AaDf+vQz+lKxDUuY0FaSEo3sP
nw7JmG1fdz2jAw0UvK4xGrYE8nTlF85mOBhV7zjwW57b9x07Og0zilqZhwARAQAB
tB9SaWNoYXJkIExhdSA8cmljbGF1QHVrLmlibS5jb20+iQJOBBMBCgA4FiEEyC+j
rhy+3Gvka5NgxDzsRcF6uTwFAl222c0CGwMFCwkIBwIGFQoJCAsCBBYCAwECHgEC
F4AACgkQxDzsRcF6uTxovw/+Mqq3Zn5BqiQQx13xOsJ25tvq7aa9BefOwhbSnguz
/ZScwwVxr1Ntp3+KWAdXPlLC0bzPpd6UAH8SXvJYNX3Oj4bKNXG/Vlarqh4ZDw0/
nJYJBlfHNDPU9pUaQzi15p+1H6KlaumhgiO36lX+pqtGAnKa7AMenDxXehuoxeqh
KjGsO2MfuoBEkcpiNhW4nxBwBDlmR3Evx/orUTejkBu+p+Vvz5lTvG7AqsU0JU6i
0gEV+2zBVSPyfxdNAzY6iNrFszcdhS7BG3xvjUq5xprp/w89DP/008KQDkU3UOcR
hR3MTQrLjXkR1b2wKz+zVyMnTJeZgQrPFvXwGZDVXIYlVYDKL5/gDwNP84Qo8P/i
OhMBpz7TmMxDXK4ijxf+WU67/5qBlVpLX3YEzvGIG8dmePed1NCTAEHPPAsmNUZ8
O+Uv7Y5k/ocJRjG/mCosKvfj92aOfvXTx8/mi+DOYLJGQwT9iLvnNIsYLpKCnWH/
HZo3u1LLhdkb1tMtGf8CITUqOvzf4WK+ouXDKA3meszFWWRMhT8fyZ7wF+ge7fuw
azDRUbY7xvUzbeT+AZKActHy+QHZonf6FpQy8+qaLI+Wsn42+IoQfdQSNTkWqhvK
CwFAugtb2/HZrwjxiMjNKZiZwC3Of4JZwzasjlUa2AEF6MDa5VT3W193WG2dKKBg
HsG5Ag0EXbbZzQEQAL9YA50WXd+iCK2rTlDk4Pv8piGkBu92CJ8ZlbP37AriS0xK
Ym78sWFqRwflFoerUwdPbC7PV5FuslRC3Y7T2T7uJOU08YEue5nCXgLJxnbtpjCK
oLlgDWgLgLcmtfQnQrZkIZmYQ6zlTFHrJZ+Mg29ku/JeZ7HHB3EPdQoFd0EIJJJy
5IUhJA10xnjND3RrSaApS0Q7swui8LXNOtLa/tpGXF/0OA6OjIXBxuT8lgTTUtk6
zz+ESw0BgI+GnYZmL65m/PSfTVd79PujWhP3e/OmDti8JxWVsvjhtbmS2ZNuQEKA
vGJS/ZoMrap2cuA7OrDM0/Ndoq9dft5yhWZbkwBNevPwXSo9ZVgtK+mZyVrQPKTf
PusjF27HwPw1xrSvj1h1b1bAlg19FJTTAv5GqOePlnbgUlPvJYt9R3gipBy2ZIwW
V9dfRZe848dz3dReD/+q1fNkQJJC76pv7T0CboEMHvKryKfsKNp6THyHWRE472kk
QZ7qF2ssxu3d+JHFvn+KEAmIbR+UfS5hnENVallHXRU4gtEAae8cBlXNnP8swzO6
BkgGqsERtvATTdb8xjRSUIcqPxv7EIRG57lnEHuGr6N1Xa6FAxTmhOy27AlmnbQy
aJmpDMe5s5XHApUbRA4Mq1qSbcOFNml3zUVKnCXaXY0B6MM5F3RPhRnx9LHRABEB
AAGJAjYEGAEKACAWIQTIL6OuHL7ca+Rrk2DEPOxFwXq5PAUCXbbZzQIbDAAKCRDE
POxFwXq5PLlHD/9kI4bENYzm/IE1EK0zp48LZCsaeZGZ/hyW0qJ9lnLyXKRmilHA
eLmD+tRXEnCOzmFwqftJpQJditx79uoyUiTiOA/yexia4/hrItZ8+E7lXQmvA6vE
FRMNZ+5+TtlOMMS8BL1kdyJIC589nDZorA8l8401e9nAGVtowhk/jWpF3tuRfb7s
VKvvWpzee/EJ1ntmUXi8FrhflMhBJafQaRdLFnrGTjr3iwh05TDEAbpwzTfZQkj6
YljJAFz+QwNZV9mK9hGzq1ExGo3B7EXdY7qelQIYTEByPXkRXa9jtUYJZOKX12hy
CYfONIFFcZcNryxbF+X7UtCnTrgyK8LZ3L1t2xKOxumvoeLnfOqXWdizm25eu1va
BKSmdYwwC9z9DYZqImYtOksLQoolqEh0LcqJBKJuItMKmDsBW5EB5IFinbpmzxa2
X4rvX7qNNQ46ky0sJzLW+bollsrn40S021IUyXq/FsisJTyFz7NdeTvEgr8uvOZJ
f++r9oEZw48siZNqjvPsejQjacu9UyXM0dCnJSaOm8OnZy8TpRB/ibYKg149T1Y2
+JrwHaXdKiM0U4k3a9X+TjA8BCV0+m3eY97cuFqXItaEGg/3FJyf9l5FS1bmjbon
dfTk3+rBsZ/tzDds+Jw2ir2mncO1jXgVls8xieBGoRWvH1N7nSSMNBG2Fw==
=8rRa
-----END PGP PUBLIC KEY BLOCK-----
```
</details>

**Comment by rvagg** [comment]
added to secrets/build/test

@trott or @sam-github would you mind adding Richard to the nodejs/build team if he's not already there please?

@richardlau once you're added you should have access to secrets, see the README @ https://github.com/nodejs-private/secrets/ for info on `dotgpg`. Once you have the SSH key installed in `~/.ssh/nodejs_build_test` then most of the Ansible inventry becomes accessible to you (`ansible-playbook playbooks/write-ssh-config.yml`). There's also Windows test machine login details in secrets.

**Comment by Trott** [comment]
> @Trott or @sam-github would you mind adding Richard to the nodejs/build team if he's not already there please?

Done.

Aside: We should probably go through and remove some of the inactive people....

**Comment by richardlau** [comment]
> 
> 
> > @Trott or @sam-github would you mind adding Richard to the nodejs/build team if he's not already there please?
> 
> Done.
> 

https://github.com/nodejs-private/secrets/ is still coming up as a 404 page not found for me.

**Comment by Trott** [comment]
> https://github.com/nodejs-private/secrets/ is still coming up as a 404 page not found for me.

That's because I only added you in to `nodejs/build` and not `nodejs-private/build`. I've just corrected that error and you should have access now.

**Comment by richardlau** [comment]
> 
> 
> > https://github.com/nodejs-private/secrets/ is still coming up as a 404 page not found for me.
> 
> That's because I only added you in to `nodejs/build` and not `nodejs-private/build`. I've just corrected that error and you should have access now.

Thanks, but I still don't have access 😞.

**Comment by rvagg** [comment]
let us know if you'd like a proper onboarding and someone may be able to take you through the basics, I suspect you know a lot of it already

**Comment by richardlau** [comment]
> 
> 
> let us know if you'd like a proper onboarding and someone may be able to take you through the basics, I suspect you know a lot of it already

I'll reach out if I get stuck. The good news is that the stuff documented in and linked from https://github.com/nodejs/build/blob/master/ONBOARDING.md is fairly easy to follow (🎉) and I've verified that I can ssh into some of the test machines (following https://github.com/nodejs/build/blob/master/doc/ssh.md). 

Is it too early to request being added to `nodejs/jenkins-admins` to expand the jobs I can edit on the test CI (I'm already in `citgm-admins` and `post-mortem-admins`)?

**Comment by rvagg** [comment]
Yeah, it's pretty early but you've been a great value-add with your Jenkins work already that I'm +1. I'll take this private and see what we can do. Easing in with small amounts of access like you've done is probably a good model for increasing access for others.

**Pull request merged**
