### PR TITLE
Start adding svn to test machines for V8 testing

### PR DESCRIPTION
**Pull request by mhdawson**

### CODE REVIEW

**Comment by mhdawson** [comment]
@jbergstroem  can you review ?

**Comment by mhdawson** [comment]
@jbergstroem  updated to add the rest of the platforms that made sense.  (Excluded raspberry pi as I don't think they will be powerful enough to run the v8 tests any time soon)

**Comment by jbergstroem** [comment]
LGTM

**Comment by mhdawson** [comment]
Landed as 12db79f166656da301138539fa2c5dac73992eb8

**Pull request closed without merging**
