### PR TITLE
ansible,jenkins: add OpenSSL 3.0.0 to sharedlibs container

### PR DESCRIPTION
**Pull request by richardlau**
Add OpenSSL 3.0.0 alpha13 to the sharedlibs container. Add an entry to
the VersionSelectorScript to build against it with Node.js 15 onwards.

Update OpenSSL 1.1.1g to 1.1.1k.

Refs: https://github.com/nodejs/build/issues/2584

### CODE REVIEW

**Comment by richardlau** [comment]
I've ansibled these changes on `test-softlayer-ubuntu1804_docker-x64-1` and restarted the sharedlibs containers on it.
I'm currently unable to edit/save https://ci.nodejs.org/job/node-test-commit-linux-containered or a copy of it which means I've not been able to test these changes on the CI.

**Review by AshCripps — APPROVED** [review]

**Comment by richardlau** [comment]
Forgot to state, the plan would be (when I can edit the job) to add the `ubuntu1804_sharedlibs_openssl300_x64` label to the CI job and a condition step for it based on the existing `ubuntu1804_sharedlibs_openssl111_x64` one but pointing at the OpenSSL 3.0.0 env var and directories.

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by rvagg — APPROVED** [review]
👌 I've been meaning to get around to that 1.1.1 bump too, so thanks for adding that in!

**Comment by richardlau** [comment]
Reansibled the two digitalocean docker hosts and added the `ubuntu1804_sharedlibs_openssl300_x64` label to them:
image

Still looking into the job edit/save issue.

**Comment by richardlau** [comment]
I managed to get an editable copy of [node-test-commit-linux-containered](https://ci.nodejs.org/job/node-test-commit-linux-containered) (https://github.com/nodejs/build/issues/2602#issuecomment-811914889) and was able to test these changes.

- First test build failed for a real test issue: 
https://ci.nodejs.org/job/node-test-commit-linux-containered-richard/3/nodes=ubuntu1804_sharedlibs_openssl300_x64/
- Passes with https://github.com/nodejs/node/pull/38027: 
https://ci.nodejs.org/job/node-test-commit-linux-containered-richard/4/nodes=ubuntu1804_sharedlibs_openssl300_x64/

I'll merge this PR and work on updating [node-test-commit-linux-containered](https://ci.nodejs.org/job/node-test-commit-linux-containered) separately (I'll post updates in https://github.com/nodejs/build/issues/2584).

**Pull request merged**
