### PR TITLE
ansible: add support for rhel72-s390x

### PR DESCRIPTION
**Pull request by maclover7**
playbooks/jenkins/worker/create.yml works now.

cc @nodejs/build

### CODE REVIEW

**Comment by gibfahn** [comment]
Wow, this is great.

LGTM if we can test it.

**Comment by mhdawson** [comment]
@jbarz can you test and add any changes needed to support gcc 4.8 and 4.9 concurrently?

**Comment by jBarz** [comment]
working on it

**Comment by gibfahn** [comment]
>@jBarz can you test and add any changes needed to support gcc 4.8 and 4.9 concurrently?

Seems like a separate PR, is there a reason for that to block this one?

**Comment by jBarz** [comment]
yea, that would be a separate PR.

**Comment by maclover7** [comment]
@jBarz @mhdawson Agree, I think gcc upgrade would best be kept separate from this. Are you able to review this PR as-is so we can land in current state

**Comment by maclover7** [comment]
Thank you for reviews! Landing

**Comment by maclover7** [comment]
Landed in d2942fe66f6b4bd2dba2b7ee37557ea7c3c8b608

**Pull request closed without merging**
