### PR TITLE
Removed macos10.14 machines from Orka in the Inventory

### PR DESCRIPTION
**Pull request by UlisesGascon**
close https://github.com/nodejs/build/issues/3087

### CODE REVIEW

**Review by targos — APPROVED** [review]

**Comment by targos** [comment]
Seems like Node.js 16 is still tested with macos10.14: https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1014/

**Comment by UlisesGascon** [comment]
@targos should we change the target to macos10.15 for Node.js 16? I am not sure how, but I can investigate it 🤔

**Comment by targos** [comment]
I went in a few Jenkins jobs (test-commit, test-commit-osx), and saved them to force removing the label from their configs so it should be fine for the next nightly runs.
Do you want to open a PR updating the version selector script?
https://github.com/nodejs/build/blob/612dcfead3720c178a76cfd827cd7ca408167987/jenkins/scripts/VersionSelectorScript.groovy#L131

**Comment by targos** [comment]
There are a few other things that can be cleaned up:
CleanShot 2023-05-03 at 11 06 38

**Pull request merged**
