### PR TITLE
setup: install lldb-3.6/lldb-3.6-dev on ubuntu

### PR DESCRIPTION
**Pull request by indutny**
Required for [llnode](https://github.com/indutny/llnode) smoke testing.

cc @nodejs/build

### CODE REVIEW

**Comment by indutny** [comment]
NOTE: I'm not sure if the lldb-3.6 is available on all of these platforms. Please re-check!

**Comment by jbergstroem** [comment]
Does it specifically require 3.6 or is it the lowest req?

**Comment by indutny** [comment]
I don't think it is the lowest required version, but I know for sure that it works starting from it.

**Comment by indutny** [comment]
Additional note: while not absolutely necessary, it will make things easier if the version of lldb will be the same across the machines. I'll need to supply path to `lldb` when running `llnode`'s build script, and this path depends on the version.

**Comment by TheAlphaNerd** [comment]
@indutny why is only ubuntu included? Smoke testing also runs on fedora, osx, and ppc

**Comment by indutny** [comment]
@TheAlphaNerd I'm sure that this thing works on OS X and Ubuntu, and OS X doesn't need any additional packages. I may take a look at fedor, but don't have access to ppc.

**Comment by jbergstroem** [comment]
@indutny that's kind of why I asked. Can only assume that mileage will vary between the different systems. I know FreeBSD only have 3.7 or 3.8.

**Comment by indutny** [comment]
So anything actionable on this?

**Comment by jbergstroem** [comment]
@indutny yeah; likely finding out all packages on the platforms we support and adding them to the playbooks. I can look at this, likely end of week. Is something held up by this at the moment?

**Comment by maclover7** [comment]
ping @indutny -- is this still needed? If yes, this will need to be updated to change `ansible`, not `setup`

**Comment by BridgeAR** [comment]
This should likely be closed. There was no progress for more than 1.5 years now.

**Comment by mmarchini** [comment]
Closing since this has been inactive for quite some time now and https://github.com/nodejs/build/pull/1025 downloads `lldb` before testing llnode. Feel free to reopen if you believe this should still land though.

**Pull request closed without merging**
