### PR TITLE
setup: remove osx

### PR DESCRIPTION
**Pull request by maclover7**
cc @gdams

### CODE REVIEW

**Comment by maclover7** [comment]
@gdams See #1357

**Comment by maclover7** [comment]
Actually, wait, yeah that probably won't cut it. Let me add to `doc/jenkins-guide.md`...

**Comment by gdams** [comment]
yeah we should add it somewhere convinent for people to easily look it up

**Comment by maclover7** [comment]
@gdams updated

**Comment by mhdawson** [comment]
I'm wondering if the non-MacStadium OSX machines (those I think that are in @rvagg's site) still need some of the parts being removed.  @rvagg can you comment.

**Comment by rvagg** [comment]
No, I think we're good to go with this. I believe I should be able to re-use the new Ansible scripts to re-setup the existing VMs if I dared blow away the existing state.

lgtm

**Comment by maclover7** [comment]
Landed in b804f76

**Pull request merged**
