### PR TITLE
ansible: add a third 10.14 mac

### PR DESCRIPTION
**Pull request by AshCripps**
10.14 macs are a bit of a bottleneck in CI at the moment so adding a third one to hopefully help alleviate the bottleneck

### CODE REVIEW

**Comment by AshCripps** [comment]
Anyone ever seen an error like this before?

```sh 
TASK [jenkins-worker : download slave.jar] ************************************************************************************************************************************************************************************************************************************************
task path: /Users/ashleycripps/nodework/build/ansible/roles/jenkins-worker/tasks/main.yml:151
fatal: [test-orka-macos10.14-x64-3]: FAILED! => {"changed": false, "msg": "Failed to validate the SSL certificate for ci.nodejs.org:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/ansible, /usr/local/etc/openssl. The exception msg was: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590).", "status": -1, "url": "https://ci.nodejs.org/jnlpJars/slave.jar"}
```

**Comment by AshCripps** [comment]
Got a more fuller stack trace for this error:

<details>

```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_get_url_payload_9QVDwK/ansible_get_url_payload.zip/ansible/module_utils/urls.py", line 1359, in fetch_url
    unix_socket=unix_socket)
  File "/tmp/ansible_get_url_payload_9QVDwK/ansible_get_url_payload.zip/ansible/module_utils/urls.py", line 1257, in open_url
    use_gssapi=use_gssapi, unix_socket=unix_socket)
  File "/tmp/ansible_get_url_payload_9QVDwK/ansible_get_url_payload.zip/ansible/module_utils/urls.py", line 1163, in open
    r = urllib_request.urlopen(*urlopen_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    req = meth(req)
  File "/tmp/ansible_get_url_payload_9QVDwK/ansible_get_url_payload.zip/ansible/module_utils/urls.py", line 870, in http_request
    build_ssl_validation_error(self.hostname, self.port, paths_checked, e)
  File "/tmp/ansible_get_url_payload_9QVDwK/ansible_get_url_payload.zip/ansible/module_utils/urls.py", line 671, in build_ssl_validation_error
    raise SSLValidationError(' '.join(msg) % (hostname, port, ", ".join(paths)))

fatal: [test-orka-macos10.14-x64-3]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "checksum": "",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "delimiter": null,
            "dest": "/Users/iojs/slave.jar",
            "directory_mode": null,
            "follow": false,
            "force": true,
            "force_basic_auth": false,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": 420,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "src": null,
            "timeout": 60,
            "tmp_dest": null,
            "unsafe_writes": null,
            "url": "https://ci.nodejs.org/jnlpJars/slave.jar",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Failed to validate the SSL certificate for ci.nodejs.org:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/ansible, /usr/local/etc/openssl. The exception msg was: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590).",
    "status": -1,
    "url": "https://ci.nodejs.org/jnlpJars/slave.jar"
}
```

</details>

**Comment by richardlau** [comment]
I haven't seen this error before, but from https://github.com/nodejs/build/issues/1901#issuecomment-532503742 we're using a Sectigo certificate which means it could be related to https://github.com/nodejs/node/issues/33681 (see https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020). I'm not sure how Python picks up root certificates on a mac (i.e. whether it's perhaps a Python update that might be required or something else that needs to be updated).

**Comment by rvagg** [comment]
Yeah, we're bundling the expired AddTrust:

addtrust_expired

I've removed that entirely from ci.nodejs.org, can you try again @AshCripps? That _should_ work, but if not we may have to re-generate the certs and install a new chain. Same chained bundle is on all our other properties.

**Comment by AshCripps** [comment]
@rvagg that did the trick the machine is connected now: https://ci.nodejs.org/computer/test-orka-macos10.14-x64-3/

**Comment by AshCripps** [comment]
test build - https://ci.nodejs.org/view/All/job/node-test-commit-osx-AshCripps/18/nodes=test-orka-macos10.14-x64-3/

**Pull request merged**
