### PR TITLE
Update nodejs.org.conf.j2

### PR DESCRIPTION
**Pull request by XhmikosR**
Adjust favicon.ico and apple-touch-icon.png path for https://github.com/nodejs/nodejs.org/pull/2402

**Should be merged and deployed after the aforementioned PR is merged!**

### CODE REVIEW

**Comment by rvagg** [comment]
I guess a successful merge of nodejs/nodejs.org#2402 would indicate sign-off from the website wg so that's fine by me.

**Comment by MylesBorins** [comment]
@rvagg I signed off on nodejs/nodejs.org#2402

would you be able to land it at the same time as deploying these updates?

**Comment by rvagg** [comment]
PR was against the wrong file, the active nodejs.org config is @ setup/www/resources/config/nodejs.org

I've updated the commit to make the same changes to that file, I've also put in a PR to remove the bogus config file to prevent further confusion.

@fhemberger this change, which you were responsible for, wasn't deployed properly for some reason, a diff showed it wasn't on the server but it is now:

```
243c243
<         if ($uri ~* ^/(es|it|ko|zh-cn|uk|ja|de|fr|ca|gl)/) {
---
>         if ($uri ~* ^/(ar|ca|de|es|fa|fr|gl|it|ja|ko|pt-br|uk|zh-cn|zh-tw)/) {
246c246
<         rewrite ^/(es|it|ko|zh-cn|uk|ja|de|fr|ca|gl)/(.*)$ /en/$2;
---
>         rewrite ^/(ar|ca|de|es|fa|fr|gl|it|ja|ko|pt-br|uk|zh-cn|zh-tw)/(.*)$ /en/$2;
```

**Comment by rvagg** [comment]
landed in 9162224c565

**Pull request closed without merging**
