### PR TITLE
doc: move people to emeritus

### PR DESCRIPTION
**Pull request by mhdawson**
Refs: https://github.com/nodejs/build/issues/3144

We'll have to remove access as part of landing this.

### CODE REVIEW

**Review by Starefossen — APPROVED** [review]

**Comment by phillipj** [comment]
Thanks for all the fun, I'll let you know if I end up having more time to contribute again down the road.

Don't hesitate to reach out if you think I might have some answers related to the github-bot for example.

**Review by richardlau — APPROVED** [review]

**Comment by Trott** [comment]
The [offboarding doc](https://github.com/nodejs/build/blob/349887dc3cee92973e24a7ff76561bb8897f2db1/OFFBOARDING.md) is 3 years old and might need some updates, but I guess that will be discovered once the offboarding tasks start to happen.

**Review by Trott — APPROVED** [review]

**Comment by Trott** [comment]
> We'll have to remove access as part of landing this.

Don't forget to check (and update, if necessary) the offboarding doc (linked above, but also easily findable in the repo).

**Review by MoLow — APPROVED** [review]

**Review by UlisesGascon — APPROVED** [review]

**Comment by aduh95** [comment]
There's a conflict to fix here.

**Comment by joyeecheung** [comment]
I would like to keep my access to the test machines, in case simple build machine issues that I can fix comes up and no one else is around (that was the reason why I updated my keys in the secrets repo recently, and I did a few orka machine disk cleanup recently so it seems useful).

**Pull request merged**
