### PR TITLE
metrics: skip empty lines in process cloudflare

### PR DESCRIPTION
**Pull request by trivikr**
Refs: https://github.com/nodejs/build/issues/3697#issuecomment-2177237274

### CODE REVIEW

**Comment by trivikr** [comment]
cc @targos

**Comment by targos** [comment]
Is it normal to have empty lines?

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by trivikr** [comment]
This PR is good to merge, and `gcloud run deploy` is successful

https://github.com/nodejs/build/pull/3767#issuecomment-2189157376

**Comment by trivikr** [comment]
Deployed, and verified that errors are no longer logged.

### Before

```console
EVENT TYPE:  OBJECT_FINALIZE
Node version is: v20.14.0
BUCKET cloudflare-logs-nodejs
FILENAME 20240625/20240625T193221Z_20240625T193327Z_121d0e03.log.gz
PROCESSEDFILENAME 20240625/20240625T193221Z_20240625T193327Z
INSIDE CREATE PIPELINE
String length:  23750258
Array Length:  48452
SyntaxError: Unexpected end of JSON input     at JSON.parse (<anonymous>)     at /usr/src/app/process-cloudflare.js:164:34     at callback (/usr/src/app/node_modules/@google-cloud/storage/build/src/file.js:1624:17)     at /usr/src/app/node_modules/@google-cloud/storage/build/src/file.js:1640:87     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Upload complete
rss 358.32 MB
heapTotal 57.23 MB
heapUsed 44.96 MB
external 26.86 MB
arrayBuffers 23.75 MB
```

### After 

```console
EVENT TYPE:  OBJECT_FINALIZE
Node version is: v20.15.0
BUCKET cloudflare-logs-nodejs
FILENAME 20240625/20240625T193633Z_20240625T193744Z_8987830a.log.gz
PROCESSEDFILENAME 20240625/20240625T193633Z_20240625T193744Z
INSIDE CREATE PIPELINE
String length:  9327443
Array Length:  18849
Upload complete
rss 157.49 MB
heapTotal 31.18 MB
heapUsed 25.12 MB
external 12.45 MB
arrayBuffers 9.35 MB
```

**Pull request merged**
