### PR TITLE
jenkins: backup benchmark-node-micro-benchmarks-compare

### PR DESCRIPTION
**Pull request by refack**
AFAICT it never worked.
https://ci.nodejs.org/job/benchmark-node-micro-benchmarks/ is used instead.

### CODE REVIEW

**Comment by mhdawson** [comment]
@refack can you fill in any context.  As far as I know the job was working fine for people (unless there is a different one that lets people run the microbenchmarks) and there was even requests to extend it.

There seem to be a few successful runs as well>

**Comment by refack** [comment]
> unless there is a different one that lets people run the microbenchmarks

That what I think is going on.
This job was called `benchmark-node-micro-benchmarks-compare` and it was never used, and AFAICT never worked.
The one that is used and works Ok is the one I linked in the OP - https://ci.nodejs.org/job/benchmark-node-micro-benchmarks/ - which I assume is the one you are looking at.

**Comment by mhdawson** [comment]
@refack ok that makes sense to me.  My understanding based on the last discussion around  https://ci.nodejs.org/job/benchmark-node-micro-benchmarks/ was that instead of a new job we could just add options to the existing one.  We can always create a new job if needed as well.

**Comment by refack** [comment]
Added two other unused jobs.

P.S. @mhdawson is this https://ci.nodejs.org/view/Node.js%20Daily/job/node-test-commit-linux-coverage-new/jobConfigHistory/ still needed?

**Comment by mhdawson** [comment]
@refack I think we can get rid of s https://ci.nodejs.org/view/Node.js%20Daily/job/node-test-commit-linux-coverage-new/jobConfigHistory/

**Comment by sam-github** [comment]
stale, and @AshCripps recently cleaned out unused jobs.

**Pull request closed without merging**
