### PR TITLE
dist: add PPC LE machine

### PR DESCRIPTION
**Pull request by mhdawson**
Add PPC LE machine to inventory

Not sure if I should be adding myself to setup/ubuntu14.04/ansible-vars.yaml but did want to be able to access the machines for debugging

### CODE REVIEW

**Comment by jbergstroem** [comment]
LGTM

**Comment by mhdawson** [comment]
Do we need any more reviewers before pulling this in ?

**Comment by rvagg** [comment]
no, go for it, lgtm if that helps

**Comment by mhdawson** [comment]
Fixed up to follow standard procedure as opposed to using merge button

Landed as 8fce5b90feaa1b59ce457268ae95c532ef2e0524

**Pull request merged**
