### PR TITLE
chore(try-files): try files instead of error

### PR DESCRIPTION
**Pull request by ovflowd**
This PR fixes the server errors we're getting when 404'ing these paths.

### CODE REVIEW

**Comment by targos** [comment]
Does it mean that we will respond with code 200 instead of 404?

**Comment by ovflowd** [comment]
It will respond with 404 if the file is 404. But it will not create an error.

**Comment by targos** [comment]
https://github.com/nodejs/build/pull/3222/commits/0790757e4e29eda98a5c4aedf4a7e6176e5b0082 is deployed on the server
Spam requests from https://github.com/nodejs/build/issues/3223 now don't generate errors anymore and go in the access log

**Comment by ovflowd** [comment]
@Trott @targos @richardlau this can probably be merged as it was deployed.

**Pull request merged**
