### PR TITLE
ansible: update for new jenkins-workspace machine

### PR DESCRIPTION
**Pull request by maclover7**
cc @rvagg, this broke because of new jenkins workspace machine being added

### CODE REVIEW

**Comment by rvagg** [comment]
yoik! thanks for picking this up

**Comment by maclover7** [comment]
@rvagg Would you be able to run the ansible job for github-bot? I don't think I have machine access

**Comment by rvagg** [comment]
I just did it manually, I'm not confident about the script and haven't run this particular one before so I've edited the environment file and changed that last line and restarted the service. Could you confirm it's working?

**Comment by maclover7** [comment]
@rvagg yep, looks to be working again. Thank you for your help!

**Pull request merged**
