### PR TITLE
Initial outline for onboarding

### PR DESCRIPTION
**Pull request by jbergstroem**
Just getting this up here to get more eyeballs. I'll expand on each section incrementally.

### CODE REVIEW

**Comment by Starefossen** [comment]
Great work, Johan! If you need a candidate to test the on-boarding on I would happily volunteer. I could use a formal introduction to our Ansible / Jenkins Slave setup.

**Comment by jbergstroem** [comment]
@Starefossen cool! This is based on the session I did with @phillipj but I'm happy to run you through as well. Chat me up in private (IRC or smith) and we'll set up a time.

**Comment by Trott** [comment]
I'm happy to be a test subject for this too, if that's helpful.

**Comment by jbergstroem** [comment]
Thanks! Super cool to have one on ones with all of you :)

**Comment by phillipj** [comment]
The things covered here was pretty much ideal. Most of it was new to me and I've got ~zero  ansible experience, but did cover [getting started with ansible](http://docs.ansible.com/ansible/intro_getting_started.html) beforehand so I had some idea what inventory and playbooks were, which was helpful to follow along with the examples shown from the build repo.

Bottom line great onboarding by @jbergstroem 👍

**Comment by rvagg** [comment]
LRGTM ("really"), perhaps you could land this and then we could have one of our new onboardees file another PR to add some meat into here that we could get out of our heads and into a doc. There's a few things in here that are best suited to 1:1 explanation but a lot of it could just be captured in text.

**Comment by joaocgreis** [comment]
LGTM! Perhaps some things that could be added is mentions to the web server, the GH bot, and how the release files go from the release machines to public. Some of this is still a bit dark to me and I guess newcomers would appreciate the overview.

**Comment by jbergstroem** [comment]
@joaocgreis thanks for the feedback! I'll revise.

**Comment by mhdawson** [comment]
LTGM from me as well.  I'll echo @rvagg's comment that this would be a good template to flesh out into document(s) to help us all remember the parts we don't do day to day.

**Comment by jbergstroem** [comment]
@mhdawson My idea was to expand before landing. I don't aim to replace README.md or similar, but lest se how we go.

**Pull request merged**
