### PR TITLE
doc: add sam-github to members

### PR DESCRIPTION
**Pull request by sam-github**
Fixes: #1771

### CODE REVIEW

**Comment by sam-github** [comment]
So, what happens next? I guess someone has to add me to team? I can't land this myself, not until I have permissions.

Is there an onboarding process, @mhdawson ? How do I get ssh access to the test machines, like AIX?

**Comment by rvagg** [comment]
@sam-github first, give me a gpg key and I'll add you to secrets/build/test which gives you access to all our test machines. Some onboarding might be worthwhile but you seem to be getting up to speed pretty quickly by contributing to ansible/.

**Comment by sam-github** [comment]
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBFzB1HwBDADHhkQ1rouLAJ8/ZmeJ4U6KVtdAzMIrvuI1tX2Inf6YuVi7k1uw
LOGV0B/03EFqtyVqqD2qyuxkfdgIoMwEvf5LiqdQf/x0j5veCzvpuST+awKCb2Rk
47TnYycZ+AF91tFGiI38XlR60+lJE8ImVXVbl/nrWSNZhRoHrTdTFww9z16DXxRP
QG8Y9g8H9I8QPkkPngdLhtyKRQJEX0/AxUQjUAlmWUQUg8bfkQMq+smV0PXYNdGq
3ftRbs0usM4BrRqnw2DbeV2+ZcC4fYowslQMpALRfx9/gesKGbUH1VGeVjWQynfu
ey+w6jUD4JGYnJnYWlT0PhPS0nXh3eAZFEyTYNtOCd58CXz74D6RNwuuh2N/xek2
Ec0UX/1XFmeyL7z4Buek+Ymbzgd005hZJMpiYeDrNbQDGxgA8McCfOzCS1HLacrC
8M+ZaJHykkqSLkGkj/GVvgen+APwBv8jy9KiOMtpOaTNmjH2d9ovsb3RI8JmtDSA
hvWpEsO5iEumLFEAEQEAAbQhU2FtIFJvYmVydHMgPHZpZXV4dGVjaEBnbWFpbC5j
b20+iQHOBBMBCgA4FiEEUYK0l69RQ1CY2U/3/S0tWaas73YFAlzB1HwCGwMFCwkI
BwIGFQoJCAsCBBYCAwECHgECF4AACgkQ/S0tWaas73Zssgv/fSu16+vu/1AyzEjM
zs/DmCduCK9cp3okvzjmhQ7IjMnPgBd+imhqIg+WpPRsvxLkKTDzeH9sy8k5adxu
2cnB68o3TsML7f4EY7wZJXM5Kq5r7vwCrGECojOuy/pxppdaMmQKyjYBo7PBY3Sa
5aiifS1FdXOBgE45E1eqNx/9fSjpD9URWP0+uW+NAvwfFIva7aXaroVwair3oie9
joOeJQNt/S/93jjASnYGkEELrEk0W2FXXmudenHGu8pISM9Cfe0sCn26pZXjpQrw
yk2pl0SG8tKweZikC/x/FZOx6Yd7MLbf4VxjQPKu+t+r2h6voong0iCCWi0PExjY
1q+9MyPIbBTBNZriQXLWkvMIP0IF1HKRZMlYLioekAQEvO9L8nyhBzgn5TjqApLO
3bkWEmV5IWJ3KOeYab0dCtWUHADpnENt6897XDoXFodTECG+jJ2nfe5wZFCghJlg
3FvvIM+g+EnS1IM3a7iGKmVTd7zFBEdyseICmhoecGmt7XmMuQGNBFzB1HwBDACf
JIHvSuj9qm8BziBr4r2rIguD1dr0hR3VdmmshbfK/+Tvm2JWi7raOworW5agUBu9
X01TSk+ZwdTkoqW9wxjMxeAL5HTb+Cf1H/XQ0aNFKIR8AY+GI+osw+zgxnG5Qlu/
JOU609VHTEHHmSxtE/EWIzVZfCS/ztyrnhXkX+PNznImmj/z2WQtQtpEAktJ03ws
X6mkU/D2xjfAPSLmirqYAHRV5IZKNnFBUxgLeGs6+CBEfv77qegbCN6YlHB6oC0W
OU55rkht9dzFwxWPuauTS6Y1ntnz2GzAcfT68MwBVuJois+VeuF/2SNXWSNAW+Xo
r/CctfZ0AffuhxGiSvfMu/11+S7nDpTmDPSO79rjEkcg+lvTiq5zb6LeNM/RdrUI
qVIns1kaUYcaUJfG5XYRDb8aYYD3jhuo/ivYXosxGNjZ8DlrAhq0yfsDRHs/UGt+
Sl7lgzVq1Bg3Sl0eY23F+HgNivlWuEZ4s5HkDDyK4jjVWWFcBMT72a46mGynmJUA
EQEAAYkBtgQYAQoAIBYhBFGCtJevUUNQmNlP9/0tLVmmrO92BQJcwdR8AhsMAAoJ
EP0tLVmmrO926xUMAMNgVBPcNMugvHqROxPmXVRoC3+0Wg5wGwl8/vJmzNG0Qwf2
5oVweGNt1slVz7eGEBIRsW50KMo+hESjmiAsDbMvL5HQzbLlwCQGuCJerXMC93Ap
e5ML7LScCQBuywwlW2lHLxYoM5TEfiU3ClTIW8eLCxTHe66UFCUvySlVinCG7ENZ
bPLnvd8KR9nYGC3JUfb3wNGhfLrgyUCpIgRG7p+PYcnLLZ6bIg41fgm34Qq+8IXU
U21CwSp/XcTyEE07tU/ZtEWJcAXUt6amUD0M0J5L1BHK+FdOj64Y/TkH2pfEpOze
9hqYXoS5BK/XaJE4oXWsKd4+SNsp95GT4DXEM3vZXprtpMfuTkv10PCN64jyebna
sLTqQem1g0vPdjALdcZl7XwcX5Db88EE/980aMTVBaISfURtvzNYJJnsH5quncVq
yhaJmw/MlJLfla99+PiRoeHTBQ9W5WoijK1NvN2TAt8BuAGD9395zy1evrhRyPWs
FvTkDZC9lLeXDV8qFg==
=EEtp
-----END PGP PUBLIC KEY BLOCK-----
```

^--- @rvagg that what you need? It's been a long time since I've used gpg.

**Comment by rvagg** [comment]
@sam-github :thumbsup: I've added you to nodejs/build and nodejs-private/build and put your key into [nodejs-private/secrets](https://github.com/nodejs-private/secrets/)/build/test. You should read the README in the secrets repo and get set up with `dotgpg` which is how we read and write files in there using our GPG keys. When you've done that you can grab the `nodejs_build_test` SSH key and put it in `~/.ssh/`. If you haven't already, run `ansible-playbook playbooks/write-ssh-config.yml` in the build/ansible directory and if you have the `# begin: node.js template` and `# end: node.js template` lines in your ~/.ssh/config then you should get all of the hosts out of inventory.yml into there and you'll be able to SSH in to any of the ones that start with `test-`. YMMV with `write-ssh-config.yml` however as I think it still has some Python 3 issues, at least for me I don't get a proper config on my Mac so I use it mainly on Linux where Python 2 is the default for Ansible. Windows logins are in secrets/build/test/windows-servers.md for connection via remote desktop. I think you've already had a baptism-by-fire with Ansible so you probably know way more than the average new Build person about how that stuff all works. Also make sure you linger on `#nodejs-build` on Freenode. It's low-traffic but where some urgent _HELP_ calls go.

Aside from that, have a poke around, there's plenty of ways to improve things and it'll depend mainly on what interests you, your expertise, and seems most pressing. Once the nodejs/build github notifications start rolling in and you see the kinds of things that show up in `#nodejs-build` it might be obvious to you where the greatest value-add could come from.

Aside from that I'm not sure what other good pointers are good for an onboarding. There are some tools but I'm not sure what others find helpful at the moment. I mainly interact with Jenkins and occasionally run the `build/tools/jenkins-status/` script to see what machines need attention.

There's scope to expand to Jenkins administration too, having write access to the configs, if you're interested. That's another layer of permissions.

**Pull request merged**
