### PR TITLE
doc: Fix a typo and adjust line width

### PR DESCRIPTION
**Pull request by jbergstroem**
/R=@bnoordhuis?

### CODE REVIEW

**Comment by rvagg** [comment]
rly? is this necessary? do y'all have 640x480 monochrome monitors still?

**Comment by jbergstroem** [comment]
The w80 kinda snuck in there -- I read somewhere that the recommended markdown width should be 80 [link needed] which is why I changed it while at it.

**Comment by jbergstroem** [comment]
It's kind of useful should you open README.md in your favourite terminal emulator as well.

**Comment by bnoordhuis** [comment]
Rubber-stamp LGTM.

**Comment by jbergstroem** [comment]
@rvagg plz?

**Comment by rvagg** [comment]
your call, manual line wrapping makes zero sense to me

**Comment by jbergstroem** [comment]
Guessing a lot in the readme's will change once I start messing with abstractions. I'll close this and tell my better future self to revisit.

**Pull request closed without merging**
