### PR TITLE
redirect for Windows Environment wiki page

### PR DESCRIPTION
**Pull request by joaocgreis**
This is necessary to land https://github.com/nodejs/node/pull/4111

@rvagg is this the correct way to add the redirect?

### CODE REVIEW

**Comment by rvagg** [comment]
yes, I think remove the first one though, let the direct go through from http to https and we'll always just link to the https version when we refer to it publicly anyway

**Comment by jbergstroem** [comment]
+1 to https only. Redirects like these will stay in a config forever; the less rules the better

**Comment by joaocgreis** [comment]
Thanks, updated

**Comment by orangemocha** [comment]
LGTM

**Comment by joaocgreis** [comment]
@rvagg what more needs to be done here to update the server config?

**Comment by rvagg** [comment]
Sorry! Someone with access to the web server just needed to drop this in /etc/nginx/sites-available/ and reload nginx. I've done that now, https://nodejs.org/windows-environment is active.

**Comment by joaocgreis** [comment]
Thanks!

**Comment by jbergstroem** [comment]
@joaocgreis (you should have access with the infra key)

**Pull request merged**
