### PR TITLE
Revert "ansible: temporarily patch libstdc++ header on s390x"

### PR DESCRIPTION
**Pull request by richardlau**
This reverts commit 9c149d0e687f9c987d50876b95a7c73fa78c6328.

`gcc-toolset-12` now includes the fix we were temporarily patching for.

Refs: https://github.com/nodejs/build/pull/3659#issuecomment-2059807142
Refs: https://github.com/nodeshift/v8-build/pull/7

### CODE REVIEW

**Comment by richardlau** [comment]
So what appears to be happening is that according to `dnf` there is glibc 251.el8_10.2 available:
```console
[linux1@test-ibm-rhel8-s390x-4 ~]$ sudo dnf info glibc
Failed to set locale, defaulting to C.UTF-8
Updating Subscription Management repositories.
Last metadata expiration check: 0:17:55 ago on Thu May 23 13:00:25 2024.
Installed Packages
Name         : glibc
Version      : 2.28
Release      : 251.el8_10.2
Architecture : s390x
Size         : 5.0 M
Source       : glibc-2.28-251.el8_10.2.src.rpm
Repository   : @System
From repo    : rhel-8-for-s390x-baseos-rpms
Summary      : The GNU libc libraries
URL          : http://www.gnu.org/software/glibc/
License      : LGPLv2+ and LGPLv2+ with exceptions and GPLv2+ and GPLv2+ with exceptions and BSD and Inner-Net and ISC and Public Domain and GFDL
Description  : The glibc package contains standard libraries which are used by
             : multiple programs on the system. In order to save disk space and
             : memory, as well as to make upgrading easier, common system code is
             : kept in one place and shared between programs. This particular package
             : contains the most important sets of shared libraries: the standard C
             : library and the standard math library. Without these two libraries, a
             : Linux system will not function.

[linux1@test-ibm-rhel8-s390x-4 ~]$ sudo dnf update glibc
Failed to set locale, defaulting to C.UTF-8
Updating Subscription Management repositories.
Last metadata expiration check: 0:20:58 ago on Thu May 23 13:00:25 2024.
Dependencies resolved.
Nothing to do.
Complete!
[linux1@test-ibm-rhel8-s390x-4 ~]$
```

However, installing a `gcc-toolset-*` (I've tried 12 and 13 which are in support, and 10 which is not) wants to downgrade glibc to glibc 2.28-251.el8_10.1. 
```console
[linux1@test-ibm-rhel8-s390x-4 ~]$ sudo dnf install gcc-toolset-12
Failed to set locale, defaulting to C.UTF-8
Updating Subscription Management repositories.
Last metadata expiration check: 0:19:38 ago on Thu May 23 13:00:25 2024.
Dependencies resolved.
=================================================================================================================================================================================================================
 Package                                                       Architecture                      Version                                       Repository                                                   Size
=================================================================================================================================================================================================================
Installing:
 gcc-toolset-12                                                s390x                             12.0-6.el8                                    rhel-8-for-s390x-appstream-rpms                              11 k
Installing dependencies:
 gcc-toolset-12-annobin-plugin-gcc                             s390x                             11.08-1.el8                                   rhel-8-for-s390x-appstream-rpms                             916 k
 gcc-toolset-12-gcc                                            s390x                             12.2.1-7.6.el8_10                             rhel-8-for-s390x-appstream-rpms                              32 M
 gcc-toolset-12-gcc-c++                                        s390x                             12.2.1-7.6.el8_10                             rhel-8-for-s390x-appstream-rpms                              10 M
 gcc-toolset-12-gcc-gfortran                                   s390x                             12.2.1-7.6.el8_10                             rhel-8-for-s390x-appstream-rpms                             9.8 M
 glibc-devel                                                   s390x                             2.28-251.el8_10.1                             rhel-8-for-s390x-baseos-rpms                                104 k
 glibc-headers                                                 s390x                             2.28-251.el8_10.1                             rhel-8-for-s390x-baseos-rpms                                484 k
 libxcrypt-devel                                               s390x                             4.1.1-6.el8                                   rhel-8-for-s390x-baseos-rpms                                 25 k
Installing weak dependencies:
 glibc-gconv-extra                                             s390x                             2.28-251.el8_10.1                             rhel-8-for-s390x-baseos-rpms                                1.5 M
 glibc-langpack-en                                             s390x                             2.28-251.el8_10.1                             rhel-8-for-s390x-baseos-rpms                                813 k
Downgrading:
 glibc                                                         s390x                             2.28-251.el8_10.1                             rhel-8-for-s390x-baseos-rpms                                1.8 M
 glibc-common                                                  s390x                             2.28-251.el8_10.1                             rhel-8-for-s390x-baseos-rpms                                1.2 M
 glibc-langpack-agr                                            s390x                             2.28-251.el8_10.1                             rhel-8-for-s390x-baseos-rpms                                385 k

Transaction Summary
=================================================================================================================================================================================================================
Install    10 Packages
Downgrade   3 Packages

Total download size: 59 M
Is this ok [y/N]:
```

If I (or our Ansible playbook) proceeds, then glibc is downgraded, but attempts to upgrade to glibc 251.el8_10.2 fail:
```console
[linux1@test-ibm-rhel8-s390x-4 ~]$ sudo dnf info glibc
Updating Subscription Management repositories.
Last metadata expiration check: 0:21:52 ago on Thu 23 May 2024 01:00:25 PM EDT.
Installed Packages
Name         : glibc
Version      : 2.28
Release      : 251.el8_10.1
Architecture : s390x
Size         : 5.0 M
Source       : glibc-2.28-251.el8_10.1.src.rpm
Repository   : @System
From repo    : rhel-8-for-s390x-baseos-rpms
Summary      : The GNU libc libraries
URL          : http://www.gnu.org/software/glibc/
License      : LGPLv2+ and LGPLv2+ with exceptions and GPLv2+ and GPLv2+ with exceptions and BSD and Inner-Net and ISC and Public Domain and GFDL
Description  : The glibc package contains standard libraries which are used by
             : multiple programs on the system. In order to save disk space and
             : memory, as well as to make upgrading easier, common system code is
             : kept in one place and shared between programs. This particular package
             : contains the most important sets of shared libraries: the standard C
             : library and the standard math library. Without these two libraries, a
             : Linux system will not function.

Available Packages
Name         : glibc
Version      : 2.28
Release      : 251.el8_10.2
Architecture : s390x
Size         : 1.8 M
Source       : glibc-2.28-251.el8_10.2.src.rpm
Repository   : rhel-8-for-s390x-baseos-rpms
Summary      : The GNU libc libraries
URL          : http://www.gnu.org/software/glibc/
License      : LGPLv2+ and LGPLv2+ with exceptions and GPLv2+ and GPLv2+ with exceptions and BSD and Inner-Net and ISC and Public Domain and GFDL
Description  : The glibc package contains standard libraries which are used by
             : multiple programs on the system. In order to save disk space and
             : memory, as well as to make upgrading easier, common system code is
             : kept in one place and shared between programs. This particular package
             : contains the most important sets of shared libraries: the standard C
             : library and the standard math library. Without these two libraries, a
             : Linux system will not function.

[linux1@test-ibm-rhel8-s390x-4 ~]$ sudo dnf update glibc
Updating Subscription Management repositories.
Last metadata expiration check: 0:22:47 ago on Thu 23 May 2024 01:00:25 PM EDT.
Error:
 Problem: problem with installed package glibc-langpack-en-2.28-251.el8_10.1.s390x
  - package glibc-langpack-en-2.28-251.el8_10.1.s390x from @System requires glibc = 2.28-251.el8_10.1, but none of the providers can be installed
  - package glibc-langpack-en-2.28-251.el8_10.1.s390x from rhel-8-for-s390x-baseos-rpms requires glibc = 2.28-251.el8_10.1, but none of the providers can be installed
  - cannot install both glibc-2.28-251.el8_10.2.s390x from rhel-8-for-s390x-baseos-rpms and glibc-2.28-251.el8_10.1.s390x from @System
  - cannot install both glibc-2.28-251.el8_10.2.s390x from rhel-8-for-s390x-baseos-rpms and glibc-2.28-251.el8_10.1.s390x from rhel-8-for-s390x-baseos-rpms
  - cannot install the best update candidate for package glibc-2.28-251.el8_10.1.s390x
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[linux1@test-ibm-rhel8-s390x-4 ~]$
```

`--allowerasing` would result in the removal of the toolset, and we're then in a loop as rerunning the playbook would reinstall the toolset, downgrading glibc and then rerunning the playbook again would fail to update glibc.
```console
[linux1@test-ibm-rhel8-s390x-4 ~]$ sudo dnf update glibc --allowerasing
Updating Subscription Management repositories.
Last metadata expiration check: 0:25:00 ago on Thu 23 May 2024 01:00:25 PM EDT.
Dependencies resolved.
=================================================================================================================================================================================================================
 Package                                                      Architecture                     Version                                         Repository                                                   Size
=================================================================================================================================================================================================================
Upgrading:
 glibc                                                        s390x                            2.28-251.el8_10.2                               rhel-8-for-s390x-baseos-rpms                                1.8 M
 glibc-common                                                 s390x                            2.28-251.el8_10.2                               rhel-8-for-s390x-baseos-rpms                                1.2 M
 glibc-langpack-agr                                           s390x                            2.28-251.el8_10.2                               rhel-8-for-s390x-baseos-rpms                                385 k
Removing dependent packages:
 gcc-toolset-12                                               s390x                            12.0-6.el8                                      @rhel-8-for-s390x-appstream-rpms                            1.7 k
 gcc-toolset-12-annobin-plugin-gcc                            s390x                            11.08-1.el8                                     @rhel-8-for-s390x-appstream-rpms                            888 k
 gcc-toolset-12-gcc                                           s390x                            12.2.1-7.6.el8_10                               @rhel-8-for-s390x-appstream-rpms                             82 M
 gcc-toolset-12-gcc-c++                                       s390x                            12.2.1-7.6.el8_10                               @rhel-8-for-s390x-appstream-rpms                             27 M
 gcc-toolset-12-gcc-gfortran                                  s390x                            12.2.1-7.6.el8_10                               @rhel-8-for-s390x-appstream-rpms                             29 M
 glibc-devel                                                  s390x                            2.28-251.el8_10.1                               @rhel-8-for-s390x-baseos-rpms                               1.7 M
 glibc-gconv-extra                                            s390x                            2.28-251.el8_10.1                               @rhel-8-for-s390x-baseos-rpms                               6.2 M
 glibc-headers                                                s390x                            2.28-251.el8_10.1                               @rhel-8-for-s390x-baseos-rpms                               1.9 M
 glibc-langpack-en                                            s390x                            2.28-251.el8_10.1                               @rhel-8-for-s390x-baseos-rpms                               5.7 M
 libxcrypt-devel                                              s390x                            4.1.1-6.el8                                     @rhel-8-for-s390x-baseos-rpms                                24 k

Transaction Summary
=================================================================================================================================================================================================================
Upgrade   3 Packages
Remove   10 Packages

Total download size: 3.4 M
Is this ok [y/N]:
```

**Comment by richardlau** [comment]
I was only able to do a quick test today (running the `dnf` commands directly) but it looks like the problem may have been resolved (which indicates it was probably an issue with the packages/repository rather than something we did). I'll do further testing to confirm on Tuesday.

**Comment by richardlau** [comment]
Looks like the `dnf` issues are resolved.

Deploying the changes:
- [ ] [release-ibm-rhel8-s390x-1](https://ci-release.nodejs.org/computer/release-ibm-rhel8-s390x-1/)
- [ ] [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/computer/test%2Dibm%2Drhel8%2Ds390x%2D1/)
- [x] [test-ibm-rhel8-s390x-2](https://ci.nodejs.org/computer/test%2Dibm%2Drhel8%2Ds390x%2D2/)
- [ ] [test-ibm-rhel8-s390x-3](https://ci.nodejs.org/computer/test%2Dibm%2Drhel8%2Ds390x%2D3/)
- [x] [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/computer/test%2Dibm%2Drhel8%2Ds390x%2D4/)

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
