### PR TITLE
chore: Add Shellcheck CI action

### PR DESCRIPTION
**Pull request by nschonni**
Setup the CI to see if this makes sense to add here before trying to fix any of the things it's flagging.

### CODE REVIEW

**Comment by nschonni** [comment]
I disabled all the failing checks so they could be resolved later.
Included a commit that ran `shfmt -w .` to address a few auto-fixable things, but could rebase that out to keep this simpler

**Comment by nschonni** [comment]
@richardlau does this make sense?

**Comment by richardlau** [comment]
> 
> 
> @richardlau does this make sense?

I like the idea of linting for consistency but as it stands this looks like too much churn (in terms of the number of files being changed). It's also going to be difficult to update all the places these scripts are actually deployed. For example, for things under `ansible/*-standalone` @rvagg has previously informed me that most of that is a record of what's on the machines but it's mostly manual synced and we have no guarantee it those can actually be deployed via ansible. Other stuff under `ansible` would require the CI hosts to be reansibled which is going to take a lot of someone's time. 

(I'm also not a fan of replacing spaces with tabs but if there's agreement from the other @nodejs/build members I'm willing to cede.)

**Comment by nschonni** [comment]
> I like the idea of linting for consistency but as it stands this looks like too much churn (in terms of the number of files being changed).

It could possibly be batched by folder before adding the CI




> (I'm also not a fan of replacing spaces with tabs but if there's agreement from the other @nodejs/build members I'm willing to cede.)

No preference from me, but it looks like it can be set https://github.com/mvdan/sh/blob/master/cmd/shfmt/shfmt.1.scd#L59-L61, just the default is tabs

**Comment by mhdawson** [comment]
I favor spaces instead of tabs and also share the concern about changing things that may be a lot of effort to test/validate.

In other repos when we've turned on linting there has been an option to only lint on code which has been changed. Is that an option?

**Comment by nschonni** [comment]
Ok, rebased out the `shfmt` commits and left it with all failing rules disabled

**Review by Trott — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM, given that it won't fail on any existing files I'm willing to give it a try.

**Review by richardlau — APPROVED** [review]

**Pull request merged**
