### PR TITLE
Rewrite http://blog.nodejs.org/feed/

### PR DESCRIPTION
**Pull request by fhemberger**

### CODE REVIEW

**Comment by jbergstroem** [comment]
Have we ever referenced this path?

**Comment by fhemberger** [comment]
I had in my RSS reader, having subscribed to the old website's feed. Took a while to recognize it was gone, as I'm reading most postings as PR notifications. ;)

**Comment by jbergstroem** [comment]
Ok, cool. It looks like the line below tries to attempt the same thing though. Perhaps look at fixing that instead (suspected missing trailing slash)?

**Comment by fhemberger** [comment]
@jbergstroem Okay, updated the PR. Rewrite specific feeds first, everything else starting with 'atom', 'feed' or 'rss' should redirect to the current blog feed. Also much easier to read. ;)

**Comment by jbergstroem** [comment]
LGTM. I can merge this in a few days.

**Comment by fhemberger** [comment]
Can we please get this fixed?

**Comment by jbergstroem** [comment]
Sorry; I'll get it done.

**Comment by jbergstroem** [comment]
Merged in 04bb6ba5758f618a88216fde404d235a9ab4ce29. Btw, guessing you edited through online? Suggesting you change your email through git config (currently `fhemberger@users.noreply.github.com`) and use commandline to push instead.

**Comment by fhemberger** [comment]
@jbergstroem Thanks, flag for "private email" was set on the web interface.

**Pull request closed without merging**
