### PR TITLE
ansible: update compiler selection for 10.x

### PR DESCRIPTION
**Pull request by mhdawson**
- add compiler selection for AIX
- add use of newer binutils for PPC
- change path to get newer binutils for s390

### CODE REVIEW

**Comment by mhdawson** [comment]
@gibfahn can you take a look

**Comment by rvagg** [comment]
@mhdawson would you mind updating this so it'll do the binutils path update for any ubuntu1404 and debian8 please?

I updated all intel ubuntu1404 with the change as per https://github.com/nodejs/build/pull/1235#issuecomment-382281479

I've just done debian8 as per https://github.com/nodejs/build/pull/1242

Let me know if you have trouble making it generic and just merge this and I'll give it a go.

**Comment by mhdawson** [comment]
@rvagg looking again I think I'd like to land and then give it an update.  Can I get your LGTM?

**Comment by mhdawson** [comment]
@rvagg I see you said to go ahead and merge above, will take that as approval.

**Comment by mhdawson** [comment]
Landed as 5c9ab90ea4986e266b8bef5a6f8468b1558801cc

**Pull request closed without merging**
