### PR TITLE
jenkins: no debian8-x86 for node 10

### PR DESCRIPTION
**Pull request by refack**
Fixes: https://github.com/nodejs/build/issues/1290

### CODE REVIEW

**Comment by joaocgreis** [comment]
I don't see a `debian8-x86` machine in ci-release, so why is this needed?

Perhaps cc @rvagg

**Comment by rvagg** [comment]
yeah, this isn't going to have an impact as there isn't a machine of this type on ci-release (at least there shouldn't be!). Was this intended for `anyType` so it runs on ci?

**Comment by refack** [comment]
> Was this intended for anyType so it runs on ci?

Probably.

**Comment by refack** [comment]
@nodejs/build PTAL.
Since this is in alignment with previous decisions, if there are no objections I'm planning on landing this.

**Comment by refack** [comment]
https://ci.nodejs.org/job/node-test-commit-linux/20645/console:
```
...
16:29:38 Skipping centos5-64 for Node.js 10
16:29:38 Skipping debian8-x86 for Node.js 10
16:29:38 Skipping ubuntu1204-64 for Node.js 10
...
```

**Pull request merged**
