### PR TITLE
jenkins: fix coverage gcovr patches

### PR DESCRIPTION
**Pull request by killagu**
Refs: https://github.com/nodejs/node/issues/18938

### CODE REVIEW

**Comment by targos** [comment]
LGTM if it works

**Comment by mhdawson** [comment]
I'll try to test this out later today.

**Comment by mhdawson** [comment]
Generated coverage successfully.  @killagu many thanks for putting together the 2 PRs to fix this, landing

**Comment by mhdawson** [comment]
Landed as f577cb839256410d709713216df46fe580df2f98

**Comment by killagu** [comment]
🎉🎉🎉

**Pull request closed without merging**
