### PR TITLE
inventory: add test-digitalocean-ubuntu1604-x86-1

### PR DESCRIPTION
**Pull request by gibfahn**
Was going to push directly to master, but thought I'd raise a PR in case there are any others.

Would be good to have something that polled the Jenkins API and auto-filled the inventory.yml, maybe a nice project for someone.

### CODE REVIEW

**Comment by gibfahn** [comment]
I also noticed that [test-softlayer-ubuntu14-x86-1](https://ci.nodejs.org/computer/test-softlayer-ubuntu14-x86-1/) is misnamed (should be `1404` not `14`). I assume I should change the name in Jenkins rather than the inventory, thoughts?

**Comment by refack** [comment]
> I assume I should change the name in Jenkins rather than the inventory, thoughts?

According to the naming convention, I think rename in Jenkins
https://github.com/nodejs/build/blob/89e15bed2131366c1ea4d38370a69ec879b7f298/ansible/README.md#L94

**Comment by gibfahn** [comment]
Yeah, I'll rename tomorrow if no-one corrects me.

**Comment by joaocgreis** [comment]
About renaming: renaming in Jenkins would be the right thing to do, `ubuntu1404` is better than just `ubuntu14`. However, the workers use that name to connect, so you'll have to rename in the workers as well (looks like that worker was deployed before the ansible refactor, so you'll have to figure out where to rename - in this case is `/etc/init/jenkins.conf`). There are many others `ubuntu12/14`, feel free to rename however many, or just leave them.

**Pull request merged**
