### PR TITLE
doc: add Softlayer to list of Hardware Sponsors

### PR DESCRIPTION
**Pull request by mhdawson**
Add another line to identify IBM is also contributing
through Softlayer

Not sure if this is the best way but I would like to call out Softlayer and the OSU Open Source Lab separately.

### CODE REVIEW

**Comment by mhdawson** [comment]
@jbergstroem @rvagg

**Comment by jbergstroem** [comment]
LGTM, overdue :+1:

**Comment by rvagg** [comment]
aye, lgtm

we need to remove linaro and put something about ARM Holdings, also we're getting FreeBSD from somewhere new right @jbergstroem?

**Comment by jbergstroem** [comment]
@rvagg correct. lets add the freebsd stuff once its in.

**Comment by mhdawson** [comment]
Landed as 28a1a5e6062ea7b50139f652c1dbd8d83139612b

**Pull request closed without merging**
