### PR TITLE
ansible: replace DO debian8-x64-1 with debian11-x64-1

### PR DESCRIPTION
**Pull request by targos**
Refs: https://github.com/nodejs/build/issues/3499

### CODE REVIEW

**Comment by targos** [comment]
Agent connected: https://ci.nodejs.org/computer/test-digitalocean-debian11-x64-1/

**Comment by targos** [comment]
CI run on `main`: https://ci.nodejs.org/view/All/job/node-test-commit-linux-targos/1/nodes=debian11-64/

**Comment by targos** [comment]
Not sure why it failed. Retrying: https://ci.nodejs.org/view/All/job/node-test-commit-linux-targos/2/nodes=debian11-64/

**Comment by targos** [comment]
Again: https://ci.nodejs.org/view/All/job/node-test-commit-linux-targos/3/nodes=debian11-64/

**Comment by targos** [comment]
I'm upgrading the droplet to 4GB of memory instead of 2GB.

**Comment by targos** [comment]
Rerun with 4GB: https://ci.nodejs.org/view/All/job/node-test-commit-linux-targos/4/nodes=debian11-64/

**Review by MoLow — APPROVED** [review]
RSLGTM

**Comment by targos** [comment]
CI on v18.x (started by @richardlau) is green as well: https://ci.nodejs.org/view/All/job/node-test-commit-linux-targos/5/

**Review by richardlau — APPROVED** [review]

**Review by UlisesGascon — APPROVED** [review]

**Pull request merged**
