### PR TITLE
ansible: add requireio-osx1010-x64-1 to inventory

### PR DESCRIPTION
**Pull request by gibfahn**
Fixes: https://github.com/nodejs/build/issues/752

Not really sure why the user is `iojs` rather than root here, is that intended?

### CODE REVIEW

**Comment by rvagg** [comment]
yeah, the root account isn't active on that machine, we could fix it up but for now let's just leave it as is cause we're migrating to MacStadium anyway. There's a user account "rvagg" that has admin privs, if need be I could probably stick the test key in there too. For full admin though you really need remote desktop, which you could do via SSH tunnel but you then need a password to log in and do anything useful. We're going to have to figure out an answer for this problem, it'll probably mean assigning the same password to an admin account for all of the test OSX machines. /cc @jbergstroem @mhdawson 

@gibfahn while you're in here, could you add another entry in there, under `release`, same name, IP 192.168.2.211 please

**Comment by gibfahn** [comment]
>could you add another entry in there, under release, same name, IP 192.168.2.211 please

Done

**Comment by rvagg** [comment]
lgtm

**Comment by jbergstroem** [comment]
It might be worth mentioning that the create playbooks with fail now seeing how we don't have any support for macos builders. Hopefully this will not be the case any longer ni teh coming week or two, seeing how we now have a few machines up and running at macstadium we will fully ansible-fy (if possible).

**Pull request merged**
