### PR TITLE
github-bot: clone nodejs/node repository

### PR DESCRIPTION
**Pull request by phillipj**
These changes clones the nodejs/node repository required for the bot to automatically attempt backport of new PRs.

Refs https://github.com/nodejs/github-bot/pull/90

/cc @nodejs/github-bot

### CODE REVIEW

**Comment by Fishrock123** [comment]
cc @nodejs/build

**Comment by phillipj** [comment]
Thanks for reviewing! For some reason I'm struggling to get my local ansible test setup up-n-running, really want to figure out what's causing that and ofc do a test run locally before applying to any of our servers.

**Comment by phillipj** [comment]
@Fishrock123 too reduce the time spent cloning the node repo, I pushed a change fetching only the last revision. Cloning the whole repo history didn't seem necessary to me. From the [ansible docs](http://docs.ansible.com/ansible/git_module.html#options):

> Create a shallow clone with a history truncated to the specified number or revisions. The minimum possible value is 1, otherwise ignored.

You okey with that?

**Comment by Fishrock123** [comment]
@phillipj It needs access to any `vM.x-staging` staging branches currently in use. Technically it doesn't need `master`.

**Comment by jbergstroem** [comment]
By accessing staging stuff I reckon you'll be touching most of master. Might as well do a full checkout seeing how shallow clones will have issues traversing history.

**Comment by phillipj** [comment]
Thanks for your thoughts, decided to remove the shallow clone, and just clone the entire node repo.

This has been applied to the github-bot server in production.

**Pull request merged**
