### PR TITLE
www: enable fallback for Japanese locale

### PR DESCRIPTION
**Pull request by phillipj**
Japanese has been added to nodejs.org, these changes enabled the english fallback for pages the translation WG hasn't translated yet.

Refs: https://github.com/nodejs/nodejs.org/pull/900

### CODE REVIEW

**Comment by jbergstroem** [comment]
LGTM

**Comment by watilde** [comment]
Thanks for the following up! LGTM😺

**Comment by phillipj** [comment]
@jbergstroem you got the time to run this in production?

**Comment by jbergstroem** [comment]
> @phillipj said:
> @jbergstroem you got the time to run this in production?

Done.

**Pull request merged**
