### PR TITLE
ansible: fix and simply ccache version getter

### PR DESCRIPTION
**Pull request by maclover7**
@rvagg This was what I meant in #1277 -- for some reason the awk script doesn't work on my Mac, and this will help to simplify what we're actually trying to do here

### CODE REVIEW

**Comment by LucaLanziani** [comment]
One issue I can see with this, if I'm reading the code correctly, is that we are assuming that the moment the tag is in GitHub the tar.gz is already in the "samba ftp" endpoint.

**Comment by refack** [comment]
How about splitting this to:
1. A script that fetches whatever version and stores it in a known location (e.g. www/downloads)
2. Ansible can always fetch from known location.

**Comment by LucaLanziani** [comment]
@refack would the script fetch the version on every run?

At the end I've decided to push my version too #1312 ;)

**Comment by rvagg** [comment]
oh, whoops, this must work for me because I have `coreutils` installed on my mac and they are the default executables so it's consistent between my mac and linux machines. +1 on whatever works.

**Comment by maclover7** [comment]
Closing in favor of #1312

**Pull request closed without merging**
