### PR TITLE
inv: decomission `infra-softlayer-ubuntu1404-x64-2`

### PR DESCRIPTION
**Pull request by AshCripps**
refs: https://github.com/nodejs/build/issues/2650

### CODE REVIEW

**Review by richardlau — APPROVED** [review]
Remind me to remove this from the secrets repo next week.

**Comment by AshCripps** [comment]
ive cancelled the machine in softlayer but it will still be around untill 2021/06/24 when the subscription is up

**Review by bl-ue — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by richardlau** [comment]
@AshCripps this host is also referenced in https://github.com/nodejs/build/blob/e93b5266cb0c622606c8f07adad2033531f3d404/ansible/playbooks/jenkins/worker/create.yml#L11 and should be removed from there as well.

**Review by richardlau — APPROVED** [review]

**Comment by AshCripps** [comment]
cancelling request finally went through - billing is cancelled and the machine will be reclaimed on 2021/07/24

**Comment by richardlau** [comment]
FYI I've deleted the agent from Jenkins, i.e. what was previously at https://ci.nodejs.org/computer/infra-softlayer-ubuntu1404-x64-2/ (now a 404).

**Pull request merged**
