### PR TITLE
added Ubuntu 15.04 config

### PR DESCRIPTION
**Pull request by rvagg**

### CODE REVIEW

**Comment by jbergstroem** [comment]
Perhaps add `ccache`?

**Comment by jbergstroem** [comment]
I can possibly provide an init script if you haven't got one already.

**Comment by rvagg** [comment]
systemd, I have one for something else, fedora perhaps .. or did I dump it in an issue here somewhere?

**Comment by jbergstroem** [comment]
Probably this no? https://github.com/nodejs/build/blob/master/setup/fedora21/resources/jenkins.service

**Comment by rvagg** [comment]
ah yes, but actually, this is probably closer to Ubuntu: https://github.com/nodejs/build/tree/master/setup/debian8

**Pull request closed without merging**
