### PR TITLE
build: extend timeout for git for AIX

### PR DESCRIPTION
**Pull request by mhdawson**
We were seeing timeouts in git checkouts. Extended
the timeout through a parameter passed to the plugin
as a command line option when starting the jenkins
agent

Increased the memory available to the JVM in hopes
that might speed up actions like the checkout
which are being handled by a java plugin

Addresses https://github.com/nodejs/build/issues/381

### CODE REVIEW

**Comment by rvagg** [comment]
perhaps you should just include a bare git mirror like we do for arm machines, located in /home/iojs/git/io.js.reference, when a clone is done, any refs found in there will be linked straight to it and any not found in there are pulled from the remote. I occasionally update the mirror as upstream gets more bloated. The reference location is specified in the jenkins job setup under advanced git options, or something like that.

**Comment by jbergstroem** [comment]
I left my comment in the originating issue. I'd prefer the following triage:
1. Is `-mx256m` required to solve issues?
2. Can we test setting the timeout locally or even globally [still machine only] to confirm that's the actual issue?
3. What @rvagg said.

**Comment by mhdawson** [comment]
Doing 1) now https://ci.nodejs.org/job/node-test-commit-aix/120/ build without 12m

**Comment by mhdawson** [comment]
@rvagg which jobs uses the bare mirror ? I looked at https://ci.nodejs.org/job/node-test-commit-arm/ and I did find references to io.js.reference but maybe I just did not look hard enough.

**Comment by mhdawson** [comment]
Ok was fine without change to heap size so removed that.  Change pushed to pr.

**Comment by mhdawson** [comment]
Ok found this:https://randyfay.com/content/reference-cache-repositories-speed-clones-git-clone-reference

So looks like I create the mirror using

git clone --mirror  https://github.com/nodejs/node.git   /home/iojs/git/io.js.reference

And I also found that "Path of the reference repo to use during clone"  is already set

**Comment by rvagg** [comment]
bingo, and occasionally you can `git fetch` inside it to update it, but I suspect that won't be needed for a while in this case

**Comment by mhdawson** [comment]
I added the mirror but the total execution did not seem to be any faster.  I'm thinking the problem may not be the remote traffic but slowness on the disk I/O.  At this point I think extending the timeout still makes sense.

**Comment by mhdawson** [comment]
@jbergstroem you ok with landing this now or was there something else I should try out first ?

**Comment by jbergstroem** [comment]
@mhdawson sure, LGTM

**Comment by mhdawson** [comment]
landed as c7e244bcc73b2dc373bab973ebd725255e487f4f

**Pull request closed without merging**
