### PR TITLE
[WIP]ansible: low hanging GCC-8 fruit

### PR DESCRIPTION
**Pull request by refack**
* CentOS7 - `devtoolset-8`
* Ubuntu - `gcc-8`

### CODE REVIEW

**Comment by rvagg** [comment]
with CentOS7 that'll have to be an opt-in at the Jenkins level, for Ubuntu will that work across all our infra? Do we have the toolchain ppa setup by default? And then, when enabled it'll switch to GCC 8 by default and that'll begin removing testing of older GCC, are we OK with that?

**Comment by refack** [comment]
> with CentOS7 that'll have to be an opt-in at the Jenkins level, for Ubuntu will that work across all our infra? Do we have the toolchain ppa setup by default? And then, when enabled it'll switch to GCC 8 by default and that'll begin removing testing of older GCC, are we OK with that?

Optimally they should live SxS, so I'd like to set up select-compiler-per-node-version for Ubuntu as well.

(for CentOS we already have an if-elif for devtoolset-6)
image

**Comment by rvagg** [comment]
ok, so this is blocked until we have something in place to do side-by-side? and `apt-get install gcc gcc-8` is that going to install gcc-8 only or both gcc-8 and the default gcc? I have a feeling that since gcc-8 "provides" gcc that we'll only get 8, so it won't be side-by side unless we specify the version for each ubuntu.

**Comment by refack** [comment]
> ok, so this is blocked until we have something in place to do side-by-side?

Ack.

> and `apt-get install gcc gcc-8` is that going to install gcc-8 only or both gcc-8 and the default gcc?

As far as I've tested (16.04 and 18.04), both, since `gcc` is hard-aliased to a specific version:
https://packages.ubuntu.com/xenial/gcc
https://packages.ubuntu.com/disco/gcc

**Comment by sam-github** [comment]
Stale.

**Pull request closed without merging**
