### PR TITLE
add release-macstadium-macos10.11-x64-1

### PR DESCRIPTION
**Pull request by gdams**
FYI @mhdawson this machine currently has the test keys on in rather than release so this will need changing. I had to fixup a few bugs in the playbook but this has now been run on the machine so it should be good to add to ci-release.

### CODE REVIEW

**Comment by mhdawson** [comment]
Enabled OSX 11 and 12 in the test CI so we get coverage in advance: https://ci.nodejs.org/view/All/job/libuv-test-commit-osx/

**Comment by mhdawson** [comment]
Accidentally added the libuv job instead of node one. Interestingly there were failures on OSX 12.

Added to main node test job here: https://ci.nodejs.org/view/All/job/node-test-commit-osx

**Comment by maclover7** [comment]
Two quick questions:
- Can you run the updated playbook on one or two macOS machines in the test cluster, just to make sure everything's ok there
- Do we have any docs about how to add/remove MacStadium macOS machines?

**Comment by mhdawson** [comment]
There is some doc in the private infra doc, but most of it does not need to be there, its just there because its were we put the brain dump along with the secrets.   

We should pull out the no-private parts to a public doc.

**Comment by targos** [comment]
What is blocking this?

**Comment by rvagg** [comment]
I believe we're ready to make this happen. Michael produced a test build https://nodejs.org/download/test/v11.0.0-test8ac916309b/ that I've been all over and it all looks good so I think it might be just a matter of wiring it up to take over master/11+ builds.

@mhdawson @gdams let me know if you'd like me to hop in and help get this connected up.

**Comment by mhdawson** [comment]
The machine is ready, but when I was testing out changes to the selector script in https://github.com/nodejs/build/pull/1409/commits/33c659f42a71a44babcf42f7611a7082dec0aa52, they were not working in the test infra.  

@refack I think from the discussion in 1409 you found/fixed the problem in the test infra but I'm not 100% sure so can you confirm?

**Comment by refack** [comment]
> @refack I think from the discussion in 1409 you found/fixed the problem in the test infra but I'm not 100% sure so can you confirm?

Tests have been working. I run a test release for the v10 line and it worked. v11 issue tracked in https://github.com/nodejs/build/issues/1415

**Comment by mhdawson** [comment]
@refack thanks I assume it was this part which fixed the test infra?

`For posterity: when enabling VersionSelectorScript.groovy also need to enable the NodeVersionExtension SCM plugin with exportNodejsVersion checked.`

**Comment by refack** [comment]
> I assume it was this part which fixed the test infra?

Probably (I figured that out a week ago while playing with other "beta" jobs).

**Comment by mhdawson** [comment]
Just added osx11 to the main release job.  I `think` I have everything I had changed in my testing job.

**Comment by mhdawson** [comment]
test job https://ci-release.nodejs.org/job/iojs+release/3609/

**Comment by refack** [comment]
No headers in 2018-07-31 nightlies. I think there was a typo in the job config.
Now testing this fix
https://ci-release.nodejs.org/job/iojs+release/jobConfigHistory/showDiffFiles?timestamp1=2018-07-30_16-25-59&timestamp2=2018-07-31_07-58-29
in job https://ci-release.nodejs.org/job/iojs+release/3615/

**Comment by refack** [comment]
Headers were built:
https://nodejs.org/download/nightly/v11.0.0-nightly20180731be322bd9ad

**Comment by refack** [comment]
Today's nightly failed because of https://github.com/nodejs/node/issues/22006 so I changed `make` arguments (for osx) to `-j 1`
https://ci-release.nodejs.org/job/iojs+release/jobConfigHistory/showDiffFiles?timestamp1=2018-07-31_07-58-29&timestamp2=2018-08-01_07-49-13

Nightly test - https://ci-release.nodejs.org/job/iojs+release/3619/parameters/
10.x test - https://ci-release.nodejs.org/job/iojs+release/3620/parameters/
8.x test - https://ci-release.nodejs.org/job/iojs+release/3621/parameters/
6.x test - https://ci-release.nodejs.org/job/iojs+release/3622/parameters/

**Comment by mhdawson** [comment]
This should not have affected 10, 8 or 6 since they still use the old OSX machine and don't have V8 6.8.  But still good to validate that things are ok :)

**Comment by MylesBorins** [comment]
is this good to go?

can we land https://github.com/nodejs/node/pull/21668?

**Comment by refack** [comment]
> is this good to go?

Yes, as far as can be tested.
Actualy with https://github.com/nodejs/node/pull/21668/commits/0b3f44c5346a5320edf5878a7667aa1f67773275 there should be no problems even with macOS 10.10 as seen in the [PR's CI](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1010/20217/)

**Comment by mhdawson** [comment]
@gdams I think you can land this.

**Pull request merged**
