### PR TITLE
Request to join the build WG

### PR DESCRIPTION
**Pull request by joyeecheung**
Hi all, I have been asking for help a lot on the build IRC lately (regarding benchmark CI configurations and core CI jobs). Had a chat with @refack and I was suggested to join the working group. I'd love to get more involved.

cc @nodejs/build

### CODE REVIEW

**Comment by refack** [comment]
🎉 👏

**Comment by gibfahn** [comment]
+1 on this landing, but @joyeecheung if you'd like to work on anything in the mean time, please let us know.

**Comment by joyeecheung** [comment]
@gibfahn  I am thinking about the continuation of https://github.com/nodejs/build/issues/887 , a CI job for `make lint` and doc tests? (see https://github.com/nodejs/node/pull/16208#issuecomment-337581773). I will open a issue for that.

**Comment by gibfahn** [comment]
@nodejs/build If there are no objections I think we should consider this settled. Does anyone have time to do an onboarding for @joyeecheung ? We might be able to combine it with one for @maclover7 (https://github.com/nodejs/build/pull/928).

I'd like to help out with the onboarding, but not comfortable leading it.

**Comment by refack** [comment]
I'd also love to help with onboarding (also don't mind leading if no one else is available)

**Comment by joyeecheung** [comment]
Rebased.

@refack @gibfahn I'd be happy to get onboard with @maclover7 if we can find a time that works for all of us.

**Comment by joaocgreis** [comment]
I can also join if you'd like me to, but my availability isn't so great at the moment so feel free to go ahead @gibfahn @refack . Ping me to add to the build team in the day before or so.

Welcome @joyeecheung and @maclover7 !

**Pull request merged**
