### PR TITLE
doc: add myself to release admins

### PR DESCRIPTION
**Pull request by mhdawson**
Update to reflect reality

### CODE REVIEW

**Comment by rvagg** [comment]
`ncu-team sync` does this automatically doesn't it? maybe run that to see that it all reflects reality.

**Comment by richardlau** [comment]
> 
> 
> `ncu-team sync` does this automatically doesn't it? maybe run that to see that it all reflects reality.

It syncs to groups and we don't, AFAICT, have a GitHub group for release admins.

Current mapping (https://github.com/nodejs/build/pull/2018) is:
nodejs/build-infra ➡️ Infra Admins
nodejs/jenkins-admins ➡️ Jenkins Admins
nodejs/jenkins-release-admins ➡️ Release Jenkins Admins

**Comment by nschonni** [comment]
Should the `ncu-team sync` be run as Jenkins scheduled job or a Travis cron job?

**Comment by mhdawson** [comment]
@rvagg what you suggest makes sense but it more than I was trying to sign up for here...

**Pull request merged**
