### PR TITLE
doc: add maclover7 to github bot admin list

### PR DESCRIPTION
**Pull request by maclover7**
Been doing a bunch of work on the bot related to pull request status
lights, and would be helpful to have elevated permissions. For example,
Ansible permissions were needed to roll out
https://github.com/nodejs/build/pull/1054.

cc @phillipj

### CODE REVIEW

**Comment by maclover7** [comment]
@joyeecheung Just tried running `dotgpg add` with my PGP public key in `build/github-bot`, and got this:

```
-----END PGP PUBLIC KEY BLOCK-----Adding Jon Moss to /Users/jon/code/nodejs/secrets/build/github-bot
  .gpg/me@jonathanmoss.me
/Users/jon/code/nodejs/secrets/build/github-bot/deployment_secrets.md: Decryption failed
/Users/jon/code/nodejs/secrets/build/github-bot/github_bot_account.md: Decryption failed
```

I _think_ the issue is that someone who already has access needs to run the command. Still trying to read the docs.

**Comment by rvagg** [comment]
yeah, that's correct, you can't do it yourself and there's not even a way you can request it other than in writing. It'd be best if someone active in that group does it too so @joyeecheung since you're approving this PR how about you go and add @maclover7 to the secrets too? Feel free to just commit and push to that repo, no need to PR it.

**Comment by joyeecheung** [comment]
@rvagg I've added @maclover7 to the secrets (BTW I've forced pushed right after my first push to reset the misconfigured author, let me know if I've stepped on anyone's toes although I doubt that).

**Comment by phillipj** [comment]
LGTM!

For future ref, rolling out to production is usually done by merging changes to [nodejs/github-bot](https://github.com/nodejs/github-bot) master branch which automagically kicks off its [re-deployment script](https://github.com/nodejs/build/blob/master/setup/github-bot/resources/deploy-github-bot.sh).

**Comment by maclover7** [comment]
@joyeecheung @phillipj Can confirm secrets are working good. Would you be able to add me to the nodejs/github-bot team as well?

**Comment by joyeecheung** [comment]
@maclover7 Sure, I've added you to the team.

**Pull request merged**
