### PR TITLE
install latest version of git

### PR DESCRIPTION
**Pull request by rvagg**
This is for @fishrock123 who is trying to get a rebase task working and we're seeing if it's an older version of git that's the problem. May as well got for the latest version.

### CODE REVIEW

**Comment by gibfahn** [comment]
@rvagg I assume this can be closed now, reopen or retarget to `ansible/` if not.

**Comment by rvagg** [comment]
eh, no not really, there's still things that use the old ansible scripts, retargetting is going to require fully reimplementing the github-bot scripts and I'm not really up for that, I barely have a grip on how the new ansible stuff works

**Comment by gibfahn** [comment]
@rvagg okay, so maybe just land this?

**Comment by rvagg** [comment]
yeah, I guess so!

**Pull request merged**
