### PR TITLE
jenkins: send statuses for non-nodejs/node repos

### PR DESCRIPTION
**Pull request by maclover7**
Related #922. At some point, the CITGM builds can be updated to use this as well.

### CODE REVIEW

**Comment by refack** [comment]
And `node-gyp` (which I just noticed today don't receive statuses).
We'll need to do some changes in the bot for `libuv` to receive these as well.

**Comment by gibfahn** [comment]
> We'll need to do some changes in the bot for libuv to receive these as well.

If we're going to do libuv, we'd probably need to add an `org` parameter to this PR (or change `REPO` to accept `nodejs/node`. But I assume that'd require changes to `github-bot` as well.

**Comment by refack** [comment]
> But I assume that'd require changes to github-bot as well.

1. Need to verify the bot has permissions to the `libuv` org.
2. We could do a simpler hack in the bot so that `libuv` == `libuv/libuv`

**Comment by maclover7** [comment]
Going to land this for now-- as this job continues to be used by others, we can keep making changes as necessary :)

**Comment by maclover7** [comment]
Landed in 6b050dc70bd4aa4e7914f694927ef01b7b1d48a9

**Pull request closed without merging**
