### PR TITLE
Created a small working with Ansible guide

### PR DESCRIPTION
**Pull request by phillipj**
As briefly mentioned in the last WG meeting, while working in the github-bot setup, I got a local Vagrant setup working for running playbooks against. I thought that was really valuable when trying to learn Ansible basics, and it made it trivial to start from scratch after having tested a lot of different approaches.

Any feedback would be more than welcome!

### CODE REVIEW

**Comment by jbergstroem** [comment]
This is awesome. Will check soon!

**Comment by phillipj** [comment]
Not sure how / where to mention the required vars from the secrets repo tho

**Comment by jbergstroem** [comment]
That's fine, we can add that somewhere else.

**Comment by mhdawson** [comment]
My first thought after reading was that we might want to split into 2 docs.  The first which has the links and general information which would go in the readme.md under setup and then a separate one with the specific example of how to do it with Vagrant.  This might avoid any confusion about Vagrant being used/required.

**Comment by jbergstroem** [comment]
I'm more interested in the Vagrant guide seeing how that will make more people able to test the playbooks! I have a 'general' ansible guide (at least in terms of using it) at my branch: https://github.com/jbergstroem/build/tree/feature/refactor-the-world/ansible#ansible-scripts-for-the-nodejs-build-group-infrastructure

**Comment by phillipj** [comment]
Thanks for reviewing, sorry about the late reply!

In an attempt to make this guide more Vagrant related, I removed what could be seen as an intro to ansible and the use of ansible in the project.

PTAL

**Comment by mhdawson** [comment]
I think the content looks good now, but should probably be named something other than README.md.  I'm thinking the README.md for the setup directory should be an overview and point to docs like the "general" ansible guide and this one about testing locally.

**Comment by jbergstroem** [comment]
I'm with @mhdawson -- let's reference it from README.

**Comment by phillipj** [comment]
I won't push the merge button yet, as there hasn't been a clear LGTM from anyone yet, tho feedback has been positive and there's no outstanding issues afaik.

**Pull request merged**
