### PR TITLE
Fix nginx logrotate script for www

### PR DESCRIPTION
**Pull request by rvagg**
fixes https://github.com/nodejs/build/issues/550

### CODE REVIEW

**Comment by rvagg** [comment]
apparently logrotate doesn't support globs ... so there you go

**Comment by jbergstroem** [comment]
Wow. I've been "using" globs for I don't know how long..

**Comment by rvagg** [comment]
perhaps it was the commas? or perhaps this is a linux thing and you're just used to some dodgy *bsd hack

**Comment by jbergstroem** [comment]
Ah, I think it was the commas. Was just baffled by the fact that it might have been broken and I've never noticed on my servers either.

**Pull request merged**
