### PR TITLE
ansible: remove firewalld on centos and fedora

### PR DESCRIPTION
**Pull request by santigimeno**
So it doesn't interfere with multicast tests.

Refs: https://github.com/libuv/libuv/pull/2185

### CODE REVIEW

**Comment by santigimeno** [comment]
Any estimate when this could be included. It'll be great in order to have a greener libuv ci. Thanks!

**Comment by mhdawson** [comment]
@santigimeno the challenge is that even once it lands it will only take effect once somebody runs it on all of the relevant machines.  That I believe is a multi-hour job....

**Comment by rvagg** [comment]
yes, sorry, this is near the top of my TODO list, haven't lost track of it, just need a bit of time to execute it with a clear head

**Comment by santigimeno** [comment]
Ok. Thanks for the prompt response.

**Comment by vtjnash** [comment]
Do you mind if I bump this?

**Comment by rvagg** [comment]
don't mind at all, this had slipped low in my list! ... which is getting a bit out of hand again so I probably should dedicate a day or two to clearing my backlog. Will try and get to this soon.

**Comment by rvagg** [comment]
with https://github.com/nodejs-private/secrets/pull/52 & https://github.com/nodejs/build/pull/1977 this will be final, I merged this particular commit in 821de09 but it needed the additional cleanup in #1977 to run. It's been run against the fedora and centos hosts now and it appears to be working, see #1971

**Comment by santigimeno** [comment]
Thanks!

**Pull request closed without merging**
