### PR TITLE
Redirect iojs.org to nodejs.org

### PR DESCRIPTION
**Pull request by fhemberger**
Using full domain redirects, because the little amount of traffic still pointing
to iojs.org probably doesn't justify full url mapping redirects.

Ref: https://github.com/nodejs/iojs.org/issues/432

Open issues:

- [ ] Remove DNS entry for roadmap.iojs.org  
  (linking to https://github.com/nodejs/roadmap/tree/gh-pages)
- [ ] `*.iojs.org` also resolves to GitHub pages
- [ ] What should happen with `https://iojs.org/dist/`?
Drop it entirely? Integrate it somehow into `https://nodejs.org/dist/`?
- [ ] What about tools like `nvm` or `n`, which still point to `dist`?

### CODE REVIEW

**Comment by fhemberger** [comment]
What should happen with `https://iojs.org/dist/`?
Drop it entirely? Integrate it somehow into `https://nodejs.org/dist/`?

**Comment by fhemberger** [comment]
@Trott Any thoughts about the open questions? Should we just ditch all iojs downloads completely (while we still keep stuff like Node.js 0.1.10 around)?
How will this affect 3rd-party-tools?

**Comment by Trott** [comment]
> @Trott Any thoughts about the open questions? Should we just ditch all iojs downloads completely (while we still keep stuff like Node.js 0.1.10 around)?
How will this affect 3rd-party-tools?

/ping @nodejs/version-management

**Comment by refack** [comment]
> For nvm to work properly, it needs nodejs.org/dist to _not_ contain io.js versions, and iojs.org/dist to _only_ contain io.js versions.

What I meant by integrating, is that we do just that, i.e. keep:
```yaml
    location /dist {	
        alias /home/dist/iojs/release/;	
        autoindex on;	
        default_type text/plain;	
         location ~ \.json$ {	
            add_header access-control-allow-origin *;	
        }	
    }	
```

**Comment by ljharb** [comment]
As long as all the same versions are accessible, and show up in distinct lists depending on the domain requested, everything will continue to work.

**Comment by fhemberger** [comment]
Updated the PR to keep all `location` directives in place. PTAL.

**Comment by rvagg** [comment]
I'm not sure the config matches the discussion here. Can we be more precise with what we're trying to achieve given the above discussion?

As far as the website is concerned, it's very simple and only has localisation directories plus an /images. Nothing deeper than that.

We also have locations that point to distributables, they are: /dist, /download, /api, and /docs.

My suggestion would be to redirect everything but those distributables, leaving them intact. Each of them lets you access specific versions and there's probably links out there on the web to them and people using weird versions that it might not be worth disrupting.

Use of assets in /images might also be a concern. We've tried really hard to not break historical links on nodejs.org since we started the Foundation, maybe that should extend here too?

Aside from the question of /images. If the redirect goes only in `location /`, the rest could stay intact.

FYI here's the DNS records for iojs.org, and also we actively use @iojs.org for emails.

iojs_dns

**Comment by fhemberger** [comment]
@rvagg Ok, so basically leave everything as it is (redirect http+www -> https, etc.) and only redirect `/` (as more specific location paths still have a higher rank).

I updated the PR accordingly, PTAL.

Removing the `*` CNAME record should also be fine to remove `roadmap.iojs.org` as well (added redirect in nginx config).

**Comment by rvagg** [comment]
I think this looks good. Thankfully iojs.org isn't critical in the same way as nodejs.org so I'll be able to deploy and test it out. Our SSL cert expires this week so I'll need to sort that out too, either cloudflare or letsencrypt.

**Comment by rvagg** [comment]
switched to letsencrypt on iojs.org

**Comment by rvagg** [comment]
All done, landed in 7a7e700c, I reworked some of the config to make nginx work and also activate ipv6 on some of the `server` stanzas (letsencrypt verifies via AAAA records when they exist).

Some letsencrypt config details for this added to https://github.com/nodejs/build/pull/1552

**Comment by rvagg** [comment]
and I removed the `*` -> gh-pages DNS record and put `roadmap.iojs.org` as a CNAME for `iojs.org` so the redirect works there too.

**Pull request closed without merging**
