### PR TITLE
jenkins: use /bin/sh syntax in select-compiler.sh

### PR DESCRIPTION
**Pull request by sam-github**
Fixes: https://github.com/nodejs/build/issues/1992

### CODE REVIEW

**Comment by sam-github** [comment]
I reproduced the original syntax error with /bin/dash on Linux, and this fixes it (and uses the same case syntax as the rest of the file). I'm in process of trying to repro and proves this fixes it on actual AIX.

**Comment by sam-github** [comment]
I verified that the original could not be sourced on AIX, and that this can be after conversion to case statements.

@nodejs/build can I fasttrack this onto master?

**Comment by mhdawson** [comment]
+1 to fasttrack since I think AIX Is currently broken.

**Comment by sam-github** [comment]
https://ci.nodejs.org/job/node-test-commit/32083/

^-- kicked off a test run on master to confirm nothing was broken by this

**Comment by richardlau** [comment]
Belated LGTM.

**Pull request merged**
