### PR TITLE
chore: upgrade github actions

### PR DESCRIPTION
**Pull request by UlisesGascon**
### Main changes
- Upgraded: `actions/setup-python@v1` -> `actions/setup-python@v4`
- Upgraded `actions/checkout@v2` -> `actions/checkout@v3`

### Context

- https://github.com/nodejs/build/pull/3086#issuecomment-1323683587

### CODE REVIEW

**Review by richardlau — APPROVED** [review]

**Review by targos — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by AshCripps — APPROVED** [review]

**Comment by nschonni** [comment]
May be worth adding the Dependabot for the GitHub Actions to keep them in sync going forward https://github.com/nodejs/nodejs.org/blob/15742f7ca350e1862ee1ebcc9e54515683763499/.github/dependabot.yml#LL3C10-L3C10

**Comment by UlisesGascon** [comment]
Seems like a good idea @nschonni. Do you want to create a PR for that? 👍

**Comment by nschonni** [comment]
> Seems like a good idea @nschonni. Do you want to create a PR for that? 👍

Sure, created https://github.com/nodejs/build/pull/3094

**Pull request merged**
