### PR TITLE
doc: add phillipj to the team

### PR DESCRIPTION
**Pull request by phillipj**
Rumours has it I'm welcome to join the team?

### CODE REVIEW

**Comment by joaocgreis** [comment]
LGTM, welcome!

**Comment by jbergstroem** [comment]
LGTM

**Comment by mhdawson** [comment]
LGTM

**Comment by Starefossen** [comment]
LGTM 😄

**Comment by mhdawson** [comment]
Landed as f4fff5eda3513c287b47e91c5e769dfc58fef45e

**Comment by Starefossen** [comment]
✨🎉✨

**Comment by jbergstroem** [comment]
@mhdawson fyi - I just force pushed; changed the `oe` in my last name to `ö`. I usually don't care but since I copy paste from `git log` I reckon others likely does too :)

**Pull request closed without merging**
