### PR TITLE
meta: add anonrig to build

### PR DESCRIPTION
**Pull request by anonrig**
After talking to several TSC members, I'm opening this self-nomination pull request:

I am interested in joining the Build WG to help with the current effort of understanding the infrastructure that's causing issues with our current setup. I'm also interested in getting familiar with our CI and solving outages and help improving them.

cc @MoLow @richardlau

### CODE REVIEW

**Comment by UlisesGascon** [comment]
Big +1 from me.

**Comment by Trott** [comment]
@nodejs/build Is there anything that @anonrig or someone else should do to get this moving forward? Does anything need to happen before [onboarding](https://github.com/nodejs/build/blob/main/ONBOARDING.md) can begin?

**Comment by MoLow** [comment]
I think we can continue with onboarding (some other issues on https://github.com/nodejs/build/labels/build-agenda can probably also be handled since its been a long time since last meeting)

**Comment by anonrig** [comment]
Hey @MoLow, would you mind starting the onboarding to get the ball rolling?

**Comment by mhdawson** [comment]
@MoLow if possible I'd like to be in the onboarding session when you do it with @anonrig

**Comment by MoLow** [comment]
I don't think I have all the context yet to perform an onboarding, so definitely someone else would need to leed it

**Comment by UlisesGascon** [comment]
> I don't think I have all the context yet to perform an onboarding, so definitely someone else would need to leed it

I can lead it, no problem at all. I can include you also @mhdawson 👍.

**Review by MoLow — APPROVED** [review]

**Review by UlisesGascon — APPROVED** [review]
Welcome!

**Pull request merged**
