### PR TITLE
alpine: remove Alpine 3.9, add 3.11

### PR DESCRIPTION
**Pull request by rvagg**
Haven't actually done anything with this beyond messing with the files, so just a heads-up for now (and invitation if someone else wants to do this, @richardlau?). I don't even know if these will build properly, but the last couple of versions of Alpine have been stable enough that we haven't had to change anything so I'm hopeful.

Next steps:

 * [x] (optional) Test that these actually build. locally, tweak accordingly
 * [x] Change tags of the 3.10 containers in Jenkins to "alpine-last-latest"
 * [x] Set up 3.11 containers in Jenkins, tagging them "alpine-latest"
 * [x] Delete 3.9 Jenkins nodes  (I think what I'd do is just rename the 3.9 Jenkins nodes to 3.11 and change the tags accordingly, they'd get new secrets in the process and wouldn't leave 3.9's connected as "alpine-last-latest" during testing).
 * [ ] Set up inventory.yml in secrets with the secrets for these new 3.11 hosts and remove the 3.9 hosts in the process.
 * [x] Run the playbook against the 3 docker hosts to set these containers up
 * [x] Run CI jobs against all supported release lines and master to make sure no surprises pop up with 3.11 (we've had a lot of surprises with new Alpine versions). If there are surprises, consider getting things marked as flaky or fixed before properly enabling 3.11 in CI (probably remove "alpine-latest" from the node-test-commit-linux job).
 * [x] Manually remove the 3.9 containers from the 3 Docker hosts:
   - Stop containers via systemd
   - Remove systemd unit, then run `systemctl daemon-reload`
   - Remove images (`docker rmi ...`)
   - Run `docker system prune -fa` to clean up dangling images.

### CODE REVIEW

**Comment by sam-github** [comment]
Converted to a draft, to test the new Github feature -- it works great! Also, because its a Draft, but feel free convert back anytime @rvagg.

**Comment by rvagg** [comment]
all good, and thanks for the reminder, maybe I should actually get this done!

**Comment by rvagg** [comment]
Ran playbook against all docker hosts. Had to fix up the joyent host because /var/lib/docker has filled up the root disk - moved it to /home/iojs which is the mounted large network disk. Relabelled all the Alpine hosts and am now running test builds before removing 3.9.

containered:

* `master` https://ci.nodejs.org/job/node-test-commit-linux-containered/19501/
* `v13.x` https://ci.nodejs.org/job/node-test-commit-linux-containered/19502/
* `v12.x` https://ci.nodejs.org/job/node-test-commit-linux-containered/19503/
* `v10.x` https://ci.nodejs.org/job/node-test-commit-linux-containered/19504/

alpine (all linux):

* `master` https://ci.nodejs.org/job/node-test-commit-linux/34272/
* `v13.x` https://ci.nodejs.org/job/node-test-commit-linux/34273/
* `v12.x` https://ci.nodejs.org/job/node-test-commit-linux/34274/
* `v10.x` https://ci.nodejs.org/job/node-test-commit-linux/34275/

**Comment by rvagg** [comment]
Alpine looks good, debug failed on master with a `collect2: fatal error: ld terminated with signal 9 [Killed]` which is a bit sus. https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1804_sharedlibs_debug_x64/19501/
I've removed the Alpine 3.9 containers from the 4 hosts, cleaned dangling docker images and rebooted all of them. Running master linux-containered again: https://ci.nodejs.org/job/node-test-commit-linux-containered/19505/

**Comment by rvagg** [comment]
https://ci.nodejs.org/job/node-test-commit-linux-containered/19505/nodes=ubuntu1804_sharedlibs_debug_x64/console successful debug build

I'm rebuilding all the images on the joyent machine but I'm going to call this done in the meantime.

**Pull request merged**
