### PR TITLE
ansible: upgrade armv7l containers to Debian 11

### PR DESCRIPTION
**Pull request by targos**
Refs: https://github.com/nodejs/build/issues/3499

### CODE REVIEW

**Review by richardlau — APPROVED** [review]

**Comment by targos** [comment]
Test build: https://ci.nodejs.org/view/All/job/node-test-commit-linux-targos/7/nodes=debian11-armv7l/

**Comment by richardlau** [comment]
> Why do we have "fanned" jobs for armv7l? Compiling directly in the container seems to work fine?

In the release CI the armv7l builds are cross compiled so the fanned jobs are more representative of what we release. If we want to change the release builds to compile natively on armv7l then we'd need to pick a Linux distro to use -- we use RHEL 8 elsewhere for Linux but there's is no armv7l support in RHEL (only arm64)).

**Comment by targos** [comment]
Ok I see. Is the test job I did enough to validate that it will (probably) work in cross-compiled tests?

**Comment by richardlau** [comment]
> Ok I see. Is the test job I did enough to validate that it will (probably) work in cross-compiled tests?

I think so... the only thing I cannot remember is whether we need to add the host key for the jenkins workspace machine that hosts the temporary binary git repository to `known_hosts`.

**Comment by targos** [comment]
> the only thing I cannot remember is whether we need to add the host key for the jenkins workspace machine that hosts the temporary binary git repository to `known_hosts`.

Fanned job passed, so I guess it's good?

**Pull request merged**
