### PR TITLE
ansible: add gcc 12 to Linux containers

### PR DESCRIPTION
**Pull request by richardlau**
Add gcc 12 to RHEL/UBI 8 and Ubuntu 20.04 containers.

Refs: https://github.com/nodejs/build/issues/3806
Refs: https://github.com/nodejs/build/pull/3846

FYI for the cross compiler container this only adds gcc 12 as a host compiler and we'll need a follow up if we want to have a gcc 12 cross compiler (which we've previously been building ourselves in https://github.com/rvagg/rpi-newer-crosstools.git).

---

Updated Docker hosts:
- [x] release-mnx-ubuntu2404_docker-x64-1
- [x] test-digitalocean-ubuntu2204_docker-x64-1
- [x] test-digitalocean-ubuntu2204_docker-x64-2
- [x] test-equinix-ubuntu2004_docker-arm64-1
- [x] test-equinix-ubuntu2004_docker-arm64-3
- [x] test-ibm-ubuntu2204_docker-x64-1
- [x] test-osuosl-ubuntu2004_docker-arm64-1

### CODE REVIEW

**Comment by richardlau** [comment]
Currently (slowly) applying to test-osuosl-ubuntu2004_docker-arm64-1.

**Comment by richardlau** [comment]
> Currently (slowly) applying to test-osuosl-ubuntu2004_docker-arm64-1.

This is still running, but I'll have to rerun to check because the CentOS 7 container failed to build -- I've now removed the CentOS 7 containers from the inventory (in secrets) and the template for it. 

I've also removed four versions of ICU (64, 64, 67 and 68) as the minimum version of Node.js we now build in the CI is Node.js 18 for which the minimum supported version of ICU is 69. The change was already made for the Ubuntu 24.04 containers as part of https://github.com/nodejs/build/pull/3758. This should speed up building the sharedlibs containers.

**Comment by targos** [comment]
Still LGTM

**Comment by richardlau** [comment]
ugh. `gcc-12` isn't available on Ubuntu 20.04. I suppose the easiest thing to do is update the arm containers from Ubuntu 20.04 to 22.04 (to match the x64 ones)?

**Comment by richardlau** [comment]
> ugh. `gcc-12` isn't available on Ubuntu 20.04. I suppose the easiest thing to do is update the arm containers from Ubuntu 20.04 to 22.04 (to match the x64 ones)?

I've updated all of the arm64 and armv7l Ubuntu containers from Ubuntu 20.04 to 22.04. We currently don't actually run any sharedlibs jobs on arm so for now I've dropped the sharedlibs containers in favor of more `ubuntu2204-arm64` containers.

I've updated the labels (e.g. `ubuntu2004-arm64` -> `ubuntu2204-arm64`) in:
- [node-test-binary-armv7l](https://ci.nodejs.org/job/node-test-binary-armv7l/)
- [node-test-commit-arm](https://ci.nodejs.org/job/node-test-commit-arm/)
- [node-test-commit-arm-debug](https://ci.nodejs.org/job/node-test-commit-arm-debug/)

**Comment by richardlau** [comment]
Upgrading to Ubuntu 22.04 means we now use gcc 11 by default (at least until we update select-compiler) and run into a change for armv7: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104455

e.g.
https://ci.nodejs.org/job/node-test-binary-armv7l/12973/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/console
```
03:02:21 cc1plus: error: '-mfloat-abi=hard': selected architecture lacks an FPU
```

I've appended `+fp` to `-march` in `CFLAGS` and `CXXFLAGS`: https://ci.nodejs.org/job/node-test-binary-armv7l/jobConfigHistory/showDiffFiles?timestamp1=2024-08-15_20-58-58&timestamp2=2024-08-15_22-17-30
which seems to fix this: https://ci.nodejs.org/job/node-test-binary-armv7l/12977/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/

**Comment by richardlau** [comment]
AFAICT the updated 

- [node-test-binary-armv7l](https://ci.nodejs.org/job/node-test-binary-armv7l/)
- [node-test-commit-arm](https://ci.nodejs.org/job/node-test-commit-arm/)
- [node-test-commit-arm-debug](https://ci.nodejs.org/job/node-test-commit-arm-debug/)

jobs are working on the updated containers.

**Review by targos — APPROVED** [review]

**Pull request merged**
