### PR TITLE
hello all, happy to join and help

### PR DESCRIPTION
**Pull request by refack**

### CODE REVIEW

**Comment by Trott** [comment]
I've been inactive forever, so if you want to remove my name while you're at it, feel free. Or not. Up to you and everyone on the Build WG I suppose.

**Comment by gibfahn** [comment]
+1

@Trott my feeling is that if it were easier for you to look after CI you would (because you use it a lot). If that's true I'd rather we make that easier than have you leave. Thoughts?

**Comment by rvagg** [comment]
+1 to having @refack join /cc @nodejs/build

**Comment by Trott** [comment]
@gibfahn So, yeah, I definitely use the access I was granted as part of the Build WG to do minor/simple fixes (like terminating stalled processes that are messing up CI, although that's less of an issue lately because of changes to the Makefile to improve things, but you get the idea).

I'm happy to stay on for that reason alone, but I have been inactive as far as actual WG stuff (attending meetings, paying close attention to the build issue tracker, doing build stuff beyond reporting problems in CI that I'm unable to fix).

It's the WG's decision as far as I'm concerned.

Let's table this and put it in another issue if it's something anyone wants to discuss further. Otherwise, I'll keep chugging along until I'm booted. :-D

+1 on @refack being added to this WG. He's been absurdly active and we need to get him on a WG or two to absorb some of his excess energy. :-D

**Comment by piccoloaiutante** [comment]
yes, +1 for @refack to join the group and @Trott to stay since you're still doing some job here 😃

**Comment by phillipj** [comment]
+1 for @refack

I've also been inactive the last few months, selling/buying a new house and other family related things, but I try to keep an eye on the bot at least.

**Comment by mhdawson** [comment]
+1 from me

**Comment by MylesBorins** [comment]
+1 from me

**Comment by jbergstroem** [comment]
+1 from me!

**Comment by Trott** [comment]
There's a Build WG onboarding process, right? Who can onbaord @refack? Is that @jbergstroem?

**Comment by joaocgreis** [comment]
+1 from me as well, and given the thread above I don't think this needs to wait for a meeting.

Count me in for the onboarding. @jbergstroem are you also available, same as last time? @refack are you in EDT? If so, any time during your daytime should be good for me.

**Comment by refack** [comment]
> Count me in for the onboarding. @jbergstroem are you also available, same as last time? @refack are you in EDT? If so, any time during your daytime should be good for me.

Yep I'm EDT. Will ping you on IRC.

**Comment by joaocgreis** [comment]
Anyone else wants to join the onboarding? We're planning for monday morning, let us know until then if you want to join.

**Comment by gibfahn** [comment]
I'd like to join, what time you planning?

**Comment by joaocgreis** [comment]
@gibfahn 1pm UTC / 2pm BST. Does that work for you? I'll email you the hangouts link before (or IRC if you're there).

**Comment by gibfahn** [comment]
@joaocgreis sounds great.

Could you just put the hangouts link in this thread?

**Comment by refack** [comment]
I've invited you both to a calendar meeting.

**Comment by joaocgreis** [comment]
@gibfahn @refack I'm on the google calendar meeting @refack has sent.

**Comment by Trott** [comment]
> @refack is now onboard! @rvagg @jbergstroem @mhdawson can one of you please add him to https://github.com/orgs/nodejs/teams/build/members ?

Done.

**Comment by gibfahn** [comment]
@refack do you want to land this?

Squash and merge is fine in this repo.

**Comment by rvagg** [comment]
Welcome onboard @refack! Hit me up on IRC if you have trouble accessing the ARM cluster, it's a bit more awkward than most of the other hosts and I don't know how much of this was covered in the on-boarding.

**Pull request merged**
