### PR TITLE
Update path to style sheet for coverage.nodejs.org

### PR DESCRIPTION
**Pull request by richardlau**
Fixes; https://github.com/nodejs/build/issues/1932
Refs: https://github.com/nodejs/nodejs.org/pull/2544

### CODE REVIEW

**Comment by XhmikosR** [comment]
Thanks for the fix @richardlau. And sorry for this regression, we should probably include more people from build in the website PRs...

**Comment by XhmikosR** [comment]
If the file is linked from many other sites can I suggest that we redirect the `/layouts/css/styles.css` temporarily until we've updated all the instances?

**Comment by Trott** [comment]
Because this change is tiny, easy to revert, extremely low risk, has multiple approvals, and fixes an irksome (but hardly critical) issue, I'm going to land it now.

**Comment by Trott** [comment]
Thanks, @richardlau! As always, you're awesome!

**Pull request merged**
