### PR TITLE
meta: add MoLow to test

### PR DESCRIPTION
**Pull request by MoLow**
I am interested to join the Build WG, for the purpose of eventually getting familiar enough with the infrastructure so that I can help handle issues.
CC @richardlau

### CODE REVIEW

**Comment by mhdawson** [comment]
+1 from me.

I've talked to another TSC member who is confortable with adding @MoLow based on his contributions. That same TSC member also reached out to a long time Node.js contributor that I also trust who confirmed he would be a good build team member.  

With that I'm +1 to adding @MoLow

**Review by mhdawson — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]
+1

**Review by richardlau — APPROVED** [review]

**Review by targos — APPROVED** [review]

**Comment by sxa** [comment]
Discussed at build meeting. Next step will be to schedule an onboarding session

**Comment by MoLow** [comment]
@nodejs/build what would be the next steps?

**Comment by mhdawson** [comment]
@MoLow we need a volunteer to onboard you.  I'm hoping somebody else volunteers but nobody does I'll see if I can find a time next week.

**Comment by targos** [comment]
I was never really onboarded, so would be interested to join the session.

**Comment by mhdawson** [comment]
I'm on holiday for the next week and a half but maybe it makes sense to set a time.  I may not be the best person to onboard, but I'll do my best :)

Does March 22 at 11 ET work for you two?

**Comment by MoLow** [comment]
you mean 11 am right?
https://www.worldtimebuddy.com/?qm=1&lid=5,281184,294117&h=5&date=2023-3-22&sln=11-12&hf=1
if so that works for me

**Comment by mhdawson** [comment]
@MoLow in advance can you complete the steps outline as "do before" in https://github.com/nodejs/build/blob/main/ONBOARDING.md#onboarding-to-build-test-issue-checklist

**Comment by targos** [comment]
works for me too

**Comment by mhdawson** [comment]
Sent invite. @MoLow, @targos both of you should have received it.

**Pull request merged**
