### PR TITLE
Add testing for nodejs.org

### PR DESCRIPTION
**Pull request by fhemberger**
First idea for implementing #191, a mocha test-suite issuing HEAD requests.
- [x] http/https links to dist tarballs
- [ ] http/https links to old windows x32/x64 builds
- [ ] http/https links to new windows x32/x64 builds (different file name/directory)
- [x] http/https links to dist/latest/, dist/latest-v0.10.x/, dist/latest-v0.12.x/
- [ ] http/https links to previous versions of the api docs
- [ ] http/https links for [subdomain].nodejs.org

One redirect test deliberately failing: https://blog.nodejs.org/ redirects to http://blog.nodejs.org/ (which redirects again) instead of redirecting directly to https://nodejs.org/en/blog/.

### CODE REVIEW

**Comment by fhemberger** [comment]
@nodejs/build Is this something useful for you to work with?

**Comment by rvagg** [comment]
@fhemberger yes, this is great, I probably wouldn't have chosen mocha but that's just personal bias and whoever starts the work gets to choose in my books

**Comment by fhemberger** [comment]
What would you prefer instead of mocha? It was just the first thing that came to my mind. I'd just like to use a test runner with simple, readable output, where everybody can add tests easily.

**Comment by rvagg** [comment]
it's fine, proceed as you prefer and we'll adapt

**Comment by jbergstroem** [comment]
This could alternatively be written as part of the nginx test tool (It's perl and annoying though). Benefit being it actually running against the web server config instead of testing the live stuff.

**Comment by DavidTPate** [comment]
I've been using [RunScope](https://www.runscope.com) for some of my Projects. They have a good method of configuration for tests against live systems as well as for running tests like CRON and also from multiple regions in the world with performance metrics and such.

They have a markup for importing tests which could be added to a repo and used to configure RunScope.

**Comment by fhemberger** [comment]
Hmm, not sure that RunScope is the right match. @jbergstroem If you want to port it, please go ahead (sorry, I don't do perl).

**Comment by jbergstroem** [comment]
@fhemberger was just thinking that it'd be great being able to reuse the nginx config as part of the test suite. I won't pursue this and since I'm not driving I don't get to decide where to turn :)

**Comment by fhemberger** [comment]
Closing this, there seems to be no interest in pursuing this idea further.

**Pull request closed without merging**
