### PR TITLE
doc: add minutes for wg meeting 2016-08-09

### PR DESCRIPTION
**Pull request by mhdawson**

### CODE REVIEW

**Comment by mhdawson** [comment]
@nodejs/build minutes from meeting yesterday. Please review and comment.

**Comment by Starefossen** [comment]
Minutes looks fine, just wondering about the outline (if you look at some of the previous minutes I have transcribed). I think the meeting agenda should be in the minutes.

**Comment by mhdawson** [comment]
@Starefossen pulled agenda from doc and added to minutes.

**Comment by jbergstroem** [comment]
LGTM

**Comment by mhdawson** [comment]
@Starefossen  look good to you now ?

**Comment by Starefossen** [comment]
LGTM 👍

**Comment by mhdawson** [comment]
Landed as c1533ba5bc63978b57cf93b6b881dbec5816c661

**Pull request closed without merging**
