### PR TITLE
ubuntu: add git-core PPA to 12.04

### PR DESCRIPTION
**Pull request by joaocgreis**
The version of git shipped with Ubuntu 12.04 is old, it cannot fetch from GitHub refs that were updated. This is an issue with Jenkins, since the test-commit job uses a reference that was updated by the push-merge-commit job.

/cc @nodejs/build

### CODE REVIEW

**Comment by orangemocha** [comment]
This is happening on 15.04 as well. https://jenkins-iojs.nodesource.com/job/node-test-commit-linux/62/nodes=ubuntu1504-64/console

Would it be safe to apply the same to all Ubuntu versions?

**Comment by joaocgreis** [comment]
@orangemocha It looks different though. I'll investigate as soon as I get access to that machine.

**Comment by orangemocha** [comment]
Ah, you are right. Perhaps 15.04 is just our of disk space?

**Comment by orangemocha** [comment]
LGTM

**Comment by joaocgreis** [comment]
I updated the server manually.

Here are the errors that we had, for future reference:

- While fetching a tag:

```
 > git -c core.askpass=true fetch --tags --progress https://github.com/joyent/node.git +refs/heads/*:refs/remotes/origin/* +refs/tags/jenkins-accept-commit-temp2:refs/remotes/origin/_jenkins_local_branch # timeout=20
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/joyent/node.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:763)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1012)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1043)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1284)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/joyent/node.git +refs/heads/*:refs/remotes/origin/* +refs/tags/jenkins-accept-commit-temp2:refs/remotes/origin/_jenkins_local_branch" returned status code 128:
stdout: 
stderr: remote: Counting objects: 5, done.
remote: Compressing objects: 100% (1/1)   
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
error: no such remote ref refs/tags/jenkins-accept-commit-temp2
```

- While fetching a branch:

```
 > git -c core.askpass=true fetch --tags --progress https://github.com/orangemocha/node-1.git +refs/heads/*:refs/remotes/origin/* +refs/heads/orangemocha-ConvergeCI:refs/remotes/origin/_jenkins_local_branch # timeout=20
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/orangemocha/node-1.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:763)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1012)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1043)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1284)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/orangemocha/node-1.git +refs/heads/*:refs/remotes/origin/* +refs/heads/orangemocha-ConvergeCI:refs/remotes/origin/_jenkins_local_branch" returned status code 128:
stdout: 
stderr: remote: Counting objects: 75, done.
remote: Compressing objects:  33% (1/3)   
remote: Compressing objects:  66% (2/3)   
remote: Compressing objects: 100% (3/3)   
remote: Compressing objects: 100% (3/3), done.
remote: Total 75 (delta 46), reused 46 (delta 46), pack-reused 26
error: no such remote ref refs/heads/orangemocha-ConvergeCI
```

**Comment by rvagg** [comment]
https://github.com/nodejs/build/issues/148#issuecomment-127220354 see also comment about 15.04 errors

**Pull request merged**
