### PR TITLE
Windows Ansible playbook optimization

### PR DESCRIPTION
**Pull request by piccoloaiutante**
Starting from suggestions for a good first contribution that I received (https://github.com/nodejs/build/issues/495) I've  added few extra steps to Windows Ansible scripts:

- Force Windows to do update
- Reboot machine if necessary after update installation
- Reboot machine after Visual Studio installation 

As per https://github.com/nodejs/build/issues/574 @joaocgreis can you test it on Windows 2008 Server R2 ? I already tested it on windows 10 and Windows Server 2012.

### CODE REVIEW

**Comment by jbergstroem** [comment]
Interesting! Question: does the reboot stuff really work? I've been fighting with ansible about waiting at reboots (for the host to come back up).

**Comment by piccoloaiutante** [comment]
@jbergstroem yes it worked on the two operating system that i tested but i want to have a definitive response for @joaocgreis about Windows 2008 Server.

Here is the doc for the windows version:
https://docs.ansible.com/ansible/win_reboot_module.html

**Comment by jbergstroem** [comment]
@piccoloaiutante no, i haven't tried windows rebooting at all -- its just a nightmare for !windows :\

**Comment by joaocgreis** [comment]
Landed in https://github.com/nodejs/build/commit/5cd0f41528bfa68885105e074f41afd9e31b0c62

I took the liberty to clean up a bit and add a small header (<50char) to the commit message, hope it's ok. I tested in Windows 2008R2, the reboot works beautifully. Thanks @piccoloaiutante !

**Comment by piccoloaiutante** [comment]
Excellent @joaocgreis now moving on generating .rdp and/or .remmina files.

**Pull request closed without merging**
