### PR TITLE
ansible: added keybox & ansible to inventory

### PR DESCRIPTION
**Pull request by rvagg**
@gdams I have put your github ssh key in both of these for now. If you put together an ansible script then I guess we can decide how to move forward when access control when we move closer to actually using these. Good luck & lemme know if you need any further help with these.

### CODE REVIEW

**Comment by gdams** [comment]
@rvagg thanks for these. Neither of them seem to be able to ping `8.8.8.8`. Any ideas?

**Comment by rvagg** [comment]
Doh! it's the quirky softlayer server config form, I seem to get this wrong every time, even when I do it thinking "yeah, I get this wrong every time, do it right this time" like I did for these machines! Fixed and working now @gdams

**Comment by gdams** [comment]
@rvagg `ubuntu1804-x64-2: {ip: 169.60.150.89, alias: ansible} ` seems to be properly broken but I'm not sure what's up.... If I do `apt-get install <package_name>` I get the following error:
```bash
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "en_GB.UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
(Reading database ... 105264 files and directories currently installed.)
Removing linux-image-4.15.0-23-generic (4.15.0-23.25) ...
/etc/kernel/postrm.d/initramfs-tools:
update-initramfs: Deleting /boot/initrd.img-4.15.0-23-generic
/etc/kernel/postrm.d/x-grub-legacy-ec2:
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Searching for GRUB installation directory ... found: /boot/grub
Searching for default file ... found: /boot/grub/default
Testing for an existing GRUB menu.lst file ... found: /boot/grub/menu.lst
uuid not supported. update 'groot' in /boot/grub/menu.lst

groot must be grub root device (ie '(hd0)'). not 'LABEL=cloudimg-rootfs'

run-parts: /etc/kernel/postrm.d/x-grub-legacy-ec2 exited with return code 1
dpkg: error processing package linux-image-4.15.0-23-generic (--remove):
 installed linux-image-4.15.0-23-generic package post-removal script subprocess returned error exit status 1
Errors were encountered while processing:
 linux-image-4.15.0-23-generic
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Perhaps it's easier to wipe the machine and start again unless somebody knows the fix to this?

**Comment by rvagg** [comment]
Turn out to be an Ubuntu 18.04 + SoftLayer problem. I tried re-imaging that machine and then reprovisioning an entirely new one in a different DC but the problem repeats whenever you do apt update && apt dist-upgrade -y && apt-get autoremove -y`. I suppose the other machine is susceptible too. Googling isn't much help but I found a solution through a bit of trial and error: uncomment `groot=LABEL=cloudimg-rootfs` in /boot/grub/menu.lst does the trick. grub runs properly and reboot is successful. grub actually decides to interpret this in its own way though and rewrites menu.lst to `(hd0)` anyway .. so whatever, as long as it works.

Good to go now @gdams but fetch the new ip address from my force pushed commit here.

btw in case you didn't know you can `ansible-playbook playbooks/write-ssh-config.yml` and then ssh to `infra-softlayer-ubuntu1804-x64-2`. Your choice though cause it'll pollute your .ssh/config.

**Comment by mhdawson** [comment]
I'll talk to @gdams to validate 2 need to 2 machines as opposed to 1

**Comment by rvagg** [comment]
@nodejs/build we need to talk about what to do with these two pieces of infra post-George

**Comment by rvagg** [comment]
Just confirmed these are still running, keybox last login July 4th, ansible last login Sept 7. I think we need to discard these since we don't have a champion for it. I really like keybox though and it'd be a real help.

**Comment by mhdawson** [comment]
It would be great to have keybox running, but we would need to find a champion.

**Comment by sam-github** [comment]
I'm not sure this needs live discussion, can we remove from the agenda? Or roll it to a WG meeting that @rvagg (who labelled it with agenda) can attend?

**Comment by rvagg** [comment]
🤷‍♂ I'm not sure to do with this exactly. Maybe retire the resources and just wait for a new champion. I was particularly keen on the keybox possibilities. One nice thing about keybox is that it may lighten the load on "give me access to X" requests, make them much less manual and easier to manage. There could be real time savings in that.

**Comment by sam-github** [comment]
It's pretty easy to insert ssh keys into .ssh/authorized_keys files, and takes no knowlege specific to node's CI, and no specific server to maintain (sec updates, restart on failure, etc). Maybe its just as easy to paste into some web UI, but I'm not keen to have to troubleshoot why it doesn't work with (say) z/os or AIX or Windows. All of which is to say, I'm on board with infrastructure simplification before extension. Of course, if someone wants to offer to get this up and keep it running, that's different.

**Comment by mhdawson** [comment]
At this point I think we may need to just retire as @rvagg suggests.  I think its a good idea but unless we have somebody who might reasonably start working on it we might as well free the resources and close.

**Comment by rvagg** [comment]
👍 machines removed

**Pull request closed without merging**
