### PR TITLE
ansible: add new plinux machines

### PR DESCRIPTION
**Pull request by AshCripps**
Looks like the other two need rebuilding so will also handle that in this PR

### CODE REVIEW

**Review by richardlau — APPROVED** [review]

**Comment by AshCripps** [comment]
@nodejs/build-infra can some update the IPs in the firewall for `-1` and `-2` for the ones in this PR please?

**Comment by richardlau** [comment]
> @nodejs/build-infra can some update the IPs in the firewall for `-1` and `-2` for the ones in this PR please?

Done!

**Comment by AshCripps** [comment]
ok both replacement machines up and running

**Review by richardlau — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
