### PR TITLE
doc: add bnoordhuis to members

### PR DESCRIPTION
**Pull request by bnoordhuis**
Can I self-nominate? :-)

### CODE REVIEW

**Comment by sam-github** [comment]
https://github.com/nodejs/build/blob/master/doc/access.md#joining-the-build-working-group

I support adding @bnoordhuis to the build WG and asked him to apply to join.

He has a long history with Node.js (understatement), is an IBM employee, and has been getting ad-hoc access repeatedly to sort out difficulties. Having him just have access would make it easier for him to contribute without having to ask a build WG member to setup access each time.

**Comment by mhdawson** [comment]
+1 as it will allow @bnoordhuis to help out more easily on IBM machines as well as on other platforms as well.

**Comment by sam-github** [comment]
I'll merge this, and attempt to reproduce what @rvagg did in https://github.com/nodejs/build/pull/1787#issuecomment-486892964 tomorrow --- unless someone thinks we should give more time for review?

It looks like I just have to add @bnoordhuis to some github groups, and then add his key to secrets. I haven't done that before, but I think I have the credentials to do so. I guess I'll find out.

**Comment by sam-github** [comment]
@bnoordhuis, I invited you to nodejs/build and nodejs-private/build

I need from you:
1. a gpg key to add to the secrets repo
2. confirmation you can checkout https://github.com/nodejs-private/secrets

**Comment by bnoordhuis** [comment]
@sam-github My public key's below and I can access the secrets repo.

<details>

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFG40K8BEAC/Z2FlSWi7CGdK/28mFwNFcKW8py5Bo9CpXmgXsjVrvmPZCrE4
m3vzrCRUgmcQ2RrDp6KBfNeVL6QQFLLrU/yd2deiekhxaLwfAo472dn9TMDput5+
6Tu1kiM5H2Yrpc6D9gEmyqMZGXwG10hAgVdE7fFa7MohRUQLcKXogFQdNVyXYzTa
OUWuDpzVibccXFVnJU3Tm1XbQNDxaft15Lw4kGSlnEl79wVnqF3LM1uFm8BCPOu0
e3kFlmOacWZze17BDk8OBYhkQjsSyu8cX8WgX10Gc2ihULV2xYOB3krcxAsksfyo
B9FsX5+bCFViFRrglx5P4BNdhIbpvFPgNgusTSxtq1lNKCu0Ms9wum20d9F807Z8
g7Rw5D2iP2NNPU04nKM3WdTUwMpGRDE5BsV4uIimZcY6wcTv9xdqn/nnyqMgb3vr
Un8k7h8F6FgrxCs86OCDI4NLiFMOpIUIBVS1LBM/Gmji0nuzoHg5dfkdT8YmPom4
Tx/5ChkzFOE06mRH9rdzdRcX3MMSwLvzgtRDnF/Lb54RRK5H7WMEPCxhVe1QkZC1
3gP4GBw5vUjwaQdTmS4TCflRA8UU+JbLeYsdppmvOTvuE+Ixf3KbRaRjdegTiNFx
b0bpTouXcjm+3GCmO3m9wr9t07TKaFJS4PtlxnulyzK89hcflvRSzOJIgwARAQAB
tCJCZW4gTm9vcmRodWlzIDxpbmZvQGJub29yZGh1aXMubmw+iQI4BBMBAgAiBQJR
uNCvAhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRBPVcjIRquJudHZD/9U
+VAGhR0r6bip1nPsgmC9JDiTxvyJ74U9dkhXZBbySfcEVbtpJGGxi9+bdRWolhSZ
oYgxWjiQBo0RlaYdJC0vZud2NfBh5t3YAzes03XkcQ7UCCFivVwCmX9S2S/coE19
3RW3sYreEOzmcf+JUEVl2nFIcjmTjXlVOM10BB3I9r5w0vSe7gOvG7+VDktN5QBT
F/EkPrFHC27GBwj8cqjcT18l7gZYe2rpX3NWW6FzoUeUPDiY2ajrPBvlJzpdAv1y
sWuqefSCy0ZSkw9LQrkgfLG5WinUGw26TNBYF4H9Ci/Ls0b8vEapyu4Mf/Xqxe0r
V7QCjCS3WN+fnU9iwhsmr4jfa/TLT7W17ycvszD7CCAafkLHOOpEaS6Iv8i/T687
vove0INl3QEmExqf/VRlqPaKSmG744W9a9kgwzQssFJz5PJtgIpGkJhIZmFawfI7
LBO/qWrIFgj1blt5nbIYwkl6y2qJP7yuOIItdZeGwA4H/FpJ1ylH5L/roM9jBpPx
BYIRJtENj1EopLQ046rpHzgRUjeA4j5DIDLb6QYsm7nFRqH5UgoZHfwZCmJ6uHmT
pQRMQXoE+SAYRa+V+hh3s/g8xieydUSOmWA2M9AgVJAc/uWVbuTxwLtDondhdurO
TmyaZU88CbLBHta8KIb6cKoqyST6qLIx3yEqTjxDEbkCDQRRuNCvARAAy6yClJou
KC4PNjpq4TZ0QgPVdbhgG98yCQu3E19uxk4aIQtMbFLWbzRu2vtdaUvXOdSH/vCZ
OS5DkSkwimbLg0dE/+iJ9ZD+OejluQdULQzCfqRLCLNYKgh6XOE0qqyMQqVSccTx
ldNTVuQXFqOOaqlEDgquu4jdeS7SdrPXYLu+I37raCpJP7kk8IMQvahlbgLSqNL+
yHFPKmcv7pq+Vz0ca8bS79b218kUWXtRFHstSXwThG+ii1lUjsd3gwsE4S4654Dk
FrZ6SvR40NUqel7BwWiZDbasTUDUmCCf66khvenPI0B+Eo9x9WFA1xaS5Qph4zox
b9f0BwTErL86NqCv8uKcU/Tmu7G18tRGOeO78aYXt1/TIOoYpeG3gTZU4fVUIRyA
KxBKyl3eKORMJDc2B1YWb0O6dzIMNDrP2od5VqjyyEOuC99+fhJaaAVEj9pll5af
D1t6O3zCji2PvkIb4YE4XdZgBiQdm4WXppiZFaDmJp+N97S5uctMwEmxsV05dMZp
y7L3AIMOOFaoPcNx29wZlny6FAuNcIi5Hl8auib2s3BEPfRyPDrRLD97SG3MS1IL
jJIhJqLAj/BaUi56LfYWhbUU+/dF5y2EANE0oTL+R3xN2PCaeJflsGd47S2xTgQM
Jk8QQk5rhy16WsRJQr9CW6seY64gsAmSZPkAEQEAAYkCHwQYAQIACQUCUbjQrwIb
DAAKCRBPVcjIRquJucVLD/9PYJZRv9kTLLg0tGqI94HKYiQPn2vqpj7oVM1FrhbS
TR2owsMKQ4EWaadKoWDPQ6wVm/X8Uq7fMBqu3mRyF90oYxkdbd9iyiSOsV8QMcvG
hzk0x9x/hZ3Dgm+KVQ0G3Pgm1tHhDG+W9I6xrn/aawqxAplY3DC910xWaiA9UCDx
WhQTBIWJhvvphzT/y5eeN4momQk5oUnAMAZqdGrLaDjAqaNErF7zQvdD/7Dz+h80
iQEiMxiIYxgqVPMNSpxF7gm9DzcjnNonktyvZ5soD3AuvmkUWeno0aYJKRYhYKa1
IaupVKvT2V+AmPas0W4J+cFLSGIlyRHxQE6uogvc7yrId8Yb7SLIz2rV+wnQ5sA8
P4JPHtK9MuUW9yYurxuAshwgVx289aIJhZiRgcCrOv/c7wcEBkKair9eJN+bjkQE
tH4N2wdz9hLkDQE8rf80133Z0PdT5Er8ZZG4fIFWc+qr5y74Hjsy0mm1go/WazLZ
b/D5D/2XJJl5VqY3BoEX/PMKL9BzsNpPJVnbibjFa8Sdw141I4ZJCz5VsvBzi6sU
eDgaZdTLHvYRiI2tPVYa/EnnM/pPrzF1aVTxjXQjFuBi5BK6wVrFD3x7g4v0P9cW
zX/tLlaQ/d5GMDCGpTV+/eo6O3ui6UWw0XwsjG+S3W3EMYNjDYLooUhdM3aU5MUx
WQ==
=yuic
-----END PGP PUBLIC KEY BLOCK-----
```
</details>

It's the same key I use to sign e.g. node-gyp release tags in case you want some external verification. ^^

**Comment by sam-github** [comment]
@bnoordhuis PTAL: https://github.com/nodejs-private/secrets/pull/45

**Pull request merged**
