### PR TITLE
update redirect for security page

### PR DESCRIPTION
**Pull request by Trott**
Refs: https://github.com/nodejs/nodejs.org/pull/4280

### CODE REVIEW

**Comment by Trott** [comment]
@nodejs/security-triage

**Review by danielleadams — APPROVED** [review]

**Comment by Trott** [comment]
What would be the process for this? If I land it, does it automatically deploy? Or does someone with the right permissions need to run the ansible script?

**Comment by Trott** [comment]
(I goofed and forgot to wait for this to land before landing the change to nodejs.org, so landing this promptly would be a good thing.)

**Comment by Trott** [comment]
> What would be the process for this? If I land it, does it automatically deploy? Or does someone with the right permissions need to run the ansible script?

@nodejs/build

**Comment by richardlau** [comment]
> What would be the process for this? If I land it, does it automatically deploy? Or does someone with the right permissions need to run the ansible script?

The short answer is no, it's not an automatic deployment.

https://github.com/nodejs/build/blob/master/ansible/www-standalone/README.md has this disclaimer:
> Not actively tested against the live server so may not be idempotent.

which is basically saying that it might not be safe to run the playbook against the live server. So what more likely needs to happen is someone from @nodejs/build-infra (including myself) needs to make an equivalent edit on the `nodejs.org` nginx config file on the server and then restart nginx. I'll do that now 🤞.

**Comment by Trott** [comment]
> So what more likely needs to happen is someone from @nodejs/build-infra (including myself) needs to make an equivalent edit on the `nodejs.org` nginx config file on the server and then restart nginx. I'll do that now 🤞.

Seems to be working to me. Thanks!

**Pull request merged**
