### PR TITLE
ansible: add test-digitalocean-freebsd13-x64-1

### PR DESCRIPTION
**Pull request by richardlau**
Refs: https://github.com/nodejs/build/issues/3593

---

Test builds:
- v18.x-staging: https://ci.nodejs.org/job/richardlau-node-test-commit-freebsd/1/
- v20.x-staging: https://ci.nodejs.org/job/richardlau-node-test-commit-freebsd/3/
- v22.x-staging: https://ci.nodejs.org/job/richardlau-node-test-commit-freebsd/4/
- main: https://ci.nodejs.org/job/richardlau-node-test-commit-freebsd/5/

v22.x-staging and main will probably fail due to https://github.com/nodejs/node/issues/54576.

### CODE REVIEW

**Comment by richardlau** [comment]
> Test builds:
> 
>     * v18.x-staging: https://ci.nodejs.org/view/All/job/richardlau-node-test-commit-freebsd/1/
> 
>     * v20.x-staging: https://ci.nodejs.org/view/All/job/richardlau-node-test-commit-freebsd/2/
> 

hmm. v18.x-staging build passed.
v20.x-staging build failed twice in a row with the agent disconnecting while running tests 😞.

**Comment by richardlau** [comment]
> v20.x-staging build failed twice in a row with the agent disconnecting while running tests 😞.

The new FreeBSD 13 machine compared to the existing FreeBSD 12 machine has the same amount of RAM (2 GB) and vCPUs (2). It appears to have half the amount of available swap (1 GB vs 2 GB) -- I'll see if increasing that helps.

**Comment by richardlau** [comment]
> 
> test CI (v20.x-staging): https://ci.nodejs.org/job/richardlau-node-test-commit-freebsd/7/

Passed!

Double check test runs (since the machine was reimaged):
- v18.x-staging: https://ci.nodejs.org/job/richardlau-node-test-commit-freebsd/8/

**Review by targos — APPROVED** [review]

**Comment by richardlau** [comment]
I think my plan for this is:
- Merge/land this PR.
- Open another PR to exclude FreeBSD 13 for now on Node.js >= 22 (similar to the case with FreeBSD 12 now). If someone can figure out how to fix the build for Node.js >= 22 we can add it back later.
- Update the main [node-test-commit-freebsd](https://ci.nodejs.org/job/node-test-commit-freebsd/) job to build on FreeBSD 13 instead of 12. Probably after the release proposal for Node.js 20.18.0 is done to not get in the way of it 🙂.
- Migrate the FreeBSD 12 machines to 13. I'm actually not sure on this one whether it's better to retire these and create a new droplet for a second FreeBSD 13 machine as, if I'm reading correctly, it appears the new FreeBSD droplet is cheaper than the existing FreeBSD 12 ones?

**Pull request merged**
